ArcaneFem: FemModuleSoildynamics Class Reference
FemModuleSoildynamics Class Reference
Module Fem.
#include <modules/soildynamics/FemModule.h>
Public Member Functions
FemModuleSoildynamics (const ModuleBuildInfo &mbi)
void startInit () override
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
void _assembleBilinearOperatorTria3Gpu ()
void _assembleBilinearOperatorTetra4Gpu ()
void _assembleDirichletsGpu ()
Applies dirichlet to LHS matrix and RHS vector of the linear system on Gpu.
Private Member Functions
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _getParameters ()
void _updateVariables ()
void _updateTime ()
void _assembleBilinearOperator ()
void _solve ()
void _assembleLinearOperator ()
void _applyDirichletBoundaryConditions ()
void _validateResults ()
void _readCaseTables ()
RealMatrix< 4, 4 > _computeParaxialElementMatrixEdge2 (Face face)
Computes 2D paraxial element matrix for a edge element (ℙ1 FE).
RealMatrix< 6, 6 > _computeElementMatrixTria3 (Cell cell)
Computes 2D problem element matrix for a triangular element (ℙ1 FE)
RealMatrix< 9, 9 > _computeParaxialElementMatrixTria3 (Face face)
Computes 3D paraxial element matrix for a triangular element (ℙ1 FE).
RealMatrix< 12, 12 > _computeParaxialElementMatrixQuad4 (Face face)
Computes 3D paraxial element matrix for a quadrangular element (ℙ1 FE).
RealMatrix< 12, 12 > _computeElementMatrixTetra4 (Cell cell)
Computes 3D problem element matrix for a tetrahedral element (ℙ1 FE).
RealMatrix< 8, 8 > _computeElementMatrixQuad4 (Cell cell)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
RealMatrix< 24, 24 > _computeElementMatrixHexa8 (Cell cell)
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
void _applyTraction (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies traction to the RHS vector of the linear system.
void _applyDoubleCouple (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies double-couple boundary conditions to the RHS values.
void _applyParaxial (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof, BSRMatrix *bsr_matrix=nullptr)
Applies paraxial boundary conditions to the RHS and LHS of the linear system.
void _applySourceTerm (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies source term to RHS vector of the linear system.
void _applySourceTermTria3 (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
void _applySourceTermQuad4 (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
void _applySourceTermTetra4 (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
void _applySourceTermHexa8 (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
void _applyDirichlet (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies dirichlet to LHS matrix and RHS vector of the linear system.
template<int N>
void _assembleBilinearOperatorCpu (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the FEM bilinear operator on CPU.
Private Attributes
Real t
Real dt
Real tmax
Real beta
Real gamma
Real3 f = {0,0,0}
Real E
Real nu
Real rho
Real mu
Real lambda
Real cp
Real cs
Real c0
Real c1
Real c2
Real c3
Real c4
Real c5
Real c6
Real c7
Real c8
Real c9
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_hex_quad_mesh = false
DoFLinearSystem m_linear_system
FemDoFsOnNodes m_dofs_on_nodes
BSRFormat m_bsr_format
UniqueArray< CaseTableInfo > m_traction_case_table_list
UniqueArray< CaseTableInfo > m_double_couple_case_table_list
Detailed Description
Module Fem.
Definition at line 50 of file soildynamics/FemModule.h.
Constructor & Destructor Documentation
FemModuleSoildynamics()
FemModuleSoildynamics::FemModuleSoildynamics (const ModuleBuildInfo & mbi) inline explicit
Definition at line 55 of file soildynamics/FemModule.h.
~FemModuleSoildynamics()
FemModuleSoildynamics::~FemModuleSoildynamics () inline
Definition at line 64 of file soildynamics/FemModule.h.
Member Function Documentation
_applyDirichlet()
void FemModuleSoildynamics::_applyDirichlet (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) private
Applies dirichlet to LHS matrix and RHS vector of the linear system.
This function applies Dirichlet boundary conditions to both the LHS matrix and RHS vector of the linear system.
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 26 of file soildynamics/Dirichlet.h.
References _assembleDirichletsGpu(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToRhs(), ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToRhs().
_applyDoubleCouple()
void FemModuleSoildynamics::_applyDoubleCouple (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) private
Applies double-couple boundary conditions to the RHS values.
This function iterates over the defined double-couple boundary conditions, retrieves the corresponding force values from the associated CaseTable, and updates the RHS values for the specified nodes accordingly.
Parameters
rhs_values The RHS values to be updated.
node_dof The node DoF connectivity view.
/*------------------------------------------------------------------------—
Definition at line 27 of file DoubleCouple.h.
_applyParaxial()
void FemModuleSoildynamics::_applyParaxial (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof, BSRMatrix * bsr_matrix = nullptr) private
Applies paraxial boundary conditions to the RHS and LHS of the linear system.
Parameters
rhs_values The RHS values to be updated.
node_dof The node DoF connectivity view.
bsr_matrix The BSR matrix to be updated (optional).
/*------------------------------------------------------------------------—
Definition at line 131 of file Paraxial.h.
References _computeParaxialElementMatrixEdge2(), _computeParaxialElementMatrixQuad4(), _computeParaxialElementMatrixTria3(), ArcaneFemFunctions::MeshOperation::computeAreaQuad4(), ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::MeshOperation::computeLengthEdge2(), and Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_applySourceTerm()
void FemModuleSoildynamics::_applySourceTerm (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) private
Applies source term to RHS vector of the linear system.
This function computes the contribution of the source term to the right-hand side (RHS) vector of the linear system based on the mesh dimension.
source term = ∫∫∫ (𝐟.𝐯) + ∫∫∫ (c₀)(𝐮ₙ.𝐯) + ∫∫∫ (c₃)(𝐮ᵗₙ.𝐯) + ∫∫∫ (c₄)(𝐮ᵗᵗₙ.𝐯)
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 29 of file soildynamics/SourceTerm.h.
_applySourceTermHexa8()
void FemModuleSoildynamics::_applySourceTermHexa8 (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) private
Definition at line 212 of file soildynamics/SourceTerm.h.
_applySourceTermQuad4()
void FemModuleSoildynamics::_applySourceTermQuad4 (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) private
Definition at line 90 of file soildynamics/SourceTerm.h.
_applySourceTermTetra4()
void FemModuleSoildynamics::_applySourceTermTetra4 (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) private
Definition at line 159 of file soildynamics/SourceTerm.h.
_applySourceTermTria3()
void FemModuleSoildynamics::_applySourceTermTria3 (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) private
Definition at line 46 of file soildynamics/SourceTerm.h.
_applyTraction()
void FemModuleSoildynamics::_applyTraction (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) private
Applies traction to the RHS vector of the linear system.
This function computes the contribution of traction to the RHS vector of the linear system. It iterates over all cells in the mesh, calculates the appropriate force contributions based on the element type and mesh dimension, and updates the RHS vector accordingly.
traction term ∫∫ (𝐭.𝐯) with 𝐭 = (𝑡𝑥, 𝑡𝑦, 𝑡𝑧) = (t[0], t[1], t[2])
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding degrees of freedom (DoFs).
/*------------------------------------------------------------------------—
Definition at line 31 of file soildynamics/Traction.h.
References ArcaneFemFunctions::BoundaryConditions3D::applyTractionTableToRhsTetra4(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsTria3(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsTetra4(), and ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsTria3().
_assembleBilinearOperator()
void FemModuleSoildynamics::_assembleBilinearOperator () private
Definition at line 328 of file soildynamics/FemModule.cc.
_assembleBilinearOperatorCpu()
template<int N> void FemModuleSoildynamics::_assembleBilinearOperatorCpu (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the FEM bilinear operator on CPU.
This method assembles the FEM stiffness matrix by iterating over each cell, computing the element stiffness matrix using the provided function, and populating the global stiffness matrix accordingly.
Template Parameters
N Total DOF size (nodes_per_element × dimensions).
Parameters
compute_element_matrix function computing cell's element stiffness matrix.
Definition at line 426 of file soildynamics/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleBilinearOperatorTetra4Gpu()
void FemModuleSoildynamics::_assembleBilinearOperatorTetra4Gpu ()
Definition at line 394 of file soildynamics/FemModule.cc.
_assembleBilinearOperatorTria3Gpu()
void FemModuleSoildynamics::_assembleBilinearOperatorTria3Gpu ()
Definition at line 373 of file soildynamics/FemModule.cc.
_assembleDirichletsGpu()
void FemModuleSoildynamics::_assembleDirichletsGpu ()
Applies dirichlet to LHS matrix and RHS vector of the linear system on Gpu.
This function applies Dirichlet boundary conditions to both the LHS matrix and RHS vector of the linear system using GPU acceleration.
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 82 of file soildynamics/Dirichlet.h.
Referenced by _applyDirichlet().
_assembleLinearOperator()
void FemModuleSoildynamics::_assembleLinearOperator () private
Definition at line 294 of file soildynamics/FemModule.cc.
_computeElementMatrixHexa8()
RealMatrix< 24, 24 > FemModuleSoildynamics::_computeElementMatrixHexa8 (Cell cell) private
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫∫ [(∂²𝐮/∂𝑡²).(𝐯)] dΩ + ∫∫∫ [σ(𝐮):ε(𝐯)] dΩ
with trial function 𝐮 = (𝑢𝑥, 𝑢𝑦, 𝑢𝑧) and test function 𝐯 = (𝑣𝑥, 𝑣𝑦, 𝑣𝑧), σ(𝐮) is the stress tensor, given by σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is the strain tensor, defined as εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
The bilinear integral after applying the Newmark-Beta scheme and damping terms expands to:
a(𝐮,𝐯) = ∫∫∫ (c₀)(𝐮⋅𝐯)
∫∫∫ (c₁) (∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑦/∂𝑦)
∫∫∫ (c₂)(2(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧) + (∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥) + (∂𝑢𝑧/∂𝑦 + ∂𝑢𝑦/∂𝑧)(∂𝑣𝑦/∂𝑧 + ∂𝑣𝑧/∂𝑦) + (∂𝑢𝑥/∂𝑧 + ∂𝑢𝑧/∂𝑥)(∂𝑣𝑧/∂𝑥 + ∂𝑣𝑥/∂𝑧))
with c₀ = (ρ)/(β δ𝑡²) + (ηₘ ρ γ)/(β δ𝑡) c₁ = λ + (λ ηₖ γ)/(β δ𝑡) c₂ = 2μ + (2μ ηₖ γ)/(β δ𝑡)
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianHexa8
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 129 of file soildynamics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), ArcaneFemFunctions::FeOperation3D::computeShapeFunctionsHexa8(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
_computeElementMatrixQuad4()
RealMatrix< 8, 8 > FemModuleSoildynamics::_computeElementMatrixQuad4 (Cell cell) private
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
Theory: a(𝐮,𝐯) = ∫∫ [(∂²𝐮/∂𝑡²).(𝐯)]dΩ + ∫∫ [σ(𝐮):ε(𝐯)]dΩ
with trial func 𝐮 = (𝑢𝑥,𝑢𝑦) and test func 𝐯 = (𝑣𝑥,𝑣𝑦), σ(𝐮) is stress tensor with σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is strain tensor with εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
the bilinear integral after Newmark-Beta and damping terms expands to:
a(𝐮,𝐯) = ∫∫ (c₀)(𝐮.𝐯)
∫∫ (c₁)(∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦)
∫∫ (c₁+2c₂)(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦)
∫∫ (c₂)(∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥)
with c₀ = (ρ)/(β δ𝑡²) + (ηₘ ρ γ)/(β δ𝑡) c₁ = λ + (λ ηₖ γ)/(β δ𝑡) c₂ = 2μ + (2μ ηₖ γ)/(β δ𝑡)
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 49 of file soildynamics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), ArcaneFemFunctions::FeOperation2D::computeShapeFunctionsQuad4(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
_computeElementMatrixTetra4()
RealMatrix< 12, 12 > FemModuleSoildynamics::_computeElementMatrixTetra4 (Cell cell) private
Computes 3D problem element matrix for a tetrahedral element (ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫∫ [(∂²𝐮/∂𝑡²).(𝐯)] dΩ + ∫∫∫ [σ(𝐮):ε(𝐯)] dΩ
with trial function 𝐮 = (𝑢𝑥, 𝑢𝑦, 𝑢𝑧) and test function 𝐯 = (𝑣𝑥, 𝑣𝑦, 𝑣𝑧), σ(𝐮) is the stress tensor, given by σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is the strain tensor, defined as εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
The bilinear integral after applying the Newmark-Beta scheme and damping terms expands to:
a(𝐮,𝐯) = ∫∫∫ (c₀)(𝐮 ⋅ 𝐯) dΩ
∫∫∫ (c₁) (∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑦/∂𝑦)
∫∫∫ (c₂)(2(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧) + (∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥) + (∂𝑢𝑧/∂𝑦 + ∂𝑢𝑦/∂𝑧)(∂𝑣𝑦/∂𝑧 + ∂𝑣𝑧/∂𝑦) + (∂𝑢𝑥/∂𝑧 + ∂𝑢𝑧/∂𝑥)(∂𝑣𝑧/∂𝑥 + ∂𝑣𝑥/∂𝑧))
with c₀ = (ρ)/(β δ𝑡²) + (ηₘ ρ γ)/(β δ𝑡) c₁ = λ + (λ ηₖ γ)/(β δ𝑡) c₂ = 2μ + (2μ ηₖ γ)/(β δ𝑡)
Definition at line 159 of file soildynamics/ElementMatrix.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
_computeElementMatrixTria3()
RealMatrix< 6, 6 > FemModuleSoildynamics::_computeElementMatrixTria3 (Cell cell) private
Computes 2D problem element matrix for a triangular element (ℙ1 FE)
Theory:
a(𝐮,𝐯) = ∫∫ [(∂²𝐮/∂𝑡²).(𝐯)]dΩ + ∫∫ [σ(𝐮):ε(𝐯)]dΩ
with trial func 𝐮 = (𝑢𝑥,𝑢𝑦) and test func 𝐯 = (𝑣𝑥,𝑣𝑦), σ(𝐮) is stress tensor with σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is strain tensor with εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
the bilinear integral after Newmark-Beta and damping terms expands to:
a(𝐮,𝐯) = ∫∫ (c₀)(𝐮.𝐯)
∫∫ (c₁)(∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦)
∫∫ (c₁+2c₂)(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦)
∫∫ (c₂)(∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥)
with c₀ = (ρ)/(β δ𝑡²) + (ηₘ ρ γ)/(β δ𝑡) c₁ = λ + (λ ηₖ γ)/(β δ𝑡) c₂ = 2μ + (2μ ηₖ γ)/(β δ𝑡)
Definition at line 39 of file soildynamics/ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
_computeParaxialElementMatrixEdge2()
RealMatrix< 4, 4 > FemModuleSoildynamics::_computeParaxialElementMatrixEdge2 (Face face) private
Computes 2D paraxial element matrix for a edge element (ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫ (cₚ 𝑁𝑥² + cₛ 𝑁𝑦²)(𝑢𝑥 𝑣𝑥) + ∫ (cₚ 𝑁𝑦² + cₛ 𝑁𝑥²)(𝑢𝑦 𝑣𝑦) + ∫ (𝑁𝑦 𝑁𝑥 (cₚ - cₛ))(𝑢𝑥 𝑣𝑦) + ∫ (𝑁𝑥 𝑁𝑦 (cₚ - cₛ))(𝑢𝑦 𝑣𝑥) ;
with trial func 𝐮 = (𝑢𝑥,𝑢𝑦) and test func 𝐯 = (𝑣𝑥,𝑣𝑦)
Definition at line 29 of file Paraxial.h.
References ArcaneFemFunctions::MeshOperation::computeNormalEdge2().
Referenced by _applyParaxial().
_computeParaxialElementMatrixQuad4()
RealMatrix< 12, 12 > FemModuleSoildynamics::_computeParaxialElementMatrixQuad4 (Face face) private
Computes 3D paraxial element matrix for a quadrangular element (ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫ (cₚ 𝑁𝑥² + cₛ (1 - 𝑁𝑥²))(𝑢𝑥 𝑣𝑥) + ∫∫ (cₚ 𝑁𝑦² + cₛ (1 - 𝑁𝑦²))(𝑢𝑦 𝑣𝑦) + ∫∫ (cₚ 𝑁𝑧² + cₛ (1 - 𝑁𝑧²))(𝑢𝑧 𝑣𝑧) + ∫∫ (𝑁𝑥 𝑁𝑦 (cₚ - cₛ))(𝑢𝑥 𝑣𝑦) + ∫∫ (c₇)(𝑁𝑥 𝑁𝑧 (cₚ - cₛ))(𝑢𝑥 𝑣𝑧) + ∫∫ (𝑁𝑦 𝑁𝑥 (cₚ - cₛ))(𝑢𝑦 𝑣𝑥) + ∫∫ (c₇)(𝑁𝑦 𝑁𝑧 (cₚ - cₛ))(𝑢𝑦 𝑣𝑧) + ∫∫ (𝑁𝑧 𝑁𝑥 (cₚ - cₛ))(𝑢𝑧 𝑣𝑥) + ∫∫ (c₇)(𝑁𝑧 𝑁𝑦 (cₚ - cₛ))(𝑢𝑧 𝑣𝑦) ;
with trial function 𝐮 = (𝑢𝑥, 𝑢𝑦, 𝑢𝑧) and test function 𝐯 = (𝑣𝑥, 𝑣𝑦, 𝑣𝑧)
Definition at line 99 of file Paraxial.h.
References ArcaneFemFunctions::MeshOperation::computeNormalQuad().
Referenced by _applyParaxial().
_computeParaxialElementMatrixTria3()
RealMatrix< 9, 9 > FemModuleSoildynamics::_computeParaxialElementMatrixTria3 (Face face) private
Computes 3D paraxial element matrix for a triangular element (ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫ (cₚ 𝑁𝑥² + cₛ (1 - 𝑁𝑥²))(𝑢𝑥 𝑣𝑥) + ∫∫ (cₚ 𝑁𝑦² + cₛ (1 - 𝑁𝑦²))(𝑢𝑦 𝑣𝑦) + ∫∫ (cₚ 𝑁𝑧² + cₛ (1 - 𝑁𝑧²))(𝑢𝑧 𝑣𝑧) + ∫∫ (𝑁𝑥 𝑁𝑦 (cₚ - cₛ))(𝑢𝑥 𝑣𝑦) + ∫∫ (c₇)(𝑁𝑥 𝑁𝑧 (cₚ - cₛ))(𝑢𝑥 𝑣𝑧) + ∫∫ (𝑁𝑦 𝑁𝑥 (cₚ - cₛ))(𝑢𝑦 𝑣𝑥) + ∫∫ (c₇)(𝑁𝑦 𝑁𝑧 (cₚ - cₛ))(𝑢𝑦 𝑣𝑧) + ∫∫ (𝑁𝑧 𝑁𝑥 (cₚ - cₛ))(𝑢𝑧 𝑣𝑥) + ∫∫ (c₇)(𝑁𝑧 𝑁𝑦 (cₚ - cₛ))(𝑢𝑧 𝑣𝑦) ;
with trial function 𝐮 = (𝑢𝑥, 𝑢𝑦, 𝑢𝑧) and test function 𝐯 = (𝑣𝑥, 𝑣𝑦, 𝑣𝑧)
Definition at line 61 of file Paraxial.h.
References ArcaneFemFunctions::MeshOperation::computeNormalTriangle().
Referenced by _applyParaxial().
_doStationarySolve()
void FemModuleSoildynamics::_doStationarySolve () private
Performs a stationary solve for the FEM system.
This method follows via the following steps:
_assembleBilinearOperator() Assembles the FEM matrix 𝐀
_assembleLinearOperator() Assembles the FEM RHS vector 𝐛
_solve() Solves for solution vector 𝐮 = 𝐀⁻¹𝐛
_updateVariables() Updates FEM variables 𝐮 = 𝐱
Definition at line 115 of file soildynamics/FemModule.cc.
Referenced by compute().
_getParameters()
void FemModuleSoildynamics::_getParameters () private
Definition at line 131 of file soildynamics/FemModule.cc.
_readCaseTables()
void FemModuleSoildynamics::_readCaseTables () private
Definition at line 209 of file soildynamics/FemModule.cc.
_solve()
void FemModuleSoildynamics::_solve () private
Definition at line 460 of file soildynamics/FemModule.cc.
_updateTime()
void FemModuleSoildynamics::_updateTime () private
Definition at line 97 of file soildynamics/FemModule.cc.
_updateVariables()
void FemModuleSoildynamics::_updateVariables () private
Definition at line 239 of file soildynamics/FemModule.cc.
_validateResults()
void FemModuleSoildynamics::_validateResults () private
Definition at line 475 of file soildynamics/FemModule.cc.
compute()
void FemModuleSoildynamics::compute () override
Method called at the beginning of the simulation.
Definition at line 26 of file soildynamics/FemModule.cc.
References _doStationarySolve(), Arcane::FemUtils::DoFLinearSystem::clearValues(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), Arcane::FemUtils::DoFLinearSystem::isInitialized(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleSoildynamics::startInit () override
Definition at line 67 of file soildynamics/FemModule.cc.
versionInfo()
VersionInfo FemModuleSoildynamics::versionInfo () const inline override
Method called at each iteration.
Definition at line 76 of file soildynamics/FemModule.h.
Member Data Documentation
beta
Real FemModuleSoildynamics::beta private
Definition at line 88 of file soildynamics/FemModule.h.
c0
Real FemModuleSoildynamics::c0 private
Definition at line 101 of file soildynamics/FemModule.h.
c1
Real FemModuleSoildynamics::c1 private
Definition at line 102 of file soildynamics/FemModule.h.
c2
Real FemModuleSoildynamics::c2 private
Definition at line 103 of file soildynamics/FemModule.h.
c3
Real FemModuleSoildynamics::c3 private
Definition at line 104 of file soildynamics/FemModule.h.
c4
Real FemModuleSoildynamics::c4 private
Definition at line 105 of file soildynamics/FemModule.h.
c5
Real FemModuleSoildynamics::c5 private
Definition at line 106 of file soildynamics/FemModule.h.
c6
Real FemModuleSoildynamics::c6 private
Definition at line 107 of file soildynamics/FemModule.h.
c7
Real FemModuleSoildynamics::c7 private
Definition at line 108 of file soildynamics/FemModule.h.
c8
Real FemModuleSoildynamics::c8 private
Definition at line 109 of file soildynamics/FemModule.h.
c9
Real FemModuleSoildynamics::c9 private
Definition at line 110 of file soildynamics/FemModule.h.
cp
Real FemModuleSoildynamics::cp private
Definition at line 98 of file soildynamics/FemModule.h.
cs
Real FemModuleSoildynamics::cs private
Definition at line 99 of file soildynamics/FemModule.h.
dt
Real FemModuleSoildynamics::dt private
Definition at line 85 of file soildynamics/FemModule.h.
E
Real FemModuleSoildynamics::E private
Definition at line 93 of file soildynamics/FemModule.h.
f
Real3 FemModuleSoildynamics::f = {0,0,0} private
Definition at line 91 of file soildynamics/FemModule.h.
gamma
Real FemModuleSoildynamics::gamma private
Definition at line 89 of file soildynamics/FemModule.h.
lambda
Real FemModuleSoildynamics::lambda private
Definition at line 97 of file soildynamics/FemModule.h.
m_assemble_linear_system
bool FemModuleSoildynamics::m_assemble_linear_system = true private
Definition at line 115 of file soildynamics/FemModule.h.
m_bsr_format
BSRFormat FemModuleSoildynamics::m_bsr_format private
Definition at line 122 of file soildynamics/FemModule.h.
m_cross_validation
bool FemModuleSoildynamics::m_cross_validation = false private
Definition at line 117 of file soildynamics/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleSoildynamics::m_dofs_on_nodes private
Definition at line 121 of file soildynamics/FemModule.h.
m_double_couple_case_table_list
UniqueArray<CaseTableInfo> FemModuleSoildynamics::m_double_couple_case_table_list private
Definition at line 126 of file soildynamics/FemModule.h.
m_hex_quad_mesh
bool FemModuleSoildynamics::m_hex_quad_mesh = false private
Definition at line 118 of file soildynamics/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleSoildynamics::m_linear_system private
Definition at line 120 of file soildynamics/FemModule.h.
m_matrix_format
String FemModuleSoildynamics::m_matrix_format = "DOK" private
Definition at line 113 of file soildynamics/FemModule.h.
m_petsc_flags
String FemModuleSoildynamics::m_petsc_flags private
Definition at line 112 of file soildynamics/FemModule.h.
m_solve_linear_system
bool FemModuleSoildynamics::m_solve_linear_system = true private
Definition at line 116 of file soildynamics/FemModule.h.
m_traction_case_table_list
UniqueArray<CaseTableInfo> FemModuleSoildynamics::m_traction_case_table_list private
Definition at line 125 of file soildynamics/FemModule.h.
mu
Real FemModuleSoildynamics::mu private
Definition at line 96 of file soildynamics/FemModule.h.
nu
Real FemModuleSoildynamics::nu private
Definition at line 94 of file soildynamics/FemModule.h.
rho
Real FemModuleSoildynamics::rho private
Definition at line 95 of file soildynamics/FemModule.h.
t
Real FemModuleSoildynamics::t private
Definition at line 84 of file soildynamics/FemModule.h.
tmax
Real FemModuleSoildynamics::tmax private
Definition at line 86 of file soildynamics/FemModule.h.
The documentation for this class was generated from the following files:
soildynamics/FemModule.h
soildynamics/Dirichlet.h
DoubleCouple.h
soildynamics/ElementMatrix.h
soildynamics/ElementMatrixHexQuad.h
soildynamics/FemModule.cc
Paraxial.h
soildynamics/SourceTerm.h
soildynamics/Traction.h