ArcaneFem: ArcaneFemFunctions::FemShapeMethods Class Reference
ArcaneFemFunctions::FemShapeMethods Class Reference
Provides methods for various FEM-related operations.
#include <femutils/ArcaneFemFunctions.h>
Static Public Member Functions
static Real line2ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference linear (P1) edge finite-element The "Line2" reference element is assumed as follows: 0 1 o--------—o—> x -1 1 direct local numbering : 0->1.
static Real3 line2ShapeFuncDeriv (Integer inod, Real3)
static Real line3ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference quadratic (P2) edge finite-element The "Line3" reference element is assumed as follows: 0 2 1 o--—o---—o—> x -1 0 1 direct local numbering : 0->1->2.
static Real3 line3ShapeFuncDeriv (Integer inod, Real3 ref_coord)
static Real tri3ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference linear (P1) triangle finite-element The "Tri3" reference element is assumed as follows:
static Real3 tri3ShapeFuncDeriv (Integer inod, Real3)
static Real tri6ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference quadratic (P2) triangle finite-element The "Tri6" reference element is assumed as follows: ^ s | 2 (1,0) o . . . . . . o 6 o 5(0.5;0.5) .(0;0.5) . . . . . o----—o----—o------—> r 0(0,0) 4(0.5;0) 1(1,0) direct local numbering : 0->1->2->3->4->5.
static Real3 tri6ShapeFuncDeriv (Integer inod, Real3 ref_coord)
static Real quad4ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference linear (P1) quadrangle finite-element The "Quad4" reference element is assumed as follows: ^y | 1 o--—1--—o 0.
static Real3 quad4ShapeFuncDeriv (Integer inod, Real3 ref_coord)
static Real quad8ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference quadratic (P2) quadrangle finite-element The "Quad8" reference element is assumed as follows: ^y | 4 1 o--—o--—o 0.
static Real3 quad8ShapeFuncDeriv (Integer inod, Real3 ref_coord)
static Real hexa8ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference linear (P1) hexaedron finite-element The "Hexa8" reference element is assumed as follows: (-1, 1,1) 1----------—0 (1,1,1) /| /| / | / | / | / | 2-—|------—3 | z y (-1,-1,1) | | | / | | | | |/—>x | | | | | | | | | 5------—|—4 (1,1,-1) | / | / | / | / |/ |/ 6-----------—7 (1,-1,-1) (-1,-1,-1) Normalized coordinates (x, y, z) vary between -1/+1 direct local numbering : 0->1->2->3->4->5->6->7.
static Real3 hexa8ShapeFuncDeriv (Integer inod, Real3 ref_coord)
static Real hexa20ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference quadratic (P2) hexaedron finite-element The "Hexa20" reference element is assumed as follows: (-1, 1,1) 1---—8---—0 (1,1,1) /| /| 9 | 11 | / | / | 2-—|–10--—3 | z y (-1,-1,1) | | | / | 16 | 19 |/—>x | | | | 17 | 18 | | 5-—12—|—4 (1,1,-1) | / | / | 13 | 15 |/ |/ 6--—14----—7 (1,-1,-1) (-1,-1,-1) Normalized coordinates (x, y, z) vary between -1/+1 direct local numbering : 0->1->2->3->...->18->19.
static Real3 hexa20ShapeFuncDeriv (Integer inod, Real3 ref_coord)
static Real tetra4ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference linear (P1) tetrahedral finite-element The "Tetra4" reference element is assumed as follows:
static Real3 tetra4ShapeFuncDeriv (Integer inod, Real3)
static Real tetra10ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference quadratic (P2) tetrahedral finite-element The "Tetra10" reference element is assumed as follows:
static Real3 tetra10ShapeFuncDeriv (Integer inod, Real3 ref_coord)
static Real penta6ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference linear (P1) pentaedron finite-element The "Penta6" reference element is assumed as follows:
static Real3 penta6ShapeFuncDeriv (Integer inod, Real3 ref_coord)
static Real pyramid5ShapeFuncVal (Integer inod, Real3 ref_coord)
Provides methods for reference linear (P1) pyramid finite-element The "Pyramid5" reference element is assumed as follows:
static Real3 pyramid5ShapeFuncDeriv (Integer inod, Real3 ref_coord)
Detailed Description
Provides methods for various FEM-related operations.
This class includes static methods for computing shape functions and their derivatives depending on finite element types. These methods are used within the Dispatcher mechanism available in Arcane through the class CellFEMDispatcher (coming from PASSMO).
Definition at line 2971 of file ArcaneFemFunctions.h.
Member Function Documentation
hexa20ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::hexa20ShapeFuncDeriv (Integer inod, Real3 ref_coord) inline static
Definition at line 3577 of file ArcaneFemFunctions.h.
hexa20ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::hexa20ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference quadratic (P2) hexaedron finite-element The "Hexa20" reference element is assumed as follows: (-1, 1,1) 1---—8---—0 (1,1,1) /| /| 9 | 11 | / | / | 2-—|–10--—3 | z y (-1,-1,1) | | | / | 16 | 19 |/—>x | | | | 17 | 18 | | 5-—12—|—4 (1,1,-1) | / | / | 13 | 15 |/ |/ 6--—14----—7 (1,-1,-1) (-1,-1,-1) Normalized coordinates (x, y, z) vary between -1/+1 direct local numbering : 0->1->2->3->...->18->19.
Definition at line 3481 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
hexa8ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::hexa8ShapeFuncDeriv (Integer inod, Real3 ref_coord) inline static
Definition at line 3422 of file ArcaneFemFunctions.h.
hexa8ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::hexa8ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference linear (P1) hexaedron finite-element The "Hexa8" reference element is assumed as follows: (-1, 1,1) 1----------—0 (1,1,1) /| /| / | / | / | / | 2-—|------—3 | z y (-1,-1,1) | | | / | | | | |/—>x | | | | | | | | | 5------—|—4 (1,1,-1) | / | / | / | / |/ |/ 6-----------—7 (1,-1,-1) (-1,-1,-1) Normalized coordinates (x, y, z) vary between -1/+1 direct local numbering : 0->1->2->3->4->5->6->7.
Definition at line 3388 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
line2ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::line2ShapeFuncDeriv (Integer inod, Real3) inline static
Definition at line 2997 of file ArcaneFemFunctions.h.
line2ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::line2ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference linear (P1) edge finite-element The "Line2" reference element is assumed as follows: 0 1 o--------—o—> x -1 1 direct local numbering : 0->1.
Definition at line 2985 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
line3ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::line3ShapeFuncDeriv (Integer inod, Real3 ref_coord) inline static
Definition at line 3029 of file ArcaneFemFunctions.h.
line3ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::line3ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference quadratic (P2) edge finite-element The "Line3" reference element is assumed as follows: 0 2 1 o--—o---—o—> x -1 0 1 direct local numbering : 0->1->2.
Definition at line 3014 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
penta6ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::penta6ShapeFuncDeriv (Integer inod, Real3 ref_coord) inline static
Definition at line 3900 of file ArcaneFemFunctions.h.
penta6ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::penta6ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference linear (P1) pentaedron finite-element The "Penta6" reference element is assumed as follows:
                5 (0,1,1)
              . |  .
             .  |     .
            .   Z        .
           .    |           .
          .     |             .
  (0,0,1) 3 ------------------ 4 (1,0,1)
          |     |              |
          |     |              |
          |     |              |
          |     |              |
          |     2 (0,1,-1)     |
          |   .    .           |
          |  Y        .        |
          | .            .     |
          |.                .  |
 (0,0,-1) 0 -------- X ------- 1 (1,0,-1)
direct local numbering : 0->1->2->3->4->5->6
Definition at line 3869 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
pyramid5ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::pyramid5ShapeFuncDeriv (Integer inod, Real3 ref_coord) inline static
Definition at line 4012 of file ArcaneFemFunctions.h.
pyramid5ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::pyramid5ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference linear (P1) pyramid finite-element The "Pyramid5" reference element is assumed as follows:
                          ^
                          |
                          Z
                          |
                          4 (0,0,1)
                         *
                        * **
                       ** *  *
                      * * |*   *
                     * *  | *    *
                    * *   |  *     *
                   * *    |   *      *      .Y
                  * *     |    *       *  .
       (-1,0,0)  * 2 -----|-----*------ 1 (0,1,0)
                * .       |      *  .  .
               * .        |     . *   .
              *.             .     * .
             *                  X . *
   (0,-1,0) 3 --------------------- 0 (1,0,0)
direct local numbering : 0->1->2->3->4
Definition at line 3972 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
quad4ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::quad4ShapeFuncDeriv (Integer inod, Real3 ref_coord) inline static
Definition at line 3203 of file ArcaneFemFunctions.h.
quad4ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::quad4ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference linear (P1) quadrangle finite-element The "Quad4" reference element is assumed as follows: ^y | 1 o--—1--—o 0.
-1 -— -— 1 —> x
2 o— -1 -—o 3
direct local numbering : 0->1->2->3
Definition at line 3177 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
quad8ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::quad8ShapeFuncDeriv (Integer inod, Real3 ref_coord) inline static
Definition at line 3306 of file ArcaneFemFunctions.h.
quad8ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::quad8ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference quadratic (P2) quadrangle finite-element The "Quad8" reference element is assumed as follows: ^y | 4 1 o--—o--—o 0.
5 o -— -— o 7 —> x
2 o--—o--—o 3 6 Normalized coordinates (x, y) vary between -1/+1 Nodes 4, 6 are on line (x = 0) direct local numbering : 0->1->2->...->5->6->7
Definition at line 3251 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
tetra10ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::tetra10ShapeFuncDeriv (Integer inod, Real3 ref_coord) inline static
Definition at line 3803 of file ArcaneFemFunctions.h.
tetra10ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::tetra10ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference quadratic (P2) tetrahedral finite-element The "Tetra10" reference element is assumed as follows:
(0,0,1) x 3 . *.* . * . * . * . * . * 9 * Z (0,1,0) * . * . . * x 8 . . 7 . 2 . * . Y * 6 5 * . . * . . * .. (1,0,0) *. . * -----—X---—> 0 x ******* 4 ******** x 1
direct local numbering : 0->1->2->3->...->8->9
Definition at line 3752 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
tetra4ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::tetra4ShapeFuncDeriv (Integer inod, Real3) inline static
Definition at line 3718 of file ArcaneFemFunctions.h.
tetra4ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::tetra4ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference linear (P1) tetrahedral finite-element The "Tetra4" reference element is assumed as follows:
(0,0,1) 3 . *.* . * . * . * . * . * . * Z (0,1,0) * . * . . * 2 * . . * . . * . Y * . . * . . * . . * .. (1,0,0) *. . * -----—X---—> 0********************1
direct local numbering : 0->1->2->3
Definition at line 3697 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
tri3ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::tri3ShapeFuncDeriv (Integer inod, Real3) inline static
Definition at line 3073 of file ArcaneFemFunctions.h.
tri3ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::tri3ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference linear (P1) triangle finite-element The "Tri3" reference element is assumed as follows:
^ s | 2 (1,0) o . . . . . . . . . . . . o----------—o------—> r 0 (0,0) 1 (1,0) direct local numbering : 0->1->2
Definition at line 3059 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
tri6ShapeFuncDeriv()
static Real3 ArcaneFemFunctions::FemShapeMethods::tri6ShapeFuncDeriv (Integer inod, Real3 ref_coord) inline static
Definition at line 3137 of file ArcaneFemFunctions.h.
tri6ShapeFuncVal()
static Real ArcaneFemFunctions::FemShapeMethods::tri6ShapeFuncVal (Integer inod, Real3 ref_coord) inline static
Provides methods for reference quadratic (P2) triangle finite-element The "Tri6" reference element is assumed as follows: ^ s | 2 (1,0) o . . . . . . o 6 o 5(0.5;0.5) .(0;0.5) . . . . . o----—o----—o------—> r 0(0,0) 4(0.5;0) 1(1,0) direct local numbering : 0->1->2->3->4->5.
Definition at line 3102 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::CellFEMDispatcher().
The documentation for this class was generated from the following file:
ArcaneFemFunctions.h