ArcaneFem: NLDynamicModule Class Reference
NLDynamicModule Class Reference
Class to define the seismic inputmotion features.
#include <modules/passmonl/NLDynamicModule.h>
Classes
struct CaseTableInfo
Public Member Functions
NLDynamicModule (const ModuleBuildInfo &mbi)
void startInit () override
Method called at the beginning of the simulation.
void compute () override
Method called at each step.
VersionInfo versionInfo () const override
Private Member Functions
void _initDofs ()
void _startInitGauss ()
void _initGaussStep ()
void _initCells ()
void _applyInitialNodeConditions ()
void _applyInitialCellConditions ()
void _assembleLinearLHS ()
void _assembleLinearRHS ()
void _assembleNonLinRHS (bool init)
void _doSolve ()
void _initBoundaryConditions ()
void _initDCConditions ()
void _applyDirichletBoundaryConditions ()
void _applyParaxialBoundaryConditions ()
void _applyNeumannBoundaryConditions ()
void _getParaxialContribution (VariableDoFReal &rhs_values)
void _assembleLHSParaxialContribution ()
void _getTractionContribution (Arcane::VariableDoFReal &rhs_values)
Real3x3 _computeJacobian (const ItemWithNodes &cell, const Int32 &ig, const RealUniqueArray &vec, Real &jac)
void _predictNewmark ()
void _updateNewmark ()
void _checkResultFile ()
void _computeK (const Real &lambda, const Real &mu, const DoFLocalId &igauss, const Int32 &nb_nodes, RealUniqueArray2 &Ke)
void _computeElemMass (const Real &rho, const DoFLocalId &igauss, const Int32 &nb_nodes, RealUniqueArray2 &Me)
void _computeKParax (const Face &face, const Int32 &ig, const RealUniqueArray &vec, const Real &jacobian, RealUniqueArray2 &Ke, const Real3 &RhoC)
void _iterate ()
void _check_convergence (Int32 iter)
RealUniqueArray2 _getB (const DoFLocalId &igauss, const Int32 &nb_nodes)
Compute Elementary Derivation Matrix B at current Gauss point of a given cell with nb_nodes.
void _compute_stress (bool init, bool store)
void _stress_prediction (bool init)
void _stress_correction ()
Private Attributes
DoFLinearSystem m_linear_system
FemDoFsOnNodes m_dofs_on_nodes
GaussDoFsOnCells m_gauss_on_cells
UniqueArray< CaseTableInfo > m_traction_case_table_list
UniqueArray< CaseTableInfo > m_sacc_case_table_list
UniqueArray< CaseTableInfo > m_sdispl_case_table_list
UniqueArray< CaseTableInfo > m_svel_case_table_list
UniqueArray< CaseTableInfo > m_sforce_case_table_list
UniqueArray< CaseTableInfo > m_acc_case_table_list
UniqueArray< CaseTableInfo > m_displ_case_table_list
UniqueArray< CaseTableInfo > m_vel_case_table_list
UniqueArray< CaseTableInfo > m_force_case_table_list
UniqueArray< CaseTableInfo > m_ain_case_table_list
UniqueArray< CaseTableInfo > m_vin_case_table_list
UniqueArray< CaseTableInfo > m_uin_case_table_list
UniqueArray< CaseTableInfo > m_dc_case_table_list
Integer ninteg {2}
Int32 NDIM {2}
ArcaneFemFunctions::CellFEMDispatcher cell_fem {}
Real3 gravity {0.,0.,0.}
Real penalty {1.e64}
Real gamma {0.5}
Real beta {0.25}
Real alfam {0.}
Real alfaf {0.}
Real utol {0.001}
Real ftol {0.01}
Real etol {0.}
Real m_norm_R0 {0.}
bool is_alfa_method {false}
bool keep_constop {false}
bool is_linear {true}
bool m_converge {false}
bool m_law_stop { false}
bool m_ref {false}
bool m_deseq {false}
Integer m_nb_law_param {2}
Integer m_nb_law_hist_param {1}
String m_law_param_file {}
Real dt2 {0.}
Int32 linop_nstep {1000}
Int32 linop_nstep_counter {0}
Int32 ite_max {15}
TypesNLDynamic::eElastType elast_type {TypesNLDynamic::NoElastPropType}
TypesNLDynamic::eAnalysisType analysis_type {TypesNLDynamic::PlaneStrain}
TypesNLDynamic::eIntegType integ_type {TypesNLDynamic::FemCell}
TypesNLDynamic::eAlgoType algo_type {TypesNLDynamic::ModNewtonRaphson}
AnalyticFunc m_inputfunc {}
Detailed Description
Class to define the seismic inputmotion features.
Module NLDynamic.
Definition at line 59 of file NLDynamicModule.h.
Constructor & Destructor Documentation
NLDynamicModule()
NLDynamicModule::NLDynamicModule (const ModuleBuildInfo & mbi) explicit
Definition at line 35 of file NLDynamicModule.cc.
~NLDynamicModule()
NLDynamicModule::~NLDynamicModule ()
Definition at line 49 of file NLDynamicModule.cc.
Member Function Documentation
_applyDirichletBoundaryConditions()
void NLDynamicModule::_applyDirichletBoundaryConditions () private
Definition at line 1173 of file NLDynamicModule.cc.
_applyInitialCellConditions()
void NLDynamicModule::_applyInitialCellConditions () private
Definition at line 447 of file NLDynamicModule.cc.
_applyInitialNodeConditions()
void NLDynamicModule::_applyInitialNodeConditions () private
Definition at line 418 of file NLDynamicModule.cc.
_applyNeumannBoundaryConditions()
void NLDynamicModule::_applyNeumannBoundaryConditions () private
Definition at line 1467 of file NLDynamicModule.cc.
_applyParaxialBoundaryConditions()
void NLDynamicModule::_applyParaxialBoundaryConditions () private
Definition at line 1507 of file NLDynamicModule.cc.
_assembleLHSParaxialContribution()
void NLDynamicModule::_assembleLHSParaxialContribution () private
Definition at line 3156 of file NLDynamicModule.cc.
_assembleLinearLHS()
void NLDynamicModule::_assembleLinearLHS () private
Definition at line 1987 of file NLDynamicModule.cc.
_assembleLinearRHS()
void NLDynamicModule::_assembleLinearRHS () private
Definition at line 2078 of file NLDynamicModule.cc.
_assembleNonLinRHS()
void NLDynamicModule::_assembleNonLinRHS (bool init) private
Definition at line 2590 of file NLDynamicModule.cc.
_check_convergence()
void NLDynamicModule::_check_convergence (Int32 iter) private
Definition at line 2976 of file NLDynamicModule.cc.
_checkResultFile()
void NLDynamicModule::_checkResultFile () private
Definition at line 756 of file NLDynamicModule.cc.
_compute_stress()
void NLDynamicModule::_compute_stress (bool init, bool store) private
Definition at line 2449 of file NLDynamicModule.cc.
_computeElemMass()
void NLDynamicModule::_computeElemMass (const Real & rho, const DoFLocalId & igauss, const Int32 & nb_nodes, RealUniqueArray2 & Me) private
Definition at line 1662 of file NLDynamicModule.cc.
_computeJacobian()
Real3x3 NLDynamicModule::_computeJacobian (const ItemWithNodes & cell, const Int32 & ig, const RealUniqueArray & vec, Real & jac) private
Definition at line 1620 of file NLDynamicModule.cc.
_computeK()
void NLDynamicModule::_computeK (const Real & lambda, const Real & mu, const DoFLocalId & igauss, const Int32 & nb_nodes, RealUniqueArray2 & Ke) private
Definition at line 1699 of file NLDynamicModule.cc.
_computeKParax()
void NLDynamicModule::_computeKParax (const Face & face, const Int32 & ig, const RealUniqueArray & vec, const Real & jacobian, RealUniqueArray2 & Ke, const Real3 & RhoC) private
Definition at line 1918 of file NLDynamicModule.cc.
_doSolve()
void NLDynamicModule::_doSolve () private
Definition at line 3272 of file NLDynamicModule.cc.
_getB()
RealUniqueArray2 NLDynamicModule::_getB (const DoFLocalId & igauss, const Int32 & nb_nodes) private
Compute Elementary Derivation Matrix B at current Gauss point of a given cell with nb_nodes.
Definition at line 2394 of file NLDynamicModule.cc.
_getParaxialContribution()
void NLDynamicModule::_getParaxialContribution (VariableDoFReal & rhs_values) private
Definition at line 3037 of file NLDynamicModule.cc.
_getTractionContribution()
void NLDynamicModule::_getTractionContribution (Arcane::VariableDoFReal & rhs_values) private
Definition at line 3238 of file NLDynamicModule.cc.
_initBoundaryConditions()
void NLDynamicModule::_initBoundaryConditions () private
Definition at line 868 of file NLDynamicModule.cc.
_initCells()
void NLDynamicModule::_initCells () private
Definition at line 371 of file NLDynamicModule.cc.
_initDCConditions()
void NLDynamicModule::_initDCConditions () private
Definition at line 1136 of file NLDynamicModule.cc.
_initDofs()
void NLDynamicModule::_initDofs () private
Definition at line 199 of file NLDynamicModule.cc.
_initGaussStep()
void NLDynamicModule::_initGaussStep () private
Definition at line 554 of file NLDynamicModule.cc.
_iterate()
void NLDynamicModule::_iterate () private
Definition at line 622 of file NLDynamicModule.cc.
_predictNewmark()
void NLDynamicModule::_predictNewmark () private
Definition at line 769 of file NLDynamicModule.cc.
_startInitGauss()
void NLDynamicModule::_startInitGauss () private
Definition at line 206 of file NLDynamicModule.cc.
_stress_correction()
void NLDynamicModule::_stress_correction () private
Definition at line 2581 of file NLDynamicModule.cc.
_stress_prediction()
void NLDynamicModule::_stress_prediction (bool init) private
Definition at line 2571 of file NLDynamicModule.cc.
_updateNewmark()
void NLDynamicModule::_updateNewmark () private
Definition at line 827 of file NLDynamicModule.cc.
compute()
void NLDynamicModule::compute () override
Method called at each step.
Definition at line 656 of file NLDynamicModule.cc.
References Arcane::FemUtils::DoFLinearSystem::clearValues(), Arcane::FemUtils::DoFLinearSystem::isInitialized(), TypesNLDynamic::ModNewtonRaphson, Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void NLDynamicModule::startInit () override
Method called at the beginning of the simulation.
Definition at line 81 of file NLDynamicModule.cc.
References TypesNLDynamic::Lame, TypesNLDynamic::Linear, Arcane::FemUtils::DoFLinearSystem::reset(), Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory(), TypesNLDynamic::ThreeD, TypesNLDynamic::Veloc, and TypesNLDynamic::YoungNu.
versionInfo()
VersionInfo NLDynamicModule::versionInfo () const override
Definition at line 45 of file NLDynamicModule.cc.
Member Data Documentation
alfaf
Real NLDynamicModule::alfaf {0.} private
Definition at line 120 of file NLDynamicModule.h.
alfam
Real NLDynamicModule::alfam {0.} private
Definition at line 119 of file NLDynamicModule.h.
algo_type
TypesNLDynamic::eAlgoType NLDynamicModule::algo_type {TypesNLDynamic::ModNewtonRaphson} private
Definition at line 140 of file NLDynamicModule.h.
analysis_type
TypesNLDynamic::eAnalysisType NLDynamicModule::analysis_type {TypesNLDynamic::PlaneStrain} private
Definition at line 138 of file NLDynamicModule.h.
beta
Real NLDynamicModule::beta {0.25} private
Definition at line 118 of file NLDynamicModule.h.
cell_fem
ArcaneFemFunctions::CellFEMDispatcher NLDynamicModule::cell_fem {} private
Definition at line 114 of file NLDynamicModule.h.
dt2
Real NLDynamicModule::dt2 {0.} private
Definition at line 135 of file NLDynamicModule.h.
elast_type
TypesNLDynamic::eElastType NLDynamicModule::elast_type {TypesNLDynamic::NoElastPropType} private
Definition at line 137 of file NLDynamicModule.h.
etol
Real NLDynamicModule::etol {0.} private
Definition at line 121 of file NLDynamicModule.h.
ftol
Real NLDynamicModule::ftol {0.01} private
Definition at line 121 of file NLDynamicModule.h.
gamma
Real NLDynamicModule::gamma {0.5} private
Definition at line 117 of file NLDynamicModule.h.
gravity
Real3 NLDynamicModule::gravity {0.,0.,0.} private
Definition at line 115 of file NLDynamicModule.h.
integ_type
TypesNLDynamic::eIntegType NLDynamicModule::integ_type {TypesNLDynamic::FemCell} private
Definition at line 139 of file NLDynamicModule.h.
is_alfa_method
bool NLDynamicModule::is_alfa_method {false} private
Definition at line 124 of file NLDynamicModule.h.
is_linear
bool NLDynamicModule::is_linear {true} private
Definition at line 126 of file NLDynamicModule.h.
ite_max
Int32 NLDynamicModule::ite_max {15} private
Definition at line 136 of file NLDynamicModule.h.
keep_constop
bool NLDynamicModule::keep_constop {false} private
Definition at line 125 of file NLDynamicModule.h.
linop_nstep
Int32 NLDynamicModule::linop_nstep {1000} private
Definition at line 136 of file NLDynamicModule.h.
linop_nstep_counter
Int32 NLDynamicModule::linop_nstep_counter {0} private
Definition at line 136 of file NLDynamicModule.h.
m_acc_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_acc_case_table_list private
Definition at line 99 of file NLDynamicModule.h.
m_ain_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_ain_case_table_list private
Definition at line 105 of file NLDynamicModule.h.
m_converge
bool NLDynamicModule::m_converge {false} private
Definition at line 127 of file NLDynamicModule.h.
m_dc_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_dc_case_table_list private
Definition at line 110 of file NLDynamicModule.h.
m_deseq
bool NLDynamicModule::m_deseq {false} private
Definition at line 130 of file NLDynamicModule.h.
m_displ_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_displ_case_table_list private
Definition at line 100 of file NLDynamicModule.h.
m_dofs_on_nodes
FemDoFsOnNodes NLDynamicModule::m_dofs_on_nodes private
Definition at line 78 of file NLDynamicModule.h.
m_force_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_force_case_table_list private
Definition at line 102 of file NLDynamicModule.h.
m_gauss_on_cells
GaussDoFsOnCells NLDynamicModule::m_gauss_on_cells private
Definition at line 79 of file NLDynamicModule.h.
m_inputfunc
AnalyticFunc NLDynamicModule::m_inputfunc {} private
Definition at line 141 of file NLDynamicModule.h.
m_law_param_file
String NLDynamicModule::m_law_param_file {} private
Definition at line 133 of file NLDynamicModule.h.
m_law_stop
bool NLDynamicModule::m_law_stop { false} private
Definition at line 128 of file NLDynamicModule.h.
m_linear_system
DoFLinearSystem NLDynamicModule::m_linear_system private
Definition at line 77 of file NLDynamicModule.h.
m_nb_law_hist_param
Integer NLDynamicModule::m_nb_law_hist_param {1} private
Definition at line 132 of file NLDynamicModule.h.
m_nb_law_param
Integer NLDynamicModule::m_nb_law_param {2} private
Definition at line 131 of file NLDynamicModule.h.
m_norm_R0
Real NLDynamicModule::m_norm_R0 {0.} private
Definition at line 122 of file NLDynamicModule.h.
m_ref
bool NLDynamicModule::m_ref {false} private
Definition at line 129 of file NLDynamicModule.h.
m_sacc_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_sacc_case_table_list private
Definition at line 93 of file NLDynamicModule.h.
m_sdispl_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_sdispl_case_table_list private
Definition at line 94 of file NLDynamicModule.h.
m_sforce_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_sforce_case_table_list private
Definition at line 96 of file NLDynamicModule.h.
m_svel_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_svel_case_table_list private
Definition at line 95 of file NLDynamicModule.h.
m_traction_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_traction_case_table_list private
Definition at line 90 of file NLDynamicModule.h.
m_uin_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_uin_case_table_list private
Definition at line 107 of file NLDynamicModule.h.
m_vel_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_vel_case_table_list private
Definition at line 101 of file NLDynamicModule.h.
m_vin_case_table_list
UniqueArray<CaseTableInfo> NLDynamicModule::m_vin_case_table_list private
Definition at line 106 of file NLDynamicModule.h.
NDIM
Int32 NLDynamicModule::NDIM {2} private
Definition at line 113 of file NLDynamicModule.h.
ninteg
Integer NLDynamicModule::ninteg {2} private
Definition at line 112 of file NLDynamicModule.h.
penalty
Real NLDynamicModule::penalty {1.e64} private
Definition at line 116 of file NLDynamicModule.h.
utol
Real NLDynamicModule::utol {0.001} private
Definition at line 121 of file NLDynamicModule.h.
The documentation for this class was generated from the following files:
NLDynamicModule.h
NLDynamicModule.cc