ArcaneFem: FemModuleLaplace Class Reference
FemModuleLaplace Class Reference
A module for finite element method.
#include <modules/laplace/FemModule.h>
Public Member Functions
FemModuleLaplace (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleLaplace at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
void _assembleBilinearOperator ()
Calls the right function for LHS assembly.
void _assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
Private Member Functions
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _solve ()
Solves the linear system and updates the solution vector.
void _assembleLinearOperator ()
Assembles the FEM linear operator for the current simulation step.
void _assembleLinearOperatorCpu ()
FEM linear operator for the current simulation step.
void _updateVariables ()
Update the FEM variables.
void _validateResults ()
Validates and prints the results of the FEM computation.
RealMatrix< 3, 3 > _computeElementMatrixTria3 (Cell cell)
Computes the element matrix for a triangular element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixTetra4 (Cell cell)
Computes the element matrix for a tetrahedral element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixQuad4 (Cell cell)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
RealMatrix< 8, 8 > _computeElementMatrixHexa8 (Cell cell)
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
template<int N>
void _assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the bilinear operator matrix for the FEM linear system.
Private Attributes
DoFLinearSystem m_linear_system
IItemFamily * m_dof_family = nullptr
FemDoFsOnNodes m_dofs_on_nodes
BSRFormat m_bsr_format
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_hex_quad_mesh = false
Detailed Description
A module for finite element method.
This class handles the initialization and computation for finite element method (FEM) simulations, providing methods to set up and solve linear systems, assemble FEM operators, and perform result checks.
Definition at line 60 of file laplace/FemModule.h.
Constructor & Destructor Documentation
FemModuleLaplace()
FemModuleLaplace::FemModuleLaplace (const ModuleBuildInfo & mbi) inline explicit
Definition at line 65 of file laplace/FemModule.h.
Member Function Documentation
_assembleBilinear()
template<int N> void FemModuleLaplace::_assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the bilinear operator matrix for the FEM linear system.
The method performs the following steps:
Computes element matrix using provided compute_element_matrix function.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 314 of file laplace/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleBilinearOperator()
void FemModuleLaplace::_assembleBilinearOperator ()
Calls the right function for LHS assembly.
Definition at line 259 of file laplace/FemModule.cc.
References _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), _computeElementMatrixTria3(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_assembleLinearOperator()
void FemModuleLaplace::_assembleLinearOperator () private
Assembles the FEM linear operator for the current simulation step.
This method constructs the right-hand side (RHS) vector by calling then appropriate assembly function based on the execution context:
CPU-exclusive execution: Calls _assembleLinearOperatorCpu().
CPU or GPU execution: Calls _assembleLinearOperatorGpu().
Definition at line 133 of file laplace/FemModule.cc.
References _assembleLinearOperatorCpu(), and _assembleLinearOperatorGpu().
Referenced by _doStationarySolve().
_assembleLinearOperatorCpu()
void FemModuleLaplace::_assembleLinearOperatorCpu () private
FEM linear operator for the current simulation step.
This method constructs the FEM linear systems RHS vector by applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC/Point are specified apply to the LHS & RHS.
Definition at line 156 of file laplace/FemModule.cc.
References ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _assembleLinearOperator().
_assembleLinearOperatorGpu()
void FemModuleLaplace::_assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC/Point are specified apply to the LHS & RHS.
Definition at line 213 of file laplace/FemModule.cc.
References Arcane::FemUtils::Gpu::BoundaryConditions::applyDirichletToLhsAndRhs(), Arcane::FemUtils::Gpu::BoundaryConditions::applyPointDirichletToLhsAndRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _assembleLinearOperator().
_computeElementMatrixHexa8()
RealMatrix< 8, 8 > FemModuleLaplace::_computeElementMatrixHexa8 (Cell cell) private
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Define Gauss points (2x2x2) and weights.
Loop over Gauss points to compute the gradients in physical space (𝑥,𝑦,𝑧) and the determinant of the Jacobian via computeGradientsAndJacobianHexa8.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 86 of file laplace/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixQuad4()
RealMatrix< 4, 4 > FemModuleLaplace::_computeElementMatrixQuad4 (Cell cell) private
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 33 of file laplace/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTetra4()
RealMatrix< 4, 4 > FemModuleLaplace::_computeElementMatrixTetra4 (Cell cell) private
Computes the element matrix for a tetrahedral element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 85 of file laplace/ElementMatrix.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTria3()
RealMatrix< 3, 3 > FemModuleLaplace::_computeElementMatrixTria3 (Cell cell) private
Computes the element matrix for a triangular element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 28 of file laplace/ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
Referenced by _assembleBilinearOperator().
_doStationarySolve()
void FemModuleLaplace::_doStationarySolve () private
Performs a stationary solve for the FEM system.
This method follows via the following steps:
_assembleBilinearOperator() Assembles the FEM matrix 𝐀
_assembleLinearOperator() Assembles the FEM RHS vector 𝐛
_solve() Solves for solution vector 𝐮 = 𝐀⁻¹𝐛
_updateVariables() Updates FEM variables 𝐮 = 𝐱
_validateResults() Regression test
Definition at line 105 of file laplace/FemModule.cc.
References _assembleBilinearOperator(), _assembleLinearOperator(), _solve(), _updateVariables(), and _validateResults().
Referenced by compute().
_solve()
void FemModuleLaplace::_solve () private
Solves the linear system and updates the solution vector.
Definition at line 344 of file laplace/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updateVariables()
void FemModuleLaplace::_updateVariables () private
Update the FEM variables.
This method performs the following actions:
Fetches values of solution from solved linear system to FEM variables, i.e., it copies RHS DOF to u.
Performs synchronize of FEM variables across subdomains.
Definition at line 367 of file laplace/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_validateResults()
void FemModuleLaplace::_validateResults () private
Validates and prints the results of the FEM computation.
This method performs the following actions:
If number of nodes < 200, prints the computed values for each node.
Retrieves the filename for the result file from options.
If a filename is provided, checks the computed results against result file.
Note
The result comparison uses a tolerance of 1.0e-4.
Definition at line 401 of file laplace/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
compute()
void FemModuleLaplace::compute () override
Method called at the beginning of the simulation.
Performs the main computation for the FemModuleLaplace.
This method:
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Executes the stationary solve.
Definition at line 56 of file laplace/FemModule.cc.
References _doStationarySolve(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleLaplace::startInit () override
Initializes the FemModuleLaplace at the start of the simulation.
This method initializes degrees of freedom (DoFs) on nodes.
Definition at line 26 of file laplace/FemModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleLaplace::versionInfo () const inline override
Method called at each iteration.
Definition at line 77 of file laplace/FemModule.h.
Member Data Documentation
m_assemble_linear_system
bool FemModuleLaplace::m_assemble_linear_system = true private
Definition at line 92 of file laplace/FemModule.h.
m_bsr_format
BSRFormat FemModuleLaplace::m_bsr_format private
Definition at line 87 of file laplace/FemModule.h.
m_cross_validation
bool FemModuleLaplace::m_cross_validation = false private
Definition at line 94 of file laplace/FemModule.h.
m_dof_family
IItemFamily* FemModuleLaplace::m_dof_family = nullptr private
Definition at line 85 of file laplace/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleLaplace::m_dofs_on_nodes private
Definition at line 86 of file laplace/FemModule.h.
m_hex_quad_mesh
bool FemModuleLaplace::m_hex_quad_mesh = false private
Definition at line 95 of file laplace/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleLaplace::m_linear_system private
Definition at line 84 of file laplace/FemModule.h.
m_matrix_format
String FemModuleLaplace::m_matrix_format = "DOK" private
Definition at line 90 of file laplace/FemModule.h.
m_petsc_flags
String FemModuleLaplace::m_petsc_flags private
Definition at line 89 of file laplace/FemModule.h.
m_solve_linear_system
bool FemModuleLaplace::m_solve_linear_system = true private
Definition at line 93 of file laplace/FemModule.h.
The documentation for this class was generated from the following files:
laplace/FemModule.h
laplace/ElementMatrix.h
laplace/ElementMatrixHexQuad.h
laplace/FemModule.cc