ArcaneFem: Tensor4 Class Reference
Tensor4 Class Reference
4th-order tensor used for constitutive operators _ _ | D Sup | C = | | with D, S, Sup, Slow = Real3x3 blocks | | | Slow S | |_ _|
#include <modules/passmonl/utilFEM.h>
Public Member Functions
__host__ __device__ Tensor4 (bool constitutive=true, bool sym=true)
__host__ __device__ Tensor4 (const Real3x3 &D, const Real3x3 &S)
__host__ __device__ Tensor4 (const Real3x3 &D, const Real3x3 &S, const Real3x3 &Sup, const Real3x3 &Slow, bool constitutive=true)
__host__ __device__ Tensor4 (Real lambda, Real mu)
__host__ __device__ Tensor4 (const Tensor4 &tens)
__host__ __device__ Real3x3 operator[] (Int32 i) const
__host__ __device__ Real3x3 & operator[] (Int32 i)
__host__ __device__ bool isSymmetric () const
__host__ __device__ void isSymmetric (bool sym)
__host__ __device__ bool isConstitutive () const
__host__ __device__ void isConstitutive (bool b)
__host__ __device__ Tensor4 & operator= (const Tensor4 &tens)
__host__ __device__ Tensor4 operator+ (const Tensor4 &tens) const
Define the addition operator.
__host__ __device__ Tensor4 & operator+= (const Tensor4 &tens)
Define the += operator.
__host__ __device__ Tensor4 operator- (const Tensor4 &tens) const
Define the subtraction operator.
__host__ __device__ Tensor4 & operator-= (const Tensor4 &tens)
Define the -= operator.
__host__ __device__ void multInPlace (Real scalar)
Multiply all the components by v.
__host__ __device__ Tensor4 operator- () const
Define the unary negation operator.
__host__ __device__ void addInPlace (Real scalar)
Add v to all the components.
__host__ __device__ void subInPlace (Real v)
Substract v to all the components.
__host__ __device__ Tensor4 operator* (Real scalar) const
Scalar multiplication: Tensor4 * scalar.
__host__ __device__ Tensor4 & operator*= (Real scalar)
Define the *= operator.
__host__ __device__ Tensor4 operator/ (Real scalar) const
Scalar division: Tensor / scalar.
__host__ __device__ Tensor4 & operator/= (Real scalar)
Define the *= operator.
__host__ __device__ Real trace () const
Define the trace of the Tensor.
__host__ __device__ Real value_at (Int32 i, Int32 j) const
Get the (i,j) value of the Tensor.
__host__ __device__ void value_at (Int32 i, Int32 j, Real x)
Set the (i,j) value of the Tensor.
__host__ __device__ Real value_at (Int32 i, Int32 j, Int32 k, Int32 l)
Get the (i,j,k,l) value of the Tensor4.
__host__ __device__ void value_at (Int32 i, Int32 j, Int32 k, Int32 l, Real x)
Set the (i,j,k,l) value of the Tensor4.
Static Public Member Functions
static Tensor4 identity ()
Return Identity Tensor4.
static Tensor4 zero ()
Return zero Tensor2.
Protected Attributes
Real3x3 m_tab [4]
bool m_constitutive
bool m_sym
Friends
__host__ __device__ friend Tensor4 operator* (Real scalar, const Tensor4 &tens)
Friend function for scalar multiplication: scalar * Tensor4.
Detailed Description
4th-order tensor used for constitutive operators _ _ | D Sup | C = | | with D, S, Sup, Slow = Real3x3 blocks | | | Slow S | |_ _|
example: for elastic Tensor4 _ _ | lambda + 2mu lambda lambda | D = | |
lambda lambda + 2mu lambda
lambda lambda lambda + 2mu
_ _
_ _ | mu 0 0 | S = | | Sup = Slow = 0 (Real3x3)
0 mu 0
0 0 mu
_ _
/*------------------------------------------------------------------------—
Definition at line 54 of file utilFEM.h.
Constructor & Destructor Documentation
Tensor4() [1/5]
__host__ __device__ Tensor4::Tensor4 (bool constitutive = true, bool sym = true) inline explicit
Definition at line 64 of file utilFEM.h.
Tensor4() [2/5]
__host__ __device__ Tensor4::Tensor4 (const Real3x3 & D, const Real3x3 & S) inline
Definition at line 67 of file utilFEM.h.
Tensor4() [3/5]
__host__ __device__ Tensor4::Tensor4 (const Real3x3 & D, const Real3x3 & S, const Real3x3 & Sup, const Real3x3 & Slow, bool constitutive = true) inline
Definition at line 74 of file utilFEM.h.
Tensor4() [4/5]
__host__ __device__ Tensor4::Tensor4 (Real lambda, Real mu) inline
Definition at line 83 of file utilFEM.h.
Tensor4() [5/5]
__host__ __device__ Tensor4::Tensor4 (const Tensor4 & tens) inline
Definition at line 91 of file utilFEM.h.
Member Function Documentation
addInPlace()
__host__ __device__ void Tensor4::addInPlace (Real scalar) inline
Add v to all the components.
Definition at line 179 of file utilFEM.h.
identity()
static Tensor4 Tensor4::identity () inline static
Return Identity Tensor4.
Definition at line 111 of file utilFEM.h.
isConstitutive() [1/2]
__host__ __device__ bool Tensor4::isConstitutive () const inline
Definition at line 124 of file utilFEM.h.
isConstitutive() [2/2]
__host__ __device__ void Tensor4::isConstitutive (bool b) inline
Definition at line 125 of file utilFEM.h.
isSymmetric() [1/2]
__host__ __device__ bool Tensor4::isSymmetric () const inline
Definition at line 121 of file utilFEM.h.
isSymmetric() [2/2]
__host__ __device__ void Tensor4::isSymmetric (bool sym) inline
Definition at line 122 of file utilFEM.h.
multInPlace()
__host__ __device__ void Tensor4::multInPlace (Real scalar) inline
Multiply all the components by v.
Definition at line 165 of file utilFEM.h.
operator*()
__host__ __device__ Tensor4 Tensor4::operator* (Real scalar) const inline
Scalar multiplication: Tensor4 * scalar.
Definition at line 193 of file utilFEM.h.
operator*=()
__host__ __device__ Tensor4 & Tensor4::operator*= (Real scalar) inline
Define the *= operator.
Definition at line 202 of file utilFEM.h.
References operator*.
operator+()
__host__ __device__ Tensor4 Tensor4::operator+ (const Tensor4 & tens) const inline
Define the addition operator.
Definition at line 135 of file utilFEM.h.
operator+=()
__host__ __device__ Tensor4 & Tensor4::operator+= (const Tensor4 & tens) inline
Define the += operator.
Definition at line 144 of file utilFEM.h.
operator-() [1/2]
__host__ __device__ Tensor4 Tensor4::operator- () const inline
Define the unary negation operator.
Definition at line 172 of file utilFEM.h.
operator-() [2/2]
__host__ __device__ Tensor4 Tensor4::operator- (const Tensor4 & tens) const inline
Define the subtraction operator.
Definition at line 150 of file utilFEM.h.
operator-=()
__host__ __device__ Tensor4 & Tensor4::operator-= (const Tensor4 & tens) inline
Define the -= operator.
Definition at line 159 of file utilFEM.h.
operator/()
__host__ __device__ Tensor4 Tensor4::operator/ (Real scalar) const inline
Scalar division: Tensor / scalar.
Definition at line 208 of file utilFEM.h.
Referenced by operator/=().
operator/=()
__host__ __device__ Tensor4 & Tensor4::operator/= (Real scalar) inline
Define the *= operator.
Definition at line 217 of file utilFEM.h.
References operator/().
operator=()
__host__ __device__ Tensor4 & Tensor4::operator= (const Tensor4 & tens) inline
Definition at line 127 of file utilFEM.h.
operator[]() [1/2]
__host__ __device__ Real3x3 & Tensor4::operator[] (Int32 i) inline
Definition at line 105 of file utilFEM.h.
operator[]() [2/2]
__host__ __device__ Real3x3 Tensor4::operator[] (Int32 i) const inline
Definition at line 101 of file utilFEM.h.
subInPlace()
__host__ __device__ void Tensor4::subInPlace (Real v) inline
Substract v to all the components.
Definition at line 186 of file utilFEM.h.
trace()
__host__ __device__ Real Tensor4::trace () const inline
Define the trace of the Tensor.
Definition at line 223 of file utilFEM.h.
value_at() [1/4]
__host__ __device__ Real Tensor4::value_at (Int32 i, Int32 j) const inline
Get the (i,j) value of the Tensor.
Definition at line 228 of file utilFEM.h.
value_at() [2/4]
__host__ __device__ Real Tensor4::value_at (Int32 i, Int32 j, Int32 k, Int32 l) inline
Get the (i,j,k,l) value of the Tensor4.
Definition at line 278 of file utilFEM.h.
value_at() [3/4]
__host__ __device__ void Tensor4::value_at (Int32 i, Int32 j, Int32 k, Int32 l, Real x) inline
Set the (i,j,k,l) value of the Tensor4.
Definition at line 310 of file utilFEM.h.
value_at() [4/4]
__host__ __device__ void Tensor4::value_at (Int32 i, Int32 j, Real x) inline
Set the (i,j) value of the Tensor.
Definition at line 250 of file utilFEM.h.
zero()
static Tensor4 Tensor4::zero () inline static
Return zero Tensor2.
Definition at line 116 of file utilFEM.h.
Friends And Related Symbol Documentation
operator*
__host__ __device__ friend Tensor4 operator* (Real scalar, const Tensor4 & tens) friend
Friend function for scalar multiplication: scalar * Tensor4.
Definition at line 350 of file utilFEM.h.
Referenced by operator*=().
Member Data Documentation
m_constitutive
bool Tensor4::m_constitutive protected
Definition at line 59 of file utilFEM.h.
m_sym
bool Tensor4::m_sym protected
Definition at line 60 of file utilFEM.h.
m_tab
Real3x3 Tensor4::m_tab[4] protected
Definition at line 58 of file utilFEM.h.
The documentation for this class was generated from the following file:
utilFEM.h