ArcaneFem: FemModuleAerodynamics Class Reference
FemModuleAerodynamics Class Reference
A module for finite element method.
#include <modules/aerodynamics/FemModule.h>
Public Member Functions
FemModuleAerodynamics (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleAerodynamics at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
void _assembleBilinearOperator ()
Calls the right function for LHS assembly.
void _assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
Private Member Functions
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _solve ()
void _assembleLinearOperatorCpu ()
FEM linear operator for the current simulation step.
void _assembleLinearOperator ()
Assembles the FEM linear operator for the current simulation step.
void _getPsi ()
void _updateVariables ()
Update the FEM variables.
void _validateResults ()
Validates and prints the results of the FEM computation.
RealMatrix< 3, 3 > _computeElementMatrixTria3 (Cell cell)
Computes the element matrix for a triangular element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixTetra4 (Cell cell)
Computes the element matrix for a tetrahedral element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixQuad4 (Cell cell)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
RealMatrix< 8, 8 > _computeElementMatrixHexa8 (Cell cell)
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
template<int N>
void _assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the bilinear operator matrix for the FEM linear system.
Private Attributes
DoFLinearSystem m_linear_system
IItemFamily * m_dof_family = nullptr
FemDoFsOnNodes m_dofs_on_nodes
BSRFormat m_bsr_format
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_hex_quad_mesh = false
Detailed Description
A module for finite element method.
This class handles the initialization and computation for finite element method (FEM) simulations, providing methods to set up and solve linear systems, assemble FEM operators, and perform result checks.
Definition at line 62 of file aerodynamics/FemModule.h.
Constructor & Destructor Documentation
FemModuleAerodynamics()
FemModuleAerodynamics::FemModuleAerodynamics (const ModuleBuildInfo & mbi) inline explicit
Definition at line 67 of file aerodynamics/FemModule.h.
Member Function Documentation
_assembleBilinear()
template<int N> void FemModuleAerodynamics::_assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the bilinear operator matrix for the FEM linear system.
The method performs the following steps:
Computes element matrix using provided compute_element_matrix function.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 377 of file aerodynamics/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleBilinearOperator()
void FemModuleAerodynamics::_assembleBilinearOperator ()
Calls the right function for LHS assembly.
Definition at line 323 of file aerodynamics/FemModule.cc.
References _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), _computeElementMatrixTria3(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_assembleLinearOperator()
void FemModuleAerodynamics::_assembleLinearOperator () private
Assembles the FEM linear operator for the current simulation step.
This method constructs the right-hand side (RHS) vector by calling then appropriate assembly function based on the execution context:
CPU-exclusive execution: Calls _assembleLinearOperatorCpu().
CPU or GPU execution: Calls _assembleLinearOperatorGpu().
Definition at line 179 of file aerodynamics/FemModule.cc.
References _assembleLinearOperatorCpu(), and _assembleLinearOperatorGpu().
Referenced by _doStationarySolve().
_assembleLinearOperatorCpu()
void FemModuleAerodynamics::_assembleLinearOperatorCpu () private
FEM linear operator for the current simulation step.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
Dirichlet BC/Point are specified apply to the LHS & RHS.
Far-field BC are applied to the LHS & RHS.
Definition at line 202 of file aerodynamics/FemModule.cc.
References ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), Arcane::FemUtils::DoFLinearSystem::matrixSetValue(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _assembleLinearOperator().
_assembleLinearOperatorGpu()
void FemModuleAerodynamics::_assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC/Point are specified apply to the LHS & RHS.
Definition at line 260 of file aerodynamics/FemModule.cc.
References Arcane::FemUtils::Gpu::BoundaryConditions::applyDirichletToLhsAndRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _assembleLinearOperator().
_computeElementMatrixHexa8()
RealMatrix< 8, 8 > FemModuleAerodynamics::_computeElementMatrixHexa8 (Cell cell) private
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Define Gauss points (2x2x2) and weights.
Loop over Gauss points to compute the gradients in physical space (𝑥,𝑦,𝑧) and the determinant of the Jacobian via computeGradientsAndJacobianHexa8.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 86 of file aerodynamics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixQuad4()
RealMatrix< 4, 4 > FemModuleAerodynamics::_computeElementMatrixQuad4 (Cell cell) private
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 33 of file aerodynamics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTetra4()
RealMatrix< 4, 4 > FemModuleAerodynamics::_computeElementMatrixTetra4 (Cell cell) private
Computes the element matrix for a tetrahedral element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Calculate the volume of the tetrahedron.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 73 of file aerodynamics/ElementMatrix.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTria3()
RealMatrix< 3, 3 > FemModuleAerodynamics::_computeElementMatrixTria3 (Cell cell) private
Computes the element matrix for a triangular element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 28 of file aerodynamics/ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
Referenced by _assembleBilinearOperator().
_doStationarySolve()
void FemModuleAerodynamics::_doStationarySolve () private
Performs a stationary solve for the FEM system.
This method follows a sequence of steps to solve FEM system:
_assembleBilinearOperator() Assembles the FEM matrix 𝑨
_assembleLinearOperator() Assembles the FEM RHS vector 𝒃
_solve() Solves for solution vector 𝒖 = 𝑨⁻¹𝒃
_updateVariables() Updates FEM variables 𝒖 = 𝒙
_validateResults() Regression test
Definition at line 151 of file aerodynamics/FemModule.cc.
References _assembleBilinearOperator(), _assembleLinearOperator(), _updateVariables(), and _validateResults().
Referenced by compute().
_getPsi()
void FemModuleAerodynamics::_getPsi () private
Definition at line 98 of file aerodynamics/FemModule.cc.
_solve()
void FemModuleAerodynamics::_solve () private
Definition at line 403 of file aerodynamics/FemModule.cc.
_updateVariables()
void FemModuleAerodynamics::_updateVariables () private
Update the FEM variables.
This method performs the following actions:
Fetches values of solution from solved linear system to FEM variables, i.e., it copies RHS DOF to 𝒖.
Performs synchronize of FEM variables across subdomains.
Definition at line 426 of file aerodynamics/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_validateResults()
void FemModuleAerodynamics::_validateResults () private
Validates and prints the results of the FEM computation.
This method performs the following actions:
If number of nodes < 200, prints the computed values for each node.
Retrieves the filename for the result file from options.
If a filename is provided, checks the computed results against result file.
Note
The result comparison uses a tolerance of 1.0e-4.
Definition at line 459 of file aerodynamics/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
compute()
void FemModuleAerodynamics::compute () override
Method called at the beginning of the simulation.
Performs the main computation for the FemModuleAerodynamics.
This method:
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Applies PETSc commandline flags to the solver (if PETSc is used).
Executes the stationary solve and extracts psi.
Definition at line 69 of file aerodynamics/FemModule.cc.
References _doStationarySolve(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleAerodynamics::startInit () override
Initializes the FemModuleAerodynamics at the start of the simulation.
This method initializes degrees of freedom (DoFs) on nodes.
It also gets values of some solver parameters.
Definition at line 27 of file aerodynamics/FemModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleAerodynamics::versionInfo () const inline override
Method called at each iteration.
Definition at line 79 of file aerodynamics/FemModule.h.
Member Data Documentation
m_assemble_linear_system
bool FemModuleAerodynamics::m_assemble_linear_system = true private
Definition at line 94 of file aerodynamics/FemModule.h.
m_bsr_format
BSRFormat FemModuleAerodynamics::m_bsr_format private
Definition at line 89 of file aerodynamics/FemModule.h.
m_cross_validation
bool FemModuleAerodynamics::m_cross_validation = false private
Definition at line 96 of file aerodynamics/FemModule.h.
m_dof_family
IItemFamily* FemModuleAerodynamics::m_dof_family = nullptr private
Definition at line 87 of file aerodynamics/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleAerodynamics::m_dofs_on_nodes private
Definition at line 88 of file aerodynamics/FemModule.h.
m_hex_quad_mesh
bool FemModuleAerodynamics::m_hex_quad_mesh = false private
Definition at line 97 of file aerodynamics/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleAerodynamics::m_linear_system private
Definition at line 86 of file aerodynamics/FemModule.h.
m_matrix_format
String FemModuleAerodynamics::m_matrix_format = "DOK" private
Definition at line 92 of file aerodynamics/FemModule.h.
m_petsc_flags
String FemModuleAerodynamics::m_petsc_flags private
Definition at line 91 of file aerodynamics/FemModule.h.
m_solve_linear_system
bool FemModuleAerodynamics::m_solve_linear_system = true private
Definition at line 95 of file aerodynamics/FemModule.h.
The documentation for this class was generated from the following files:
aerodynamics/FemModule.h
aerodynamics/ElementMatrix.h
aerodynamics/ElementMatrixHexQuad.h
aerodynamics/FemModule.cc