ArcaneFem: ArcaneFemFunctions::FemGaussQuadrature Class Reference
ArcaneFemFunctions::FemGaussQuadrature Class Reference
Provides methods for Gauss quadrature.
#include <femutils/ArcaneFemFunctions.h>
Static Public Member Functions
static Integer getNbGaussPointsfromOrder (Int16 cell_type, Integer ninteg)
Provides the number of Gauss Points for a given finite element type, depending on the integration order chosen by user (coming fro PASSMO).
static Real3 getGaussRefPosition (ItemWithNodes cell, Integer ninteg, Integer rank)
Provides the position of a Gauss Point in the reference (local) element for a given finite element, depending on the rank of the point in the element loop (coming fro PASSMO).
static Real getGaussWeight (ItemWithNodes cell, Integer ninteg, Integer rank)
Provides the integration weight of a Gauss Point for a given finite element, depending on the rank of the point in the element loop (coming fro PASSMO).
static Real getRefPosition (Integer indx, Integer ordre)
Provides the position of a Gauss Point in the reference (local) element coordinates, depending on the index of the Gauss Point and integration order chosen by user (coming fro PASSMO). This method is generic (not depending on the finite element type) and is called by specialized methods (depending on FE type)
static Real getWeight (Integer indx, Integer ordre)
Provides the integration weight depending on the index of the Gauss Point and integration order chosen by user (coming fro PASSMO). This method is generic (not depending on the finite element type) and is called by specialized methods (depending on FE type)
static Real3 lineRefPosition (Integer3 indices, Integer3 ordre)
Provides the reference coordinates of a Gauss Point for edge elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real3 triRefPosition (Integer3 indices, Integer3 ordre)
Provides the reference coordinates of a Gauss Point for triangle elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real3 quadRefPosition (Integer3 indices, Integer3 ordre)
Provides the reference coordinates of a Gauss Point for quadrangle elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real3 hexaRefPosition (Integer3 indices, Integer3 ordre)
Provides the reference coordinates of a Gauss Point for hexaedron elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real3 tetraRefPosition (Integer3 indices, Integer3)
Provides the reference coordinates of a Gauss Point for tetraedron elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real3 pentaRefPosition (Integer3 indices, Integer3 ordre)
Provides the reference coordinates of a Gauss Point for wedge (pentaedron) elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real lineWeight (Integer3 indices, Integer3 ordre)
Provides the integration weight of a Gauss Point for edge elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real triWeight (Integer3 indices, Integer3 ordre)
Provides the integration weight of a Gauss Point for triangle elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real quadWeight (Integer3 indices, Integer3 ordre)
Provides the integration weight of a Gauss Point for quadrangle elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real hexaWeight (Integer3 indices, Integer3 ordre)
Provides the integration weight of a Gauss Point for hexadron elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real tetraWeight (Integer3, Integer3)
Provides the integration weight of a Gauss Point for tetraedron elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
static Real pentaWeight (Integer3 indices, Integer3 ordre)
Provides the integration weight of a Gauss Point for wedge (pentaedron) elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Detailed Description
Provides methods for Gauss quadrature.
This class includes static methods for computing Gauss-Legendre integration depending on finite element types (coming from PASSMO).
Definition at line 4076 of file ArcaneFemFunctions.h.
Member Function Documentation
getGaussRefPosition()
static Real3 ArcaneFemFunctions::FemGaussQuadrature::getGaussRefPosition (ItemWithNodes cell, Integer ninteg, Integer rank) inline static
Provides the position of a Gauss Point in the reference (local) element for a given finite element, depending on the rank of the point in the element loop (coming fro PASSMO).
Definition at line 4184 of file ArcaneFemFunctions.h.
References hexaRefPosition(), lineRefPosition(), and quadRefPosition().
Referenced by ArcaneFemFunctions::CellFEMDispatcher::getGaussData().
getGaussWeight()
static Real ArcaneFemFunctions::FemGaussQuadrature::getGaussWeight (ItemWithNodes cell, Integer ninteg, Integer rank) inline static
Provides the integration weight of a Gauss Point for a given finite element, depending on the rank of the point in the element loop (coming fro PASSMO).
Definition at line 4264 of file ArcaneFemFunctions.h.
References hexaWeight(), lineWeight(), and quadWeight().
Referenced by ArcaneFemFunctions::CellFEMDispatcher::getGaussData().
getNbGaussPointsfromOrder()
static Integer ArcaneFemFunctions::FemGaussQuadrature::getNbGaussPointsfromOrder (Int16 cell_type, Integer ninteg) inline static
Provides the number of Gauss Points for a given finite element type, depending on the integration order chosen by user (coming fro PASSMO).
Definition at line 4087 of file ArcaneFemFunctions.h.
Referenced by ArcaneFemFunctions::CellFEMDispatcher::getGaussData().
getRefPosition()
static Real ArcaneFemFunctions::FemGaussQuadrature::getRefPosition (Integer indx, Integer ordre) inline static
Provides the position of a Gauss Point in the reference (local) element coordinates, depending on the index of the Gauss Point and integration order chosen by user (coming fro PASSMO). This method is generic (not depending on the finite element type) and is called by specialized methods (depending on FE type)
Definition at line 4355 of file ArcaneFemFunctions.h.
Referenced by hexaRefPosition(), lineRefPosition(), pentaRefPosition(), and quadRefPosition().
getWeight()
static Real ArcaneFemFunctions::FemGaussQuadrature::getWeight (Integer indx, Integer ordre) inline static
Provides the integration weight depending on the index of the Gauss Point and integration order chosen by user (coming fro PASSMO). This method is generic (not depending on the finite element type) and is called by specialized methods (depending on FE type)
Definition at line 4398 of file ArcaneFemFunctions.h.
Referenced by hexaWeight(), lineWeight(), pentaWeight(), and quadWeight().
hexaRefPosition()
static Real3 ArcaneFemFunctions::FemGaussQuadrature::hexaRefPosition (Integer3 indices, Integer3 ordre) inline static
Provides the reference coordinates of a Gauss Point for hexaedron elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4486 of file ArcaneFemFunctions.h.
References getRefPosition().
Referenced by getGaussRefPosition().
hexaWeight()
static Real ArcaneFemFunctions::FemGaussQuadrature::hexaWeight (Integer3 indices, Integer3 ordre) inline static
Provides the integration weight of a Gauss Point for hexadron elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4577 of file ArcaneFemFunctions.h.
References getWeight().
Referenced by getGaussWeight().
lineRefPosition()
static Real3 ArcaneFemFunctions::FemGaussQuadrature::lineRefPosition (Integer3 indices, Integer3 ordre) inline static
Provides the reference coordinates of a Gauss Point for edge elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4442 of file ArcaneFemFunctions.h.
References getRefPosition().
Referenced by getGaussRefPosition().
lineWeight()
static Real ArcaneFemFunctions::FemGaussQuadrature::lineWeight (Integer3 indices, Integer3 ordre) inline static
Provides the integration weight of a Gauss Point for edge elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4535 of file ArcaneFemFunctions.h.
References getWeight().
Referenced by getGaussWeight().
pentaRefPosition()
static Real3 ArcaneFemFunctions::FemGaussQuadrature::pentaRefPosition (Integer3 indices, Integer3 ordre) inline static
Provides the reference coordinates of a Gauss Point for wedge (pentaedron) elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4516 of file ArcaneFemFunctions.h.
References getRefPosition(), and triRefPosition().
pentaWeight()
static Real ArcaneFemFunctions::FemGaussQuadrature::pentaWeight (Integer3 indices, Integer3 ordre) inline static
Provides the integration weight of a Gauss Point for wedge (pentaedron) elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4606 of file ArcaneFemFunctions.h.
References getWeight(), and triWeight().
quadRefPosition()
static Real3 ArcaneFemFunctions::FemGaussQuadrature::quadRefPosition (Integer3 indices, Integer3 ordre) inline static
Provides the reference coordinates of a Gauss Point for quadrangle elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4470 of file ArcaneFemFunctions.h.
References getRefPosition().
Referenced by getGaussRefPosition().
quadWeight()
static Real ArcaneFemFunctions::FemGaussQuadrature::quadWeight (Integer3 indices, Integer3 ordre) inline static
Provides the integration weight of a Gauss Point for quadrangle elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4561 of file ArcaneFemFunctions.h.
References getWeight().
Referenced by getGaussWeight().
tetraRefPosition()
static Real3 ArcaneFemFunctions::FemGaussQuadrature::tetraRefPosition (Integer3 indices, Integer3) inline static
Provides the reference coordinates of a Gauss Point for tetraedron elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4502 of file ArcaneFemFunctions.h.
tetraWeight()
static Real ArcaneFemFunctions::FemGaussQuadrature::tetraWeight (Integer3 , Integer3) inline static
Provides the integration weight of a Gauss Point for tetraedron elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4593 of file ArcaneFemFunctions.h.
triRefPosition()
static Real3 ArcaneFemFunctions::FemGaussQuadrature::triRefPosition (Integer3 indices, Integer3 ordre) inline static
Provides the reference coordinates of a Gauss Point for triangle elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4455 of file ArcaneFemFunctions.h.
Referenced by pentaRefPosition().
triWeight()
static Real ArcaneFemFunctions::FemGaussQuadrature::triWeight (Integer3 indices, Integer3 ordre) inline static
Provides the integration weight of a Gauss Point for triangle elements (coming fro PASSMO). This method takes the indices and integration orders chosen by user as inputs (in (1, 2, 3 directions depending on the space dimension)
Definition at line 4548 of file ArcaneFemFunctions.h.
Referenced by pentaWeight().
The documentation for this class was generated from the following file:
ArcaneFemFunctions.h