ArcaneFem: FemModuleFourier Class Reference
FemModuleFourier Class Reference
A module for finite element method.
#include <modules/fourier/FemModule.h>
Public Member Functions
FemModuleFourier (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleFourier at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
void _assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
void _assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
Private Member Functions
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _getMaterialParameters ()
Retrieves and sets the material parameters for the simulation.
void _solve ()
Solves the linear system and updates the solution vector.
void _assembleLinearOperator ()
void _assembleLinearOperatorCpu ()
FEM linear operator for the current simulation step.
void _validateResults ()
Validates and prints the results of the FEM computation.
void _updateVariables ()
Update the FEM variables.
RealMatrix< 3, 3 > _computeElementMatrixTria3 (Cell cell)
Computes the element matrix for a triangular element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixTetra4 (Cell cell)
Computes the element matrix for a tetrahedral element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixQuad4 (Cell cell)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
RealMatrix< 8, 8 > _computeElementMatrixHexa8 (Cell cell)
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
template<int N>
void _assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the bilinear operator matrix for the FEM linear system.
Private Attributes
Real lambda
Real qdot
Real ElementNodes
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_hex_quad_mesh = false
DoFLinearSystem m_linear_system
IItemFamily * m_dof_family = nullptr
FemDoFsOnNodes m_dofs_on_nodes
BSRFormat m_bsr_format
IBinaryMathFunctor< Real, Real3, Real > * m_manufactured_dirichlet = nullptr
IBinaryMathFunctor< Real, Real3, Real > * m_manufactured_source = nullptr
Detailed Description
A module for finite element method.
This class handles the initialization and computation for finite element method (FEM) simulations, providing methods to set up and solve linear systems, assemble FEM operators, and perform result checks.
Definition at line 59 of file fourier/FemModule.h.
Constructor & Destructor Documentation
FemModuleFourier()
FemModuleFourier::FemModuleFourier (const ModuleBuildInfo & mbi) inline explicit
Definition at line 64 of file fourier/FemModule.h.
Member Function Documentation
_assembleBilinear()
template<int N> void FemModuleFourier::_assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the bilinear operator matrix for the FEM linear system.
The method performs the following steps:
For each cell, retrieves the cell-specific constant lambda.
Computes element matrix using provided compute_element_matrix function.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 414 of file fourier/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleBilinearOperator()
void FemModuleFourier::_assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
Definition at line 357 of file fourier/FemModule.cc.
References _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), _computeElementMatrixTria3(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_assembleLinearOperator()
void FemModuleFourier::_assembleLinearOperator () private
Definition at line 189 of file fourier/FemModule.cc.
_assembleLinearOperatorCpu()
void FemModuleFourier::_assembleLinearOperatorCpu () private
FEM linear operator for the current simulation step.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If a constant source term is specified (qdot), apply it to the RHS.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC are specified apply to the LHS & RHS.
If manufactured source conditions is specified, apply to RHS.
If manufactured Dirichlet BC are specified apply to the LHS & RHS.
Definition at line 216 of file fourier/FemModule.cc.
References ArcaneFemFunctions::BoundaryConditions3D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
_assembleLinearOperatorGpu()
void FemModuleFourier::_assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC/Point are specified apply to the LHS & RHS.
Definition at line 311 of file fourier/FemModule.cc.
References _assembleLinearOperatorGpu(), Arcane::FemUtils::Gpu::BoundaryConditions::applyDirichletToLhsAndRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _assembleLinearOperatorGpu().
_computeElementMatrixHexa8()
RealMatrix< 8, 8 > FemModuleFourier::_computeElementMatrixHexa8 (Cell cell) private
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫∫ λ(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Define Gauss points (2x2x2) and weights.
Loop over Gauss points to compute the gradients in physical space (𝑥,𝑦,𝑧) and the determinant of the Jacobian via computeGradientsAndJacobianHexa8.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 86 of file fourier/ElementMatrixHexQuad.h.
References _computeElementMatrixHexa8(), ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator(), and _computeElementMatrixHexa8().
_computeElementMatrixQuad4()
RealMatrix< 4, 4 > FemModuleFourier::_computeElementMatrixQuad4 (Cell cell) private
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫ λ(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 33 of file fourier/ElementMatrixHexQuad.h.
References _computeElementMatrixQuad4(), ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator(), and _computeElementMatrixQuad4().
_computeElementMatrixTetra4()
RealMatrix< 4, 4 > FemModuleFourier::_computeElementMatrixTetra4 (Cell cell) private
Computes the element matrix for a tetrahedral element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫∫ λ(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 74 of file fourier/ElementMatrix.h.
References _computeElementMatrixTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
Referenced by _assembleBilinearOperator(), and _computeElementMatrixTetra4().
_computeElementMatrixTria3()
RealMatrix< 3, 3 > FemModuleFourier::_computeElementMatrixTria3 (Cell cell) private
Computes the element matrix for a triangular element (ℙ1 FE).
This function calculates the expression: a(𝑢,𝑣) = ∫∫ λ(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 28 of file fourier/ElementMatrix.h.
References _computeElementMatrixTria3(), ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
Referenced by _assembleBilinearOperator(), and _computeElementMatrixTria3().
_doStationarySolve()
void FemModuleFourier::_doStationarySolve () private
Performs a stationary solve for the FEM system.
This method follows via the following steps:
_getMaterialParameters() Retrieves material parameters
_assembleBilinearOperator() Assembles the FEM matrix 𝐀
_assembleLinearOperator() Assembles the FEM RHS vector 𝐛
_solve() Solves for solution vector 𝐮 = 𝐀⁻¹𝐛
_updateVariables() Updates FEM variables 𝐮 = 𝐱
_validateResults() Regression test
Definition at line 133 of file fourier/FemModule.cc.
References _assembleBilinearOperator(), _getMaterialParameters(), _solve(), _updateVariables(), and _validateResults().
Referenced by compute().
_getMaterialParameters()
void FemModuleFourier::_getMaterialParameters () private
Retrieves and sets the material parameters for the simulation.
This method initializes:
material properties:
thermal conductivity coefficient (<tt>lambda</tt>)
heat source term (<tt>qdot</tt>)
Definition at line 163 of file fourier/FemModule.cc.
References Arcane::FemUtils::RealMatrix< N, M >::fill(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_solve()
void FemModuleFourier::_solve () private
Solves the linear system and updates the solution vector.
This method performs the following actions:
Solves the linear system to compute the solution.
Copies the computed solution from the DoF to the node values.
Synchronizes the updated node values.
Definition at line 450 of file fourier/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updateVariables()
void FemModuleFourier::_updateVariables () private
Update the FEM variables.
This method performs the following actions:
Fetches values of solution from solved linear system to FEM variables, i.e., it copies RHS DOF to u.
Performs synchronize of FEM variables across subdomains.
Definition at line 473 of file fourier/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_validateResults()
void FemModuleFourier::_validateResults () private
Validates and prints the results of the FEM computation.
This method performs the following actions:
If number of nodes < 200, prints the computed values for each node.
Retrieves the filename for the result file from options.
If a filename is provided, checks the computed results against result file.
Note
The result comparison uses a tolerance of 1.0e-4.
Definition at line 518 of file fourier/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
compute()
void FemModuleFourier::compute () override
Method called at the beginning of the simulation.
Performs the main computation for the FemModuleFourier.
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Executes the stationary solve.
Definition at line 82 of file fourier/FemModule.cc.
References _doStationarySolve(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleFourier::startInit () override
Initializes the FemModuleFourier at the start of the simulation.
initializes degrees of freedom (DoFs) on nodes.
builds support for manufactured test case (optional).
Definition at line 27 of file fourier/FemModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleFourier::versionInfo () const inline override
Method called at each iteration.
Definition at line 76 of file fourier/FemModule.h.
Member Data Documentation
ElementNodes
Real FemModuleFourier::ElementNodes private
Definition at line 85 of file fourier/FemModule.h.
lambda
Real FemModuleFourier::lambda private
Definition at line 83 of file fourier/FemModule.h.
m_assemble_linear_system
bool FemModuleFourier::m_assemble_linear_system = true private
Definition at line 90 of file fourier/FemModule.h.
m_bsr_format
BSRFormat FemModuleFourier::m_bsr_format private
Definition at line 98 of file fourier/FemModule.h.
m_cross_validation
bool FemModuleFourier::m_cross_validation = false private
Definition at line 92 of file fourier/FemModule.h.
m_dof_family
IItemFamily* FemModuleFourier::m_dof_family = nullptr private
Definition at line 96 of file fourier/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleFourier::m_dofs_on_nodes private
Definition at line 97 of file fourier/FemModule.h.
m_hex_quad_mesh
bool FemModuleFourier::m_hex_quad_mesh = false private
Definition at line 93 of file fourier/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleFourier::m_linear_system private
Definition at line 95 of file fourier/FemModule.h.
m_manufactured_dirichlet
IBinaryMathFunctor<Real, Real3, Real>* FemModuleFourier::m_manufactured_dirichlet = nullptr private
Definition at line 112 of file fourier/FemModule.h.
m_manufactured_source
IBinaryMathFunctor<Real, Real3, Real>* FemModuleFourier::m_manufactured_source = nullptr private
Definition at line 113 of file fourier/FemModule.h.
m_matrix_format
String FemModuleFourier::m_matrix_format = "DOK" private
Definition at line 88 of file fourier/FemModule.h.
m_petsc_flags
String FemModuleFourier::m_petsc_flags private
Definition at line 87 of file fourier/FemModule.h.
m_solve_linear_system
bool FemModuleFourier::m_solve_linear_system = true private
Definition at line 91 of file fourier/FemModule.h.
qdot
Real FemModuleFourier::qdot private
Definition at line 84 of file fourier/FemModule.h.
The documentation for this class was generated from the following files:
fourier/FemModule.h
fourier/ElementMatrix.h
fourier/ElementMatrixHexQuad.h
fourier/FemModule.cc