ArcaneFem: Arcane::FemUtils::Tensor2 Class Reference
Arcane::FemUtils::Tensor2 Class Reference
Public Member Functions
__host__ __device__ Tensor2 (std::initializer_list< Real > init_list)
__host__ __device__ Tensor2 (const Real3 &a, const Real3 &b)
__host__ __device__ Tensor2 (const RealVector< 6 > &vec)
__host__ __device__ Tensor2 (const Real3x3 &mat)
__host__ __device__ Real & operator() (Int32 i)
__host__ __device__ RealVector< 6 > getVec () const
__host__ __device__ Real operator() (Int32 i) const
__host__ __device__ Real & operator() (Int32 i, Int32 j)
__host__ __device__ Real operator() (Int32 i, Int32 j) const
__host__ __device__ operator Real3x3 () const
Convert this Tensor to Real3x3 matrix.
__host__ __device__ void multInPlace (Real v)
Multiply all the components by v.
__host__ __device__ void addInPlace (Real v)
Add v to all the components.
void dump (std::ostream &o) const
Dump values.
__host__ __device__ bool operator== (const Tensor2 &vec)
Define the == operator.
__host__ __device__ Tensor2 & operator= (const Tensor2 &vec)
Define the = operator.
__host__ __device__ Tensor2 & operator= (const Real3x3 &mat)
Define the = operator.
__host__ __device__ Tensor2 operator+ (const Tensor2 &other) const
Define the addition operator.
__host__ __device__ Tensor2 & operator+= (const Tensor2 &vec)
Define the += operator.
__host__ __device__ Tensor2 operator- (const Tensor2 &other) const
Define the subtraction operator.
__host__ __device__ Tensor2 & operator-= (const Tensor2 &vec)
Define the -= operator.
__host__ __device__ Tensor2 operator- () const
Define the unary negation operator.
__host__ __device__ void setEqualTo (const Tensor2 &b)
Set this Tensor2 equal to b.
__host__ __device__ void setVec (const Real3 &d, const Real3 &s)
__host__ __device__ void add (const Tensor2 &b)
Add b to this Tensor2.
__host__ __device__ void add (const Real3x3 &b)
Substract b to this Tensor2.
__host__ __device__ void add (const RealVector< 6 > &b)
Add b to this Tensor2.
__host__ __device__ void sub (const Tensor2 &b)
Substract b to this Tensor2.
__host__ __device__ void sub (const Real3x3 &b)
Substract b to this Tensor2.
__host__ __device__ void sub (const RealVector< 6 > &b)
Substract b to this Tensor2.
__host__ __device__ Tensor2 operator* (Real scalar) const
Scalar multiplication: Tensor * scalar.
__host__ __device__ Tensor2 & operator*= (Real scalar)
Define the *= operator.
__host__ __device__ Tensor2 operator/ (Real scalar) const
Scalar division: Tensor / scalar.
__host__ __device__ Tensor2 & operator/= (Real scalar)
Define the *= operator.
__host__ __device__ Real3 get_diagonal () const
__host__ __device__ void set_diagonal (const Real3 &d)
__host__ __device__ Real3 get_outdiagonal () const
__host__ __device__ void set_outdiagonal (const Real3 &s)
__host__ __device__ Real trace () const
__host__ __device__ Real norm () const
__host__ __device__ void fromReal3x3ToTensor2 (const Real3x3 &mat)
Function to convert Real3x3 matrix (symmetric) to Tensor.
Static Public Member Functions
static constexpr Int32 totalNbElement ()
static Tensor2 identity ()
Return Identity Tensor2.
static Tensor2 zero ()
Return zero Tensor2.
static Arcane::Int32 get_index (Arcane::Int32 i, Arcane::Int32 j)
Private Attributes
RealVector< 6 > m_vec
Friends
__host__ __device__ friend Tensor2 operator* (Real scalar, const Tensor2 &vector)
Friend function for scalar multiplication: scalar * Tensor.
__host__ __device__ friend Real3x3 fromTensor2Real3x3 (const Tensor2 &vector)
Friend function to convert Tensor to Real3x3 matrix.
Detailed Description
Definition at line 643 of file FemUtils.h.
Constructor & Destructor Documentation
Tensor2() [1/4]
__host__ __device__ Arcane::FemUtils::Tensor2::Tensor2 (std::initializer_list< Real > init_list) inline
Definition at line 653 of file FemUtils.h.
Tensor2() [2/4]
__host__ __device__ Arcane::FemUtils::Tensor2::Tensor2 (const Real3 & a, const Real3 & b) inline
Definition at line 656 of file FemUtils.h.
Tensor2() [3/4]
__host__ __device__ Arcane::FemUtils::Tensor2::Tensor2 (const RealVector< 6 > & vec) inline explicit
Definition at line 659 of file FemUtils.h.
Tensor2() [4/4]
__host__ __device__ Arcane::FemUtils::Tensor2::Tensor2 (const Real3x3 & mat) inline explicit
Definition at line 663 of file FemUtils.h.
Member Function Documentation
add() [1/3]
__host__ __device__ void Arcane::FemUtils::Tensor2::add (const Real3x3 & b) inline
Substract b to this Tensor2.
Definition at line 807 of file FemUtils.h.
References add().
add() [2/3]
__host__ __device__ void Arcane::FemUtils::Tensor2::add (const RealVector< 6 > & b) inline
Add b to this Tensor2.
Definition at line 813 of file FemUtils.h.
add() [3/3]
__host__ __device__ void Arcane::FemUtils::Tensor2::add (const Tensor2 & b) inline
Add b to this Tensor2.
Definition at line 802 of file FemUtils.h.
Referenced by add().
addInPlace()
__host__ __device__ void Arcane::FemUtils::Tensor2::addInPlace (Real v) inline
Add v to all the components.
Definition at line 719 of file FemUtils.h.
dump()
void Arcane::FemUtils::Tensor2::dump (std::ostream & o) const inline
Dump values.
Definition at line 722 of file FemUtils.h.
References Arcane::FemUtils::RealMatrix< N, M >::dump().
fromReal3x3ToTensor2()
__host__ __device__ void Arcane::FemUtils::Tensor2::fromReal3x3ToTensor2 (const Real3x3 & mat) inline
Function to convert Real3x3 matrix (symmetric) to Tensor.
Definition at line 901 of file FemUtils.h.
get_diagonal()
__host__ __device__ Real3 Arcane::FemUtils::Tensor2::get_diagonal () const inline
Definition at line 877 of file FemUtils.h.
get_index()
static Arcane::Int32 Arcane::FemUtils::Tensor2::get_index (Arcane::Int32 i, Arcane::Int32 j) inline static
Definition at line 865 of file FemUtils.h.
get_outdiagonal()
__host__ __device__ Real3 Arcane::FemUtils::Tensor2::get_outdiagonal () const inline
Definition at line 885 of file FemUtils.h.
getVec()
__host__ __device__ RealVector< 6 > Arcane::FemUtils::Tensor2::getVec () const inline
Definition at line 678 of file FemUtils.h.
identity()
static Tensor2 Arcane::FemUtils::Tensor2::identity () inline static
Return Identity Tensor2.
Definition at line 710 of file FemUtils.h.
multInPlace()
__host__ __device__ void Arcane::FemUtils::Tensor2::multInPlace (Real v) inline
Multiply all the components by v.
Definition at line 716 of file FemUtils.h.
References Arcane::FemUtils::RealMatrix< N, M >::multInPlace().
norm()
__host__ __device__ Real Arcane::FemUtils::Tensor2::norm () const inline
Definition at line 896 of file FemUtils.h.
operator Real3x3()
__host__ __device__ Arcane::FemUtils::Tensor2::operator Real3x3 () const inline explicit
Convert this Tensor to Real3x3 matrix.
Definition at line 697 of file FemUtils.h.
operator()() [1/4]
__host__ __device__ Real & Arcane::FemUtils::Tensor2::operator() (Int32 i) inline
Definition at line 674 of file FemUtils.h.
operator()() [2/4]
__host__ __device__ Real Arcane::FemUtils::Tensor2::operator() (Int32 i) const inline
Definition at line 680 of file FemUtils.h.
operator()() [3/4]
__host__ __device__ Real & Arcane::FemUtils::Tensor2::operator() (Int32 i, Int32 j) inline
Definition at line 684 of file FemUtils.h.
operator()() [4/4]
__host__ __device__ Real Arcane::FemUtils::Tensor2::operator() (Int32 i, Int32 j) const inline
Definition at line 690 of file FemUtils.h.
operator*()
__host__ __device__ Tensor2 Arcane::FemUtils::Tensor2::operator* (Real scalar) const inline
Scalar multiplication: Tensor * scalar.
Definition at line 836 of file FemUtils.h.
operator*=()
__host__ __device__ Tensor2 & Arcane::FemUtils::Tensor2::operator*= (Real scalar) inline
Define the *= operator.
Definition at line 845 of file FemUtils.h.
References operator*.
operator+()
__host__ __device__ Tensor2 Arcane::FemUtils::Tensor2::operator+ (const Tensor2 & other) const inline
Define the addition operator.
Definition at line 750 of file FemUtils.h.
Referenced by operator+=().
operator+=()
__host__ __device__ Tensor2 & Arcane::FemUtils::Tensor2::operator+= (const Tensor2 & vec) inline
Define the += operator.
Definition at line 759 of file FemUtils.h.
References operator+().
operator-() [1/2]
__host__ __device__ Tensor2 Arcane::FemUtils::Tensor2::operator- () const inline
Define the unary negation operator.
Definition at line 780 of file FemUtils.h.
Referenced by operator-=().
operator-() [2/2]
__host__ __device__ Tensor2 Arcane::FemUtils::Tensor2::operator- (const Tensor2 & other) const inline
Define the subtraction operator.
Definition at line 765 of file FemUtils.h.
operator-=()
__host__ __device__ Tensor2 & Arcane::FemUtils::Tensor2::operator-= (const Tensor2 & vec) inline
Define the -= operator.
Definition at line 774 of file FemUtils.h.
References operator-().
operator/()
__host__ __device__ Tensor2 Arcane::FemUtils::Tensor2::operator/ (Real scalar) const inline
Scalar division: Tensor / scalar.
Definition at line 851 of file FemUtils.h.
Referenced by operator/=().
operator/=()
__host__ __device__ Tensor2 & Arcane::FemUtils::Tensor2::operator/= (Real scalar) inline
Define the *= operator.
Definition at line 860 of file FemUtils.h.
References operator/().
operator=() [1/2]
__host__ __device__ Tensor2 & Arcane::FemUtils::Tensor2::operator= (const Real3x3 & mat) inline
Define the = operator.
Definition at line 741 of file FemUtils.h.
operator=() [2/2]
__host__ __device__ Tensor2 & Arcane::FemUtils::Tensor2::operator= (const Tensor2 & vec) inline
Define the = operator.
Definition at line 735 of file FemUtils.h.
operator==()
__host__ __device__ bool Arcane::FemUtils::Tensor2::operator== (const Tensor2 & vec) inline
Define the == operator.
Definition at line 725 of file FemUtils.h.
set_diagonal()
__host__ __device__ void Arcane::FemUtils::Tensor2::set_diagonal (const Real3 & d) inline
Definition at line 881 of file FemUtils.h.
set_outdiagonal()
__host__ __device__ void Arcane::FemUtils::Tensor2::set_outdiagonal (const Real3 & s) inline
Definition at line 888 of file FemUtils.h.
setEqualTo()
__host__ __device__ void Arcane::FemUtils::Tensor2::setEqualTo (const Tensor2 & b) inline
Set this Tensor2 equal to b.
Definition at line 789 of file FemUtils.h.
setVec()
__host__ __device__ void Arcane::FemUtils::Tensor2::setVec (const Real3 & d, const Real3 & s) inline
Definition at line 794 of file FemUtils.h.
sub() [1/3]
__host__ __device__ void Arcane::FemUtils::Tensor2::sub (const Real3x3 & b) inline
Substract b to this Tensor2.
Definition at line 824 of file FemUtils.h.
References sub().
sub() [2/3]
__host__ __device__ void Arcane::FemUtils::Tensor2::sub (const RealVector< 6 > & b) inline
Substract b to this Tensor2.
Definition at line 830 of file FemUtils.h.
sub() [3/3]
__host__ __device__ void Arcane::FemUtils::Tensor2::sub (const Tensor2 & b) inline
Substract b to this Tensor2.
Definition at line 819 of file FemUtils.h.
Referenced by sub().
totalNbElement()
static constexpr Int32 Arcane::FemUtils::Tensor2::totalNbElement () inline static constexpr
Definition at line 649 of file FemUtils.h.
trace()
__host__ __device__ Real Arcane::FemUtils::Tensor2::trace () const inline
Definition at line 892 of file FemUtils.h.
zero()
static Tensor2 Arcane::FemUtils::Tensor2::zero () inline static
Return zero Tensor2.
Definition at line 712 of file FemUtils.h.
Friends And Related Symbol Documentation
fromTensor2Real3x3
__host__ __device__ friend Real3x3 fromTensor2Real3x3 (const Tensor2 & vector) friend
Friend function to convert Tensor to Real3x3 matrix.
Definition at line 918 of file FemUtils.h.
operator*
__host__ __device__ friend Tensor2 operator* (Real scalar, const Tensor2 & vector) friend
Friend function for scalar multiplication: scalar * Tensor.
Definition at line 909 of file FemUtils.h.
Referenced by operator*=().
Member Data Documentation
m_vec
RealVector<6> Arcane::FemUtils::Tensor2::m_vec private
Definition at line 645 of file FemUtils.h.
The documentation for this class was generated from the following file:
FemUtils.h