ArcaneFem: Arcane::FemUtils::CsrFormat Class Reference
Arcane::FemUtils::CsrFormat Class Reference
Public Member Functions
CsrFormat (ITraceMng *tm)
void initialize (IItemFamily *dof_family, Int32 nnz, Int32 nbRow, RunQueue &queue)
void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value)
Int32 indexValue (DoFLocalId row, DoFLocalId column)
void translateToLinearSystem (DoFLinearSystem &linear_system, const RunQueue &queue)
void printMatrix (std::string fileName)
function to print the current content of the csr matrix
void setCoordinates (DoFLocalId row, DoFLocalId column)
void matrixSetValue (DoFLocalId row, DoFLocalId column, Real value)
CsrFormatMatrixView view ()
View of the matrix.
Int32 getValue (DoFLocalId row, DoFLocalId column)
Return the Value at the (row, column) coordinates.
Public Attributes
Int32 m_nnz = 0
Int32 m_last_value = 0
NumArray< Int32, MDDim1 > m_matrix_row
NumArray< Int32, MDDim1 > m_matrix_column
NumArray< Real, MDDim1 > m_matrix_value
NumArray< Int32, MDDim1 > m_matrix_rows_nb_column
Nombre de colonnes de chaque lignes.
IItemFamily * m_dof_family = nullptr
Detailed Description
Definition at line 32 of file CsrFormatMatrix.h.
Constructor & Destructor Documentation
CsrFormat()
Arcane::FemUtils::CsrFormat::CsrFormat (ITraceMng * tm) inline explicit
Definition at line 37 of file CsrFormatMatrix.h.
Member Function Documentation
getValue()
Int32 Arcane::FemUtils::CsrFormat::getValue (DoFLocalId row, DoFLocalId column) inline
Return the Value at the (row, column) coordinates.
Definition at line 133 of file CsrFormatMatrix.h.
indexValue()
Int32 Arcane::FemUtils::CsrFormat::indexValue (DoFLocalId row, DoFLocalId column) inline
Definition at line 64 of file CsrFormatMatrix.h.
initialize()
void Arcane::FemUtils::CsrFormat::initialize (IItemFamily * dof_family, Int32 nnz, Int32 nbRow, RunQueue & queue)
Definition at line 30 of file CsrFormatMatrix.cc.
matrixAddValue()
void Arcane::FemUtils::CsrFormat::matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) inline
Parameters
row
column
value
Definition at line 53 of file CsrFormatMatrix.h.
matrixSetValue()
void Arcane::FemUtils::CsrFormat::matrixSetValue (DoFLocalId row, DoFLocalId column, Real value) inline
Definition at line 110 of file CsrFormatMatrix.h.
printMatrix()
void Arcane::FemUtils::CsrFormat::printMatrix (std::string fileName)
function to print the current content of the csr matrix
Parameters
fileName
nonzero if set to true, print only the non zero values
Definition at line 101 of file CsrFormatMatrix.cc.
setCoordinates()
void Arcane::FemUtils::CsrFormat::setCoordinates (DoFLocalId row, DoFLocalId column) inline
Definition at line 100 of file CsrFormatMatrix.h.
translateToLinearSystem()
void Arcane::FemUtils::CsrFormat::translateToLinearSystem (DoFLinearSystem & linear_system, const RunQueue & queue)
Parameters
linear_system
Definition at line 58 of file CsrFormatMatrix.cc.
References Arcane::FemUtils::DoFLinearSystem::hasSetCSRValues(), m_matrix_rows_nb_column, Arcane::FemUtils::DoFLinearSystem::matrixAddValue(), Arcane::FemUtils::DoFLinearSystem::setCSRValues(), and view().
view()
CsrFormatMatrixView Arcane::FemUtils::CsrFormat::view ()
View of the matrix.
Definition at line 94 of file CsrFormatMatrix.cc.
References m_matrix_rows_nb_column.
Referenced by translateToLinearSystem().
Member Data Documentation
m_dof_family
IItemFamily* Arcane::FemUtils::CsrFormat::m_dof_family = nullptr
Definition at line 130 of file CsrFormatMatrix.h.
m_last_value
Int32 Arcane::FemUtils::CsrFormat::m_last_value = 0
Definition at line 124 of file CsrFormatMatrix.h.
m_matrix_column
NumArray<Int32, MDDim1> Arcane::FemUtils::CsrFormat::m_matrix_column
Definition at line 126 of file CsrFormatMatrix.h.
m_matrix_row
NumArray<Int32, MDDim1> Arcane::FemUtils::CsrFormat::m_matrix_row
Definition at line 125 of file CsrFormatMatrix.h.
m_matrix_rows_nb_column
NumArray<Int32, MDDim1> Arcane::FemUtils::CsrFormat::m_matrix_rows_nb_column
Nombre de colonnes de chaque lignes.
Definition at line 129 of file CsrFormatMatrix.h.
Referenced by translateToLinearSystem(), and view().
m_matrix_value
NumArray<Real, MDDim1> Arcane::FemUtils::CsrFormat::m_matrix_value
Definition at line 127 of file CsrFormatMatrix.h.
m_nnz
Int32 Arcane::FemUtils::CsrFormat::m_nnz = 0
Definition at line 120 of file CsrFormatMatrix.h.
The documentation for this class was generated from the following files:
CsrFormatMatrix.h
CsrFormatMatrix.cc