ArcaneFem: ArcaneFemFunctions::FeOperation2D Class Reference
ArcaneFemFunctions::FeOperation2D Class Reference
Provides methods for finite element operations in 2D.
#include <femutils/ArcaneFemFunctions.h>
Classes
struct Quad4GaussPointInfo
Holds information for a Quad4 element at a single Gauss point.
Static Public Member Functions
static Real3 computeGradientTria3 (Cell cell, const VariableNodeReal3 &node_coord, VariableNodeReal u)
Computes the gradients of given function U for P1 triangles.
static Real3 computeGradientXTria3 (Cell cell, const VariableNodeReal3 &node_coord)
Computes the 𝑥 gradients of basis functions 𝐍 for ℙ1 triangles.
static Real3 computeGradientYTria3 (Cell cell, VariableNodeReal3 node_coord)
Computes the 𝑦 gradients of basis functions 𝐍 for ℙ1 triangles.
static Quad4GaussPointInfo computeGradientsAndJacobianQuad4 (Cell cell, const VariableNodeReal3 &node_coord, Real xi, Real eta)
Computes shape function gradients and the Jacobian determinant for a Quad4 element.
static Real3 computeGradientQuad4 (Cell cell, const VariableNodeReal3 &node_coord, const VariableNodeReal &u)
Computes the gradient of a scalar field 'u' for a Quad4 element.
static RealVector< 4 > computeShapeFunctionsQuad4 (Real xi, Real eta)
Computes the shape functions for a Quad4 element at a given point (ξ, η).
Detailed Description
Provides methods for finite element operations in 2D.
This class includes static methods for calculating gradients of basis functions and integrals for P1 triangles in 2D finite element analysis.
Reference Tri3 and Quad4 element in Arcane
          0 o                    1 o . . . . o 0
           . .                     .         .
          .   .                    .         .
         .     .                   .         .
      1 o  . .  o 2              2 o . . . . o 3
Definition at line 592 of file ArcaneFemFunctions.h.
Member Function Documentation
computeGradientQuad4()
static Real3 ArcaneFemFunctions::FeOperation2D::computeGradientQuad4 (Cell cell, const VariableNodeReal3 & node_coord, const VariableNodeReal & u) inline static
Computes the gradient of a scalar field 'u' for a Quad4 element.
Parameters
cell The Quad4 cell entity.
node_coord The coordinates of the mesh nodes.
u The scalar variable 𝑢 defined at the nodes.
Returns
A Real3 vector of the gradient ∇𝑢 = {∂𝑢/∂𝑥, ∂𝑢/∂𝑦, 0} at the cell center.
Definition at line 772 of file ArcaneFemFunctions.h.
References computeGradientsAndJacobianQuad4().
Referenced by FemModuleElectrostatics::_updateVariables().
computeGradientsAndJacobianQuad4()
static Quad4GaussPointInfo ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4 (Cell cell, const VariableNodeReal3 & node_coord, Real xi, Real eta) inline static
Computes shape function gradients and the Jacobian determinant for a Quad4 element.
Parameters
cell The Quad4 cell entity.
node_coord The coordinates of the mesh nodes.
xi The ξ coordinate of the evaluation point (-1 to 1).
eta The η coordinate of the evaluation point (-1 to 1).
Returns
A Quad4GaussPointInfo struct containing {∂𝐍/∂𝑥, ∂𝐍/∂𝑦, det(𝑱)}.
Definition at line 708 of file ArcaneFemFunctions.h.
Referenced by FemModuleElasticity::_applyBodyForce(), FemModuleAcoustics::_computeElementMatrixQuad4(), FemModuleAerodynamics::_computeElementMatrixQuad4(), FemModuleElastodynamics::_computeElementMatrixQuad4(), FemModuleElectrostatics::_computeElementMatrixQuad4(), FemModuleFourier::_computeElementMatrixQuad4(), FemModuleFourierNL::_computeElementMatrixQuad4(), FemModuleHeat::_computeElementMatrixQuad4(), FemModuleLaplace::_computeElementMatrixQuad4(), FemModulePoisson::_computeElementMatrixQuad4(), FemModuleSoildynamics::_computeElementMatrixQuad4(), computeGradientQuad4(), and ArcaneFemFunctions::BoundaryConditions2D::integrateNodalFieldToRhsQuad4().
computeGradientTria3()
static Real3 ArcaneFemFunctions::FeOperation2D::computeGradientTria3 (Cell cell, const VariableNodeReal3 & node_coord, VariableNodeReal u) inline static
Computes the gradients of given function U for P1 triangles.
This method calculates gradient operator ∇ Ui for a given P1 cell with i = 1,..,3 for the three values of Ui hence at cell nodes. The output is ∇ Ui is P0 (piece-wise constant) hence Real3 value per cell
    ∇ Ui = [ ∂U/∂𝑥   ∂U/∂𝑦   ∂U/∂𝑧 ]
    ∂U/∂𝑥 = ( u1*(y2 − y3) + u2*(y3 − y1) + u3*(y1 − y2) ) / (2*A)
    ∂U/∂𝑦 = ( u1*(x3 − x2) + u2*(x1 − x3) + u3*(x2 − x1) ) / (2*A)
    ∂U/∂𝑧 = 0
Note
we can adapt the same for 3D by filling the third component
Definition at line 616 of file ArcaneFemFunctions.h.
Referenced by FemModuleElectrostatics::_updateVariables().
computeGradientXTria3()
static Real3 ArcaneFemFunctions::FeOperation2D::computeGradientXTria3 (Cell cell, const VariableNodeReal3 & node_coord) inline static
Computes the 𝑥 gradients of basis functions 𝐍 for ℙ1 triangles.
This method calculates gradient operator ∂/∂𝑥 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,3 for the three shape function 𝑁ᵢ hence output is a vector of size 3
    ∂𝐍/∂𝑥 = [ ∂𝑁₁/∂𝑥  ∂𝑁₂/∂𝑥  ∂𝑁₃/∂𝑥 ]
    ∂𝐍/∂𝑥 = 1/(2𝐴) [ 𝑦₂-𝑦₃  𝑦₃-𝑦₁  𝑦₁-𝑦₂ ]
Definition at line 645 of file ArcaneFemFunctions.h.
Referenced by FemModuleAcoustics::_computeElementMatrixTria3(), FemModuleAerodynamics::_computeElementMatrixTria3(), FemModuleBilaplacian::_computeElementMatrixTria3(), FemModuleElastodynamics::_computeElementMatrixTria3(), FemModuleElectrostatics::_computeElementMatrixTria3(), FemModuleFourier::_computeElementMatrixTria3(), FemModuleFourierNL::_computeElementMatrixTria3(), FemModuleHeat::_computeElementMatrixTria3(), FemModuleLaplace::_computeElementMatrixTria3(), FemModulePoisson::_computeElementMatrixTria3(), and FemModuleSoildynamics::_computeElementMatrixTria3().
computeGradientYTria3()
static Real3 ArcaneFemFunctions::FeOperation2D::computeGradientYTria3 (Cell cell, VariableNodeReal3 node_coord) inline static
Computes the 𝑦 gradients of basis functions 𝐍 for ℙ1 triangles.
This method calculates gradient operator ∂/∂𝑦 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,3 for the three shape function 𝑁ᵢ hence output is a vector of size 3
    ∂𝐍/∂𝑦 = [ ∂𝑁₁/∂𝑦  ∂𝑁₂/∂𝑦  ∂𝑁₃/∂𝑦 ]
    ∂𝐍/∂𝑦 = 1/(2𝐴) [ 𝑥₃−𝑥₂  𝑥₁−𝑥₃  𝑥₂−𝑥₁ ]
Definition at line 670 of file ArcaneFemFunctions.h.
Referenced by FemModuleAcoustics::_computeElementMatrixTria3(), FemModuleAerodynamics::_computeElementMatrixTria3(), FemModuleBilaplacian::_computeElementMatrixTria3(), FemModuleElastodynamics::_computeElementMatrixTria3(), FemModuleElectrostatics::_computeElementMatrixTria3(), FemModuleFourier::_computeElementMatrixTria3(), FemModuleFourierNL::_computeElementMatrixTria3(), FemModuleHeat::_computeElementMatrixTria3(), FemModuleLaplace::_computeElementMatrixTria3(), FemModulePoisson::_computeElementMatrixTria3(), and FemModuleSoildynamics::_computeElementMatrixTria3().
computeShapeFunctionsQuad4()
static RealVector< 4 > ArcaneFemFunctions::FeOperation2D::computeShapeFunctionsQuad4 (Real xi, Real eta) inline static
Computes the shape functions for a Quad4 element at a given point (ξ, η).
Parameters
xi The ξ coordinate of the evaluation point (-1 to 1).
eta The η coordinate of the evaluation point (-1 to 1).
Returns
A RealVector<4> containing the shape functions {𝑁₁, 𝑁₂, 𝑁₃, 𝑁₄}.
Definition at line 809 of file ArcaneFemFunctions.h.
Referenced by FemModuleElasticity::_applyBodyForce(), FemModuleAcoustics::_computeElementMatrixQuad4(), FemModuleElastodynamics::_computeElementMatrixQuad4(), FemModuleFourierNL::_computeElementMatrixQuad4(), FemModuleHeat::_computeElementMatrixQuad4(), and FemModuleSoildynamics::_computeElementMatrixQuad4().
The documentation for this class was generated from the following file:
ArcaneFemFunctions.h