ArcaneFem: FemModuleElastodynamics Class Reference
FemModuleElastodynamics Class Reference
Module Fem.
#include <modules/elastodynamics/FemModule.h>
Public Member Functions
FemModuleElastodynamics (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleElastodynamics at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
void _assembleBilinearOperatorTria3Gpu ()
void _assembleBilinearOperatorTetra4Gpu ()
void _assembleDirichletsGpu ()
Applies dirichlet to LHS matrix and RHS vector of the linear system on Gpu.
Private Member Functions
void _doStationarySolve ()
void _getParameters ()
void _updateVariables ()
void _updateTime ()
void _solve ()
void _assembleLinearOperator ()
void _validateResults ()
void _readCaseTables ()
void _assembleBilinearOperator ()
void _applyTraction (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies traction to the RHS vector of the linear system.
void _applyDirichlet (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies dirichlet to LHS matrix and RHS vector of the linear system.
void _applySourceTerm (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies source term to RHS vector of the linear system.
void _applySourceTermTria3 (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
void _applySourceTermQuad4 (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
void _applySourceTermTetra4 (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
void _applySourceTermHexa8 (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
RealMatrix< 6, 6 > _computeElementMatrixTria3 (Cell cell)
Computes the element matrix for a triangular element (ℙ1 FE).
RealMatrix< 12, 12 > _computeElementMatrixTetra4 (Cell cell)
Computes the element matrix for a tetrahedral element (ℙ1 FE).
RealMatrix< 8, 8 > _computeElementMatrixQuad4 (Cell cell)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
RealMatrix< 24, 24 > _computeElementMatrixHexa8 (Cell cell)
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
template<int N>
void _assembleBilinearOperatorCpu (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the FEM bilinear operator on CPU.
Private Attributes
Real t
Real dt
Real tmax
Real alpm
Real alpf
Real beta
Real gamma
Real etam
Real etak
Real E
Real nu
Real rho
Real mu
Real lambda
Real3 f = {0,0,0}
Real c0
Real c1
Real c2
Real c3
Real c4
Real c5
Real c6
Real c7
Real c8
Real c9
Real c10
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_hex_quad_mesh = false
DoFLinearSystem m_linear_system
FemDoFsOnNodes m_dofs_on_nodes
BSRFormat m_bsr_format
UniqueArray< CaseTableInfo > m_traction_case_table_list
Detailed Description
Module Fem.
Definition at line 51 of file elastodynamics/FemModule.h.
Constructor & Destructor Documentation
FemModuleElastodynamics()
FemModuleElastodynamics::FemModuleElastodynamics (const ModuleBuildInfo & mbi) inline explicit
Definition at line 56 of file elastodynamics/FemModule.h.
~FemModuleElastodynamics()
FemModuleElastodynamics::~FemModuleElastodynamics () inline
Definition at line 65 of file elastodynamics/FemModule.h.
Member Function Documentation
_applyDirichlet()
void FemModuleElastodynamics::_applyDirichlet (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Applies dirichlet to LHS matrix and RHS vector of the linear system.
This function applies Dirichlet boundary conditions to both the LHS matrix and RHS vector of the linear system.
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 26 of file elastodynamics/Dirichlet.h.
References _assembleDirichletsGpu(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToRhs(), ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToRhs().
_applySourceTerm()
void FemModuleElastodynamics::_applySourceTerm (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Applies source term to RHS vector of the linear system.
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 23 of file elastodynamics/SourceTerm.h.
_applySourceTermHexa8()
void FemModuleElastodynamics::_applySourceTermHexa8 (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Definition at line 249 of file elastodynamics/SourceTerm.h.
_applySourceTermQuad4()
void FemModuleElastodynamics::_applySourceTermQuad4 (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Definition at line 96 of file elastodynamics/SourceTerm.h.
_applySourceTermTetra4()
void FemModuleElastodynamics::_applySourceTermTetra4 (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Definition at line 165 of file elastodynamics/SourceTerm.h.
_applySourceTermTria3()
void FemModuleElastodynamics::_applySourceTermTria3 (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Definition at line 39 of file elastodynamics/SourceTerm.h.
_applyTraction()
void FemModuleElastodynamics::_applyTraction (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Applies traction to the RHS vector of the linear system.
This function computes the contribution of traction to the RHS vector of the linear system. It iterates over all cells in the mesh, calculates the appropriate force contributions based on the element type and mesh dimension, and updates the RHS vector accordingly.
traction term ∫∫ (𝐭.𝐯) with 𝐭 = (𝑡𝑥, 𝑡𝑦, 𝑡𝑧) = (t[0], t[1], t[2])
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding degrees of freedom (DoFs).
/*------------------------------------------------------------------------—
Definition at line 31 of file elastodynamics/Traction.h.
References ArcaneFemFunctions::BoundaryConditions3D::applyTractionTableToRhsTetra4(), ArcaneFemFunctions::BoundaryConditions2D::applyTractionTableToRhsTria3(), ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsTetra4(), and ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsTria3().
_assembleBilinearOperator()
void FemModuleElastodynamics::_assembleBilinearOperator () private
Definition at line 452 of file elastodynamics/FemModule.cc.
_assembleBilinearOperatorCpu()
template<int N> void FemModuleElastodynamics::_assembleBilinearOperatorCpu (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the FEM bilinear operator on CPU.
This method assembles the FEM stiffness matrix by iterating over each cell, computing the element stiffness matrix using the provided function, and populating the global stiffness matrix accordingly.
Template Parameters
N Total DOF size (nodes_per_element × dimensions).
Parameters
compute_element_matrix function computing cell's element stiffness matrix.
Definition at line 418 of file elastodynamics/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleBilinearOperatorTetra4Gpu()
void FemModuleElastodynamics::_assembleBilinearOperatorTetra4Gpu ()
Definition at line 386 of file elastodynamics/FemModule.cc.
_assembleBilinearOperatorTria3Gpu()
void FemModuleElastodynamics::_assembleBilinearOperatorTria3Gpu ()
Definition at line 365 of file elastodynamics/FemModule.cc.
_assembleDirichletsGpu()
void FemModuleElastodynamics::_assembleDirichletsGpu ()
Applies dirichlet to LHS matrix and RHS vector of the linear system on Gpu.
This function applies Dirichlet boundary conditions to both the LHS matrix and RHS vector of the linear system using GPU acceleration.
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 80 of file elastodynamics/Dirichlet.h.
Referenced by _applyDirichlet().
_assembleLinearOperator()
void FemModuleElastodynamics::_assembleLinearOperator () private
Definition at line 338 of file elastodynamics/FemModule.cc.
_computeElementMatrixHexa8()
RealMatrix< 24, 24 > FemModuleElastodynamics::_computeElementMatrixHexa8 (Cell cell) private
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫∫ [(∂²𝐮/∂𝑡²).(𝐯)] dΩ + ∫∫∫ [σ(𝐮):ε(𝐯)] dΩ
with trial function 𝐮 = (𝑢𝑥, 𝑢𝑦, 𝑢𝑧) and test function 𝐯 = (𝑣𝑥, 𝑣𝑦, 𝑣𝑧), σ(𝐮) is the stress tensor, given by σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is the strain tensor, defined as εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
The bilinear integral after applying the Newmark-Beta scheme and damping terms expands to:
a(𝐮,𝐯) = ∫∫∫ (c₀)(𝐮 ⋅ 𝐯) dΩ
∫∫∫ (c₁) (∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑦/∂𝑦)
∫∫∫ (c₂)(2(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧) + (∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥) + (∂𝑢𝑧/∂𝑦 + ∂𝑢𝑦/∂𝑧)(∂𝑣𝑦/∂𝑧 + ∂𝑣𝑧/∂𝑦) + (∂𝑢𝑥/∂𝑧 + ∂𝑢𝑧/∂𝑥)(∂𝑣𝑧/∂𝑥 + ∂𝑣𝑥/∂𝑧))
with c₀ = (ρ)/(β δ𝑡²) + (ηₘ ρ γ)/(β δ𝑡) c₁ = λ + (λ ηₖ γ)/(β δ𝑡) c₂ = 2μ + (2μ ηₖ γ)/(β δ𝑡)
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianHexa8
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 125 of file elastodynamics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), ArcaneFemFunctions::FeOperation3D::computeShapeFunctionsHexa8(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
_computeElementMatrixQuad4()
RealMatrix< 8, 8 > FemModuleElastodynamics::_computeElementMatrixQuad4 (Cell cell) private
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
Theory: a(𝐮,𝐯) = ∫∫ [(∂²𝐮/∂𝑡²).(𝐯)]dΩ + ∫∫ [σ(𝐮):ε(𝐯)]dΩ
with trial func 𝐮 = (𝑢𝑥,𝑢𝑦) and test func 𝐯 = (𝑣𝑥,𝑣𝑦), σ(𝐮) is stress tensor with σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is strain tensor with εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
the bilinear integral after Newmark-Beta and damping terms expands to:
a(𝐮,𝐯) = ∫∫ (c₀)(𝐮.𝐯)
∫∫ (c₁)(∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦)
∫∫ (c₁+2c₂)(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦)
∫∫ (c₂)(∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥)
with c₀ = (ρ)/(β δ𝑡²) + (ηₘ ρ γ)/(β δ𝑡) c₁ = λ + (λ ηₖ γ)/(β δ𝑡) c₂ = 2μ + (2μ ηₖ γ)/(β δ𝑡)
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 49 of file elastodynamics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), ArcaneFemFunctions::FeOperation2D::computeShapeFunctionsQuad4(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
_computeElementMatrixTetra4()
RealMatrix< 12, 12 > FemModuleElastodynamics::_computeElementMatrixTetra4 (Cell cell) private
Computes the element matrix for a tetrahedral element (ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫∫ [(∂²𝐮/∂𝑡²).(𝐯)] dΩ + ∫∫∫ [σ(𝐮):ε(𝐯)] dΩ
with trial function 𝐮 = (𝑢𝑥, 𝑢𝑦, 𝑢𝑧) and test function 𝐯 = (𝑣𝑥, 𝑣𝑦, 𝑣𝑧), σ(𝐮) is the stress tensor, given by σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is the strain tensor, defined as εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
The bilinear integral after applying the Newmark-Beta scheme and damping terms expands to:
a(𝐮,𝐯) = ∫∫∫ (c₀)(𝐮 ⋅ 𝐯) dΩ
∫∫∫ (c₁) (∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑧/∂𝑧 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑦/∂𝑦)
∫∫∫ (c₂)(2(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦 + ∂𝑢𝑧/∂𝑧 ∂𝑣𝑧/∂𝑧) + (∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥) + (∂𝑢𝑧/∂𝑦 + ∂𝑢𝑦/∂𝑧)(∂𝑣𝑦/∂𝑧 + ∂𝑣𝑧/∂𝑦) + (∂𝑢𝑥/∂𝑧 + ∂𝑢𝑧/∂𝑥)(∂𝑣𝑧/∂𝑥 + ∂𝑣𝑥/∂𝑧))
with c₀ = (ρ)/(β δ𝑡²) + (ηₘ ρ γ)/(β δ𝑡) c₁ = λ + (λ ηₖ γ)/(β δ𝑡) c₂ = 2μ + (2μ ηₖ γ)/(β δ𝑡)
Definition at line 161 of file elastodynamics/ElementMatrix.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
_computeElementMatrixTria3()
RealMatrix< 6, 6 > FemModuleElastodynamics::_computeElementMatrixTria3 (Cell cell) private
Computes the element matrix for a triangular element (ℙ1 FE).
Theory:
a(𝐮,𝐯) = ∫∫ [(∂²𝐮/∂𝑡²).(𝐯)]dΩ + ∫∫ [σ(𝐮):ε(𝐯)]dΩ
with trial func 𝐮 = (𝑢𝑥,𝑢𝑦) and test func 𝐯 = (𝑣𝑥,𝑣𝑦), σ(𝐮) is stress tensor with σᵢⱼ = λδᵢⱼεₖₖ + 2μεᵢⱼ ε(𝐯) is strain tensor with εᵢⱼ = 0.5 (∂𝑣ᵢ/∂xⱼ + ∂𝑣ⱼ/∂xᵢ)
the bilinear integral after Newmark-Beta and damping terms expands to:
a(𝐮,𝐯) = ∫∫ (c₀)(𝐮.𝐯)
∫∫ (c₁)(∂𝑢𝑦/∂𝑦 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑦)
∫∫ (c₁+2c₂)(∂𝑢𝑥/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑢𝑦/∂𝑦 ∂𝑣𝑦/∂𝑦)
∫∫ (c₂)(∂𝑢𝑦/∂𝑥 + ∂𝑢𝑥/∂𝑦)(∂𝑣𝑥/∂𝑦 + ∂𝑣𝑦/∂𝑥)
with c₀ = (ρ)/(β δ𝑡²) + (ηₘ ρ γ)/(β δ𝑡) c₁ = λ + (λ ηₖ γ)/(β δ𝑡) c₂ = 2μ + (2μ ηₖ γ)/(β δ𝑡)
Definition at line 40 of file elastodynamics/ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
_doStationarySolve()
void FemModuleElastodynamics::_doStationarySolve () private
Definition at line 120 of file elastodynamics/FemModule.cc.
_getParameters()
void FemModuleElastodynamics::_getParameters () private
Definition at line 143 of file elastodynamics/FemModule.cc.
_readCaseTables()
void FemModuleElastodynamics::_readCaseTables () private
Definition at line 251 of file elastodynamics/FemModule.cc.
_solve()
void FemModuleElastodynamics::_solve () private
Definition at line 497 of file elastodynamics/FemModule.cc.
_updateTime()
void FemModuleElastodynamics::_updateTime () private
Definition at line 111 of file elastodynamics/FemModule.cc.
_updateVariables()
void FemModuleElastodynamics::_updateVariables () private
Definition at line 271 of file elastodynamics/FemModule.cc.
_validateResults()
void FemModuleElastodynamics::_validateResults () private
Definition at line 512 of file elastodynamics/FemModule.cc.
compute()
void FemModuleElastodynamics::compute () override
Method called at the beginning of the simulation.
Definition at line 69 of file elastodynamics/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::clearValues(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), Arcane::FemUtils::DoFLinearSystem::isInitialized(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleElastodynamics::startInit () override
Initializes the FemModuleElastodynamics at the start of the simulation.
This method initializes degrees of freedom (DoFs) on nodes.
Definition at line 29 of file elastodynamics/FemModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleElastodynamics::versionInfo () const inline override
Method called at each iteration.
Definition at line 73 of file elastodynamics/FemModule.h.
Member Data Documentation
alpf
Real FemModuleElastodynamics::alpf private
Definition at line 85 of file elastodynamics/FemModule.h.
alpm
Real FemModuleElastodynamics::alpm private
Definition at line 84 of file elastodynamics/FemModule.h.
beta
Real FemModuleElastodynamics::beta private
Definition at line 86 of file elastodynamics/FemModule.h.
c0
Real FemModuleElastodynamics::c0 private
Definition at line 100 of file elastodynamics/FemModule.h.
c1
Real FemModuleElastodynamics::c1 private
Definition at line 101 of file elastodynamics/FemModule.h.
c10
Real FemModuleElastodynamics::c10 private
Definition at line 110 of file elastodynamics/FemModule.h.
c2
Real FemModuleElastodynamics::c2 private
Definition at line 102 of file elastodynamics/FemModule.h.
c3
Real FemModuleElastodynamics::c3 private
Definition at line 103 of file elastodynamics/FemModule.h.
c4
Real FemModuleElastodynamics::c4 private
Definition at line 104 of file elastodynamics/FemModule.h.
c5
Real FemModuleElastodynamics::c5 private
Definition at line 105 of file elastodynamics/FemModule.h.
c6
Real FemModuleElastodynamics::c6 private
Definition at line 106 of file elastodynamics/FemModule.h.
c7
Real FemModuleElastodynamics::c7 private
Definition at line 107 of file elastodynamics/FemModule.h.
c8
Real FemModuleElastodynamics::c8 private
Definition at line 108 of file elastodynamics/FemModule.h.
c9
Real FemModuleElastodynamics::c9 private
Definition at line 109 of file elastodynamics/FemModule.h.
dt
Real FemModuleElastodynamics::dt private
Definition at line 82 of file elastodynamics/FemModule.h.
E
Real FemModuleElastodynamics::E private
Definition at line 92 of file elastodynamics/FemModule.h.
etak
Real FemModuleElastodynamics::etak private
Definition at line 90 of file elastodynamics/FemModule.h.
etam
Real FemModuleElastodynamics::etam private
Definition at line 89 of file elastodynamics/FemModule.h.
f
Real3 FemModuleElastodynamics::f = {0,0,0} private
Definition at line 98 of file elastodynamics/FemModule.h.
gamma
Real FemModuleElastodynamics::gamma private
Definition at line 87 of file elastodynamics/FemModule.h.
lambda
Real FemModuleElastodynamics::lambda private
Definition at line 96 of file elastodynamics/FemModule.h.
m_assemble_linear_system
bool FemModuleElastodynamics::m_assemble_linear_system = true private
Definition at line 115 of file elastodynamics/FemModule.h.
m_bsr_format
BSRFormat FemModuleElastodynamics::m_bsr_format private
Definition at line 122 of file elastodynamics/FemModule.h.
m_cross_validation
bool FemModuleElastodynamics::m_cross_validation = false private
Definition at line 117 of file elastodynamics/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleElastodynamics::m_dofs_on_nodes private
Definition at line 121 of file elastodynamics/FemModule.h.
m_hex_quad_mesh
bool FemModuleElastodynamics::m_hex_quad_mesh = false private
Definition at line 118 of file elastodynamics/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleElastodynamics::m_linear_system private
Definition at line 120 of file elastodynamics/FemModule.h.
m_matrix_format
String FemModuleElastodynamics::m_matrix_format = "DOK" private
Definition at line 113 of file elastodynamics/FemModule.h.
m_petsc_flags
String FemModuleElastodynamics::m_petsc_flags private
Definition at line 112 of file elastodynamics/FemModule.h.
m_solve_linear_system
bool FemModuleElastodynamics::m_solve_linear_system = true private
Definition at line 116 of file elastodynamics/FemModule.h.
m_traction_case_table_list
UniqueArray<CaseTableInfo> FemModuleElastodynamics::m_traction_case_table_list private
Definition at line 125 of file elastodynamics/FemModule.h.
mu
Real FemModuleElastodynamics::mu private
Definition at line 95 of file elastodynamics/FemModule.h.
nu
Real FemModuleElastodynamics::nu private
Definition at line 93 of file elastodynamics/FemModule.h.
rho
Real FemModuleElastodynamics::rho private
Definition at line 94 of file elastodynamics/FemModule.h.
t
Real FemModuleElastodynamics::t private
Definition at line 81 of file elastodynamics/FemModule.h.
tmax
Real FemModuleElastodynamics::tmax private
Definition at line 83 of file elastodynamics/FemModule.h.
The documentation for this class was generated from the following files:
elastodynamics/FemModule.h
elastodynamics/Dirichlet.h
elastodynamics/ElementMatrix.h
elastodynamics/ElementMatrixHexQuad.h
elastodynamics/FemModule.cc
elastodynamics/SourceTerm.h
elastodynamics/Traction.h