ArcaneFem: FemModuleElectrostatics Class Reference
FemModuleElectrostatics Class Reference
Module Fem.
#include <modules/electrostatics/FemModule.h>
Public Member Functions
FemModuleElectrostatics (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleElectrostatics at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
void _assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
void _assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
Private Member Functions
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _getMaterialParameters ()
Retrieves and sets the material parameters for the simulation.
void _assembleLinearOperatorCpu ()
FEM linear operator for the current simulation step.
void _solve ()
Solves the linear system and updates the solution vector.
void _assembleLinearOperator ()
Assembles the FEM linear operator for the current simulation step.
void _updateVariables ()
Update the FEM variables.
void _validateResults ()
Validates and prints the results of the FEM computation.
RealMatrix< 3, 3 > _computeElementMatrixTria3 (Cell cell)
Computes the element matrix for a triangular element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixTetra4 (Cell cell)
Computes the element matrix for a tetrahedral element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixQuad4 (Cell cell)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
RealMatrix< 8, 8 > _computeElementMatrixHexa8 (Cell cell)
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
template<int N>
void _assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the bilinear operator matrix for the FEM linear system.
Private Attributes
Real rho
Real epsilon
DoFLinearSystem m_linear_system
IItemFamily * m_dof_family = nullptr
FemDoFsOnNodes m_dofs_on_nodes
BSRFormat m_bsr_format
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_hex_quad_mesh = false
Detailed Description
Module Fem.
Definition at line 52 of file electrostatics/FemModule.h.
Constructor & Destructor Documentation
FemModuleElectrostatics()
FemModuleElectrostatics::FemModuleElectrostatics (const ModuleBuildInfo & mbi) inline explicit
Definition at line 57 of file electrostatics/FemModule.h.
Member Function Documentation
_assembleBilinear()
template<int N> void FemModuleElectrostatics::_assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the bilinear operator matrix for the FEM linear system.
The method performs the following steps:
For each cell, retrieves the cell-specific constant lambda.
Computes element matrix using provided compute_element_matrix function.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 368 of file electrostatics/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleBilinearOperator()
void FemModuleElectrostatics::_assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
Definition at line 302 of file electrostatics/FemModule.cc.
References _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), _computeElementMatrixTria3(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_assembleLinearOperator()
void FemModuleElectrostatics::_assembleLinearOperator () private
Assembles the FEM linear operator for the current simulation step.
This method constructs the right-hand side (RHS) vector by calling then appropriate assembly function based on the execution context:
CPU-exclusive execution: Calls _assembleLinearOperatorCpu().
CPU or GPU execution: Calls _assembleLinearOperatorGpu().
Definition at line 158 of file electrostatics/FemModule.cc.
References _assembleLinearOperatorCpu(), and _assembleLinearOperatorGpu().
Referenced by _doStationarySolve().
_assembleLinearOperatorCpu()
void FemModuleElectrostatics::_assembleLinearOperatorCpu () private
FEM linear operator for the current simulation step.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If a constant source term is specified (rho), apply it to the RHS.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC are specified apply to the LHS & RHS.
Definition at line 182 of file electrostatics/FemModule.cc.
References ArcaneFemFunctions::BoundaryConditions3D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _assembleLinearOperator().
_assembleLinearOperatorGpu()
void FemModuleElectrostatics::_assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC/Point are specified apply to the LHS & RHS.
Definition at line 254 of file electrostatics/FemModule.cc.
References Arcane::FemUtils::Gpu::BoundaryConditions::applyDirichletToLhsAndRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _assembleLinearOperator().
_computeElementMatrixHexa8()
RealMatrix< 8, 8 > FemModuleElectrostatics::_computeElementMatrixHexa8 (Cell cell) private
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Define Gauss points (2x2x2) and weights.
Loop over Gauss points to compute the gradients in physical space (𝑥,𝑦,𝑧) and the determinant of the Jacobian via computeGradientsAndJacobianHexa8.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 86 of file electrostatics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixQuad4()
RealMatrix< 4, 4 > FemModuleElectrostatics::_computeElementMatrixQuad4 (Cell cell) private
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 33 of file electrostatics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTetra4()
RealMatrix< 4, 4 > FemModuleElectrostatics::_computeElementMatrixTetra4 (Cell cell) private
Computes the element matrix for a tetrahedral element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 79 of file electrostatics/ElementMatrix.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTria3()
RealMatrix< 3, 3 > FemModuleElectrostatics::_computeElementMatrixTria3 (Cell cell) private
Computes the element matrix for a triangular element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 28 of file electrostatics/ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
Referenced by _assembleBilinearOperator().
_doStationarySolve()
void FemModuleElectrostatics::_doStationarySolve () private
Performs a stationary solve for the FEM system.
This method follows via the following steps:
_assembleBilinearOperator() Assembles the FEM matrix 𝐀
_assembleLinearOperator() Assembles the FEM RHS vector 𝐛
_solve() Solves for solution vector 𝐮 = 𝐀⁻¹𝐛
_updateVariables() Updates FEM variables 𝐮 = 𝐱
_validateResults() Regression test
Definition at line 106 of file electrostatics/FemModule.cc.
References _assembleBilinearOperator(), _assembleLinearOperator(), _getMaterialParameters(), _solve(), _updateVariables(), and _validateResults().
Referenced by compute().
_getMaterialParameters()
void FemModuleElectrostatics::_getMaterialParameters () private
Retrieves and sets the material parameters for the simulation.
This method initializes material properties:
charge density (rho)
free space permittivity (epsilon)
Definition at line 133 of file electrostatics/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_solve()
void FemModuleElectrostatics::_solve () private
Solves the linear system and updates the solution vector.
This method performs the following actions:
Solves the linear system to compute the solution.
Copies the computed solution from the DoF to the node values.
Synchronizes the updated node values.
Definition at line 403 of file electrostatics/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updateVariables()
void FemModuleElectrostatics::_updateVariables () private
Update the FEM variables.
This method performs the following actions:
Fetches values of solution from solved linear system to FEM variables, i.e., it copies RHS DOF to u.
Performs synchronize of FEM variables across subdomains.
Definition at line 426 of file electrostatics/FemModule.cc.
References ArcaneFemFunctions::FeOperation3D::computeGradientHexa8(), ArcaneFemFunctions::FeOperation2D::computeGradientQuad4(), ArcaneFemFunctions::FeOperation2D::computeGradientTria3(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_validateResults()
void FemModuleElectrostatics::_validateResults () private
Validates and prints the results of the FEM computation.
This method performs the following actions:
If number of nodes < 200, prints the computed values for each node.
Retrieves the filename for the result file from options.
If a filename is provided, checks the computed results against result file.
Note
The result comparison uses a tolerance of 1.0e-4.
Definition at line 492 of file electrostatics/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
compute()
void FemModuleElectrostatics::compute () override
Method called at the beginning of the simulation.
Performs the main computation for the FemModuleElectrostatics.
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Executes the stationary solve.
Definition at line 56 of file electrostatics/FemModule.cc.
References _doStationarySolve(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleElectrostatics::startInit () override
Initializes the FemModuleElectrostatics at the start of the simulation.
initializes degrees of freedom (DoFs) on nodes.
builds support for manufactured test case (optional).
Definition at line 26 of file electrostatics/FemModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleElectrostatics::versionInfo () const inline override
Method called at each iteration.
Definition at line 71 of file electrostatics/FemModule.h.
Member Data Documentation
epsilon
Real FemModuleElectrostatics::epsilon private
Definition at line 79 of file electrostatics/FemModule.h.
m_assemble_linear_system
bool FemModuleElectrostatics::m_assemble_linear_system = true private
Definition at line 89 of file electrostatics/FemModule.h.
m_bsr_format
BSRFormat FemModuleElectrostatics::m_bsr_format private
Definition at line 84 of file electrostatics/FemModule.h.
m_cross_validation
bool FemModuleElectrostatics::m_cross_validation = false private
Definition at line 91 of file electrostatics/FemModule.h.
m_dof_family
IItemFamily* FemModuleElectrostatics::m_dof_family = nullptr private
Definition at line 82 of file electrostatics/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleElectrostatics::m_dofs_on_nodes private
Definition at line 83 of file electrostatics/FemModule.h.
m_hex_quad_mesh
bool FemModuleElectrostatics::m_hex_quad_mesh = false private
Definition at line 92 of file electrostatics/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleElectrostatics::m_linear_system private
Definition at line 81 of file electrostatics/FemModule.h.
m_matrix_format
String FemModuleElectrostatics::m_matrix_format = "DOK" private
Definition at line 87 of file electrostatics/FemModule.h.
m_petsc_flags
String FemModuleElectrostatics::m_petsc_flags private
Definition at line 86 of file electrostatics/FemModule.h.
m_solve_linear_system
bool FemModuleElectrostatics::m_solve_linear_system = true private
Definition at line 90 of file electrostatics/FemModule.h.
rho
Real FemModuleElectrostatics::rho private
Definition at line 78 of file electrostatics/FemModule.h.
The documentation for this class was generated from the following files:
electrostatics/FemModule.h
electrostatics/ElementMatrix.h
electrostatics/ElementMatrixHexQuad.h
electrostatics/FemModule.cc