ArcaneFem: FemModuleFourierNL Class Reference
FemModuleFourierNL Class Reference
A module for finite element method.
#include <modules/fouriernl/FemModule.h>
Public Member Functions
FemModuleFourierNL (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleFourierNL at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
void _assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
void _assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
Private Member Functions
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _solve ()
Solves the linear system and updates the solution vector.
void _assembleLinearOperator ()
void _assembleLinearOperatorCpu ()
FEM linear operator for the current simulation step.
void _validateResults ()
Validates and prints the results of the FEM computation.
void _updateVariables (bool verbose=false)
Update the FEM variables.
void _updatePreviousIterationVariables (bool verbose=false)
Update the previous fixed-point iteration FEM variables.
void _updateSolutionFromVariables ()
Reinitialize the solution vector of the linear solve with the FEM variables.
void _checkConvergence ()
Check for convergence and Update the FEM variables.
void _updateExactSolution (bool verbose=false)
Updates the exact solution in the FEM variable m_exact.
void _checkSolution ()
Validates and prints the results of the FEM computation.
RealMatrix< 3, 3 > _computeElementMatrixTria3 (Cell cell)
Computes the element matrix for a triangular element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixTetra4 (Cell cell)
Computes the element matrix for a tetrahedral element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixQuad4 (Cell cell)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
RealMatrix< 8, 8 > _computeElementMatrixHexa8 (Cell cell)
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
Real _lambdaCpu (const Real &u)
Computes inline conduction coefficient for CPU.
template<int N>
void _assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the bilinear operator matrix for the FEM linear system.
Private Attributes
Real m_qdot
Real ElementNodes
Real m_fp_tol {1e-5}
Int32 m_max_fp_iters {15}
Int32 m_fp_iter {0}
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_check_solution = true
bool m_hex_quad_mesh = false
bool m_perform_fixed_point_iters = false
bool m_converged = false
DoFLinearSystem m_linear_system
IItemFamily * m_dof_family = nullptr
FemDoFsOnNodes m_dofs_on_nodes
BSRFormat m_bsr_format
Detailed Description
A module for finite element method.
This class handles the initialization and computation for finite element method (FEM) simulations, providing methods to set up and solve linear systems, assemble FEM operators, and perform result checks.
Definition at line 59 of file fouriernl/FemModule.h.
Constructor & Destructor Documentation
FemModuleFourierNL()
FemModuleFourierNL::FemModuleFourierNL (const ModuleBuildInfo & mbi) inline explicit
Definition at line 64 of file fouriernl/FemModule.h.
Member Function Documentation
_assembleBilinear()
template<int N> void FemModuleFourierNL::_assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the bilinear operator matrix for the FEM linear system.
The method performs the following steps:
Computes element matrix using provided compute_element_matrix function.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 382 of file fouriernl/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleBilinearOperator()
void FemModuleFourierNL::_assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
Definition at line 326 of file fouriernl/FemModule.cc.
References _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), _computeElementMatrixTria3(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_assembleLinearOperator()
void FemModuleFourierNL::_assembleLinearOperator () private
Definition at line 175 of file fouriernl/FemModule.cc.
_assembleLinearOperatorCpu()
void FemModuleFourierNL::_assembleLinearOperatorCpu () private
FEM linear operator for the current simulation step.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If a constant source term is specified (qdot), apply it to the RHS.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC are specified apply to the LHS & RHS.
Definition at line 200 of file fouriernl/FemModule.cc.
References ArcaneFemFunctions::BoundaryConditions3D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyConstantSourceToRhs(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
_assembleLinearOperatorGpu()
void FemModuleFourierNL::_assembleLinearOperatorGpu ()
FEM linear operator for the current simulation step. GPU compatible. Currently working with HypreDoFLinearSystem.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC/Point are specified apply to the LHS & RHS.
Definition at line 280 of file fouriernl/FemModule.cc.
References Arcane::FemUtils::Gpu::BoundaryConditions::applyDirichletToLhsAndRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
_checkConvergence()
void FemModuleFourierNL::_checkConvergence () private
Check for convergence and Update the FEM variables.
This method performs the following actions:
Updates the FEM solutions from the solutions of linear solver on DOF
Evaluates the error w.r.t the guess FEM variables using max norm
Checks for convergence
Updates guess or ends fixed point iterations
Definition at line 441 of file fouriernl/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_checkSolution()
void FemModuleFourierNL::_checkSolution () private
Validates and prints the results of the FEM computation.
This method performs the following actions:
Checks and prints the infinity norm of difference between the resulting solution and the analytical solution
Note
The result comparison uses a tolerance of 1.0e-4.
Definition at line 668 of file fouriernl/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_computeElementMatrixHexa8()
RealMatrix< 8, 8 > FemModuleFourierNL::_computeElementMatrixHexa8 (Cell cell) private
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫∫ λ(𝑢)(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Define Gauss points (2x2x2) and weights.
Loop over Gauss points to compute the gradients in physical space (𝑥,𝑦,𝑧) and the determinant of the Jacobian via computeGradientsAndJacobianHexa8.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 93 of file fouriernl/ElementMatrixHexQuad.h.
References _lambdaCpu(), ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), ArcaneFemFunctions::FeOperation3D::computeShapeFunctionsHexa8(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixQuad4()
RealMatrix< 4, 4 > FemModuleFourierNL::_computeElementMatrixQuad4 (Cell cell) private
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫ λ(𝑢)(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 34 of file fouriernl/ElementMatrixHexQuad.h.
References _lambdaCpu(), ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), ArcaneFemFunctions::FeOperation2D::computeShapeFunctionsQuad4(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTetra4()
RealMatrix< 4, 4 > FemModuleFourierNL::_computeElementMatrixTetra4 (Cell cell) private
Computes the element matrix for a tetrahedral element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫∫ λ(𝑢)(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 82 of file fouriernl/ElementMatrix.h.
References _lambdaCpu(), ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTria3()
RealMatrix< 3, 3 > FemModuleFourierNL::_computeElementMatrixTria3 (Cell cell) private
Computes the element matrix for a triangular element (ℙ1 FE).
This function calculates the expression: 𝑎(𝑢,𝑣) = ∫∫ λ(𝑢)(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 29 of file fouriernl/ElementMatrix.h.
References _lambdaCpu(), ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
Referenced by _assembleBilinearOperator().
_doStationarySolve()
void FemModuleFourierNL::_doStationarySolve () private
Performs a stationary solve for the FEM system.
This method follows via the following steps:
_getMaterialParameters() Retrieves material parameters
_assembleBilinearOperator() Assembles the FEM matrix 𝐀
_assembleLinearOperator() Assembles the FEM RHS vector 𝐛
_solve() Solves for solution vector 𝐮 = 𝐀⁻¹𝐛
_updateVariables() Updates FEM variables 𝐮 = 𝐱
_validateResults() Regression test
Definition at line 119 of file fouriernl/FemModule.cc.
References _assembleBilinearOperator(), _checkConvergence(), _checkSolution(), _solve(), _updateExactSolution(), _updatePreviousIterationVariables(), _updateSolutionFromVariables(), _updateVariables(), _validateResults(), Arcane::FemUtils::DoFLinearSystem::clearValues(), and Arcane::FemUtils::DoFLinearSystem::isInitialized().
Referenced by compute().
_lambdaCpu()
Real FemModuleFourierNL::_lambdaCpu (const Real & u) inline private
Computes inline conduction coefficient for CPU.
This function calculates the expression: λ(𝑢)= LAMBDA_CONDUCTION_COEFFICIENT
Steps involved:
Calculate the inline conduction coefficient.
Return λ(𝑢);
Definition at line 31 of file ConductivityCoefficient.h.
Referenced by _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), and _computeElementMatrixTria3().
_solve()
void FemModuleFourierNL::_solve () private
Solves the linear system and updates the solution vector.
This method performs the following actions:
Solves the linear system to compute the solution.
Copies the computed solution from the DoF to the node values.
Synchronizes the updated node values.
Definition at line 417 of file fouriernl/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updateExactSolution()
void FemModuleFourierNL::_updateExactSolution (bool verbose = false) private
Updates the exact solution in the FEM variable m_exact.
This method performs the following actions:
Updates the exact solution.
Performs synchronize of the FEM variable across subdomains.
Definition at line 634 of file fouriernl/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updatePreviousIterationVariables()
void FemModuleFourierNL::_updatePreviousIterationVariables (bool verbose = false) private
Update the previous fixed-point iteration FEM variables.
This method performs the following actions:
Fetches values of linear solution vector to the previous fixed-point iteration FEM variable, i.e., it copies RHS DOF to uk.
Performs synchronize of the previous fixed-point iteration FEM variable across subdomains.
Definition at line 531 of file fouriernl/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_updateSolutionFromVariables()
void FemModuleFourierNL::_updateSolutionFromVariables () private
Reinitialize the solution vector of the linear solve with the FEM variables.
This method performs the following actions:
Performs synchronize of FEM variables across subdomains.
Fetches the FEM variables to the solution vector of the linear solver for next fixed point iteration.
Definition at line 566 of file fouriernl/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_updateVariables()
void FemModuleFourierNL::_updateVariables (bool verbose = false) private
Update the FEM variables.
This method performs the following actions:
Fetches values of the solution from solved linear system to FEM variables, i.e., it copies RHS DOF to u.
Performs synchronize of FEM variables across subdomains.
Definition at line 492 of file fouriernl/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_validateResults()
void FemModuleFourierNL::_validateResults () private
Validates and prints the results of the FEM computation.
This method performs the following actions:
If number of nodes < 200, prints the computed values for each node.
Retrieves the filename for the result file from options.
If a filename is provided, checks the computed results against result file.
Note
The result comparison uses a tolerance of 1.0e-4.
Definition at line 603 of file fouriernl/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
compute()
void FemModuleFourierNL::compute () override
Method called at the beginning of the simulation.
Performs the main computation for the FemModuleFourierNL.
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Executes the stationary solve.
Definition at line 68 of file fouriernl/FemModule.cc.
References _doStationarySolve(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleFourierNL::startInit () override
Initializes the FemModuleFourierNL at the start of the simulation.
initializes degrees of freedom (DoFs) on nodes.
Definition at line 28 of file fouriernl/FemModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleFourierNL::versionInfo () const inline override
Method called at each iteration.
Definition at line 76 of file fouriernl/FemModule.h.
Member Data Documentation
ElementNodes
Real FemModuleFourierNL::ElementNodes private
Definition at line 84 of file fouriernl/FemModule.h.
m_assemble_linear_system
bool FemModuleFourierNL::m_assemble_linear_system = true private
Definition at line 92 of file fouriernl/FemModule.h.
m_bsr_format
BSRFormat FemModuleFourierNL::m_bsr_format private
Definition at line 103 of file fouriernl/FemModule.h.
m_check_solution
bool FemModuleFourierNL::m_check_solution = true private
Definition at line 95 of file fouriernl/FemModule.h.
m_converged
bool FemModuleFourierNL::m_converged = false private
Definition at line 98 of file fouriernl/FemModule.h.
m_cross_validation
bool FemModuleFourierNL::m_cross_validation = false private
Definition at line 94 of file fouriernl/FemModule.h.
m_dof_family
IItemFamily* FemModuleFourierNL::m_dof_family = nullptr private
Definition at line 101 of file fouriernl/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleFourierNL::m_dofs_on_nodes private
Definition at line 102 of file fouriernl/FemModule.h.
m_fp_iter
Int32 FemModuleFourierNL::m_fp_iter {0} private
Definition at line 87 of file fouriernl/FemModule.h.
m_fp_tol
Real FemModuleFourierNL::m_fp_tol {1e-5} private
Definition at line 85 of file fouriernl/FemModule.h.
m_hex_quad_mesh
bool FemModuleFourierNL::m_hex_quad_mesh = false private
Definition at line 96 of file fouriernl/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleFourierNL::m_linear_system private
Definition at line 100 of file fouriernl/FemModule.h.
m_matrix_format
String FemModuleFourierNL::m_matrix_format = "DOK" private
Definition at line 90 of file fouriernl/FemModule.h.
m_max_fp_iters
Int32 FemModuleFourierNL::m_max_fp_iters {15} private
Definition at line 87 of file fouriernl/FemModule.h.
m_perform_fixed_point_iters
bool FemModuleFourierNL::m_perform_fixed_point_iters = false private
Definition at line 97 of file fouriernl/FemModule.h.
m_petsc_flags
String FemModuleFourierNL::m_petsc_flags private
Definition at line 89 of file fouriernl/FemModule.h.
m_qdot
Real FemModuleFourierNL::m_qdot private
Definition at line 83 of file fouriernl/FemModule.h.
m_solve_linear_system
bool FemModuleFourierNL::m_solve_linear_system = true private
Definition at line 93 of file fouriernl/FemModule.h.
The documentation for this class was generated from the following files:
fouriernl/FemModule.h
ConductivityCoefficient.h
fouriernl/ElementMatrix.h
fouriernl/ElementMatrixHexQuad.h
fouriernl/FemModule.cc