ArcaneFem: Arcane::FemUtils::CsrFormatMatrixView Class Reference
Arcane::FemUtils::CsrFormatMatrixView Class Reference
View of a Matrix with CSR format.
#include <femutils/CsrFormatMatrixView.h>
Public Member Functions
constexpr __host__ __device__ Span< const Int32 > rows () const
constexpr __host__ __device__ Span< const Int32 > rowsNbColumn () const
constexpr __host__ __device__ Span< const Int32 > columns () const
constexpr __host__ __device__ Span< Real > values () const
constexpr __host__ __device__ Int32 nbRow () const
Number of the rows in the matrix.
constexpr __host__ __device__ Int32 nbColumn () const
Number of the values in the matrix.
constexpr __host__ __device__ Int32 nbValue () const
Number of the values in the matrix.
constexpr __host__ __device__ Int32 row (Int32 index) const
constexpr __host__ __device__ Int32 column (CsrRowColumnIndex rc_index) const
Local index of the column for the given RowColumnIndex rc_index.
constexpr __host__ __device__ Real & value (CsrRowColumnIndex rc_index) const
Value of the matrix for the given RowColumnIndex rc_index.
constexpr __host__ __device__ CsrRow rowRange (Int32 row) const
Range of CsrRowColumnIndex for the given row row.
constexpr __host__ __device__ CsrRowColumnIndex tryFindColumnInRow (Int32 row, Int32 column_id) const
Try to find a column in a row.
Private Member Functions
CsrFormatMatrixView (SmallSpan< const Int32 > rows, SmallSpan< const Int32 > matrix_rows_nb_column, SmallSpan< const Int32 > columns, SmallSpan< Real > values)
Private Attributes
friend CsrFormat
SmallSpan< const Int32 > m_matrix_rows
SmallSpan< const Int32 > m_matrix_rows_nb_column
SmallSpan< const Int32 > m_matrix_columns
SmallSpan< Real > m_values
Detailed Description
View of a Matrix with CSR format.
This view is a temporary object and is invalided when the underlying matrix structure is modified.
Definition at line 134 of file CsrFormatMatrixView.h.
Constructor & Destructor Documentation
CsrFormatMatrixView()
Arcane::FemUtils::CsrFormatMatrixView::CsrFormatMatrixView (SmallSpan< const Int32 > rows, SmallSpan< const Int32 > matrix_rows_nb_column, SmallSpan< const Int32 > columns, SmallSpan< Real > values) inline private
Definition at line 144 of file CsrFormatMatrixView.h.
Member Function Documentation
column()
constexpr __host__ __device__ Int32 Arcane::FemUtils::CsrFormatMatrixView::column (CsrRowColumnIndex rc_index) const inline constexpr
Local index of the column for the given RowColumnIndex rc_index.
Definition at line 171 of file CsrFormatMatrixView.h.
Referenced by tryFindColumnInRow().
columns()
constexpr __host__ __device__ Span< const Int32 > Arcane::FemUtils::CsrFormatMatrixView::columns () const inline constexpr
Definition at line 158 of file CsrFormatMatrixView.h.
nbColumn()
constexpr __host__ __device__ Int32 Arcane::FemUtils::CsrFormatMatrixView::nbColumn () const inline constexpr
Number of the values in the matrix.
Definition at line 164 of file CsrFormatMatrixView.h.
Referenced by rowRange().
nbRow()
constexpr __host__ __device__ Int32 Arcane::FemUtils::CsrFormatMatrixView::nbRow () const inline constexpr
Number of the rows in the matrix.
Definition at line 162 of file CsrFormatMatrixView.h.
Referenced by rowRange().
nbValue()
constexpr __host__ __device__ Int32 Arcane::FemUtils::CsrFormatMatrixView::nbValue () const inline constexpr
Number of the values in the matrix.
Definition at line 166 of file CsrFormatMatrixView.h.
row()
constexpr __host__ __device__ Int32 Arcane::FemUtils::CsrFormatMatrixView::row (Int32 index) const inline constexpr
Definition at line 168 of file CsrFormatMatrixView.h.
rowRange()
constexpr __host__ __device__ CsrRow Arcane::FemUtils::CsrFormatMatrixView::rowRange (Int32 row) const inline constexpr
Range of CsrRowColumnIndex for the given row row.
Definition at line 176 of file CsrFormatMatrixView.h.
References nbColumn(), and nbRow().
Referenced by tryFindColumnInRow().
rows()
constexpr __host__ __device__ Span< const Int32 > Arcane::FemUtils::CsrFormatMatrixView::rows () const inline constexpr
Definition at line 156 of file CsrFormatMatrixView.h.
rowsNbColumn()
constexpr __host__ __device__ Span< const Int32 > Arcane::FemUtils::CsrFormatMatrixView::rowsNbColumn () const inline constexpr
Definition at line 157 of file CsrFormatMatrixView.h.
tryFindColumnInRow()
constexpr __host__ __device__ CsrRowColumnIndex Arcane::FemUtils::CsrFormatMatrixView::tryFindColumnInRow (Int32 row, Int32 column_id) const inline constexpr
Try to find a column in a row.
Try to find the column column_id in the row row. If not found return a null index.
Definition at line 191 of file CsrFormatMatrixView.h.
References column(), and rowRange().
value()
constexpr __host__ __device__ Real & Arcane::FemUtils::CsrFormatMatrixView::value (CsrRowColumnIndex rc_index) const inline constexpr
Value of the matrix for the given RowColumnIndex rc_index.
Definition at line 173 of file CsrFormatMatrixView.h.
values()
constexpr __host__ __device__ Span< Real > Arcane::FemUtils::CsrFormatMatrixView::values () const inline constexpr
Definition at line 159 of file CsrFormatMatrixView.h.
Member Data Documentation
CsrFormat
friend Arcane::FemUtils::CsrFormatMatrixView::CsrFormat private
Definition at line 136 of file CsrFormatMatrixView.h.
m_matrix_columns
SmallSpan<const Int32> Arcane::FemUtils::CsrFormatMatrixView::m_matrix_columns private
Definition at line 203 of file CsrFormatMatrixView.h.
m_matrix_rows
SmallSpan<const Int32> Arcane::FemUtils::CsrFormatMatrixView::m_matrix_rows private
Definition at line 201 of file CsrFormatMatrixView.h.
m_matrix_rows_nb_column
SmallSpan<const Int32> Arcane::FemUtils::CsrFormatMatrixView::m_matrix_rows_nb_column private
Definition at line 202 of file CsrFormatMatrixView.h.
m_values
SmallSpan<Real> Arcane::FemUtils::CsrFormatMatrixView::m_values private
Definition at line 204 of file CsrFormatMatrixView.h.
The documentation for this class was generated from the following file:
CsrFormatMatrixView.h