ArcaneFem: ArcaneFemFunctions::FeOperation3D Class Reference
ArcaneFemFunctions::FeOperation3D Class Reference
Provides methods for finite element operations in 3D.
#include <femutils/ArcaneFemFunctions.h>
Classes
struct Hexa8GaussPointInfo
Holds information for a Hexa8 element at a single Gauss point.
Static Public Member Functions
static Real4 computeGradientXTetra4 (Cell cell, const VariableNodeReal3 &node_coord)
Computes the X gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
static Real4 computeGradientYTetra4 (Cell cell, const VariableNodeReal3 &node_coord)
Computes the Y gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
static Real4 computeGradientZTetra4 (Cell cell, const VariableNodeReal3 &node_coord)
Computes the 𝑧 gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
static Real3 computeGradientTetra4 (Cell cell, const VariableNodeReal3 &node_coord, VariableNodeReal u)
static Hexa8GaussPointInfo computeGradientsAndJacobianHexa8 (Cell cell, const VariableNodeReal3 &node_coord, Real xi, Real eta, Real zeta)
Computes shape function gradients and the Jacobian determinant for a Hexa8 element.
static Real3 computeGradientHexa8 (Cell cell, const VariableNodeReal3 &node_coord, const VariableNodeReal &u)
Computes the gradient of a scalar field 'u' for a Hexa8 element.
static RealVector< 8 > computeShapeFunctionsHexa8 (Real xi, Real eta, Real zeta)
Computes the shape functions for a Hexa8 element at a given point (ξ,η,ζ).
Detailed Description
Provides methods for finite element operations in 3D.
This class includes static methods for calculating gradients of basis functions and integrals for P1 triangles in 3D finite element analysis.
Reference Tetra4 element in Arcane
          3 o
           /|\
          / | \
         /  |  \
        /   o 2 \
       / .    .  \
    0 o-----------o 1
Definition at line 782 of file ArcaneFemFunctions.h.
Member Function Documentation
computeGradientHexa8()
static Real3 ArcaneFemFunctions::FeOperation3D::computeGradientHexa8 (Cell cell, const VariableNodeReal3 & node_coord, const VariableNodeReal & u) inline static
Computes the gradient of a scalar field 'u' for a Hexa8 element.
Parameters
cell The Hexa8 cell entity.
node_coord The coordinates of the mesh nodes.
u The scalar variable 𝑢 defined at the nodes.
Returns
A Real3 vector of the gradient ∇𝑢 = {∂𝑢/∂𝑥, ∂𝑢/∂𝑦, ∂𝑢/∂𝑧} at the cell center.
Definition at line 1090 of file ArcaneFemFunctions.h.
References computeGradientsAndJacobianHexa8().
Referenced by FemModuleElectrostatics::_updateVariables().
computeGradientsAndJacobianHexa8()
static Hexa8GaussPointInfo ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8 (Cell cell, const VariableNodeReal3 & node_coord, Real xi, Real eta, Real zeta) inline static
Computes shape function gradients and the Jacobian determinant for a Hexa8 element.
Parameters
cell The Hexa8 cell entity.
node_coord The coordinates of the mesh nodes.
xi The ξ coordinate of the evaluation point (-1 to 1).
eta The η coordinate of the evaluation point (-1 to 1).
zeta The ζ coordinate of the evaluation point (-1 to 1).
Returns
A Hexa8GaussPointInfo struct containing the gradients and Jacobian determinant.
Definition at line 988 of file ArcaneFemFunctions.h.
Referenced by FemModuleElasticity::_applyBodyForce(), FemModuleAcoustics::_computeElementMatrixHexa8(), FemModuleAerodynamics::_computeElementMatrixHexa8(), FemModuleElastodynamics::_computeElementMatrixHexa8(), FemModuleElectrostatics::_computeElementMatrixHexa8(), FemModuleFourier::_computeElementMatrixHexa8(), FemModuleHeat::_computeElementMatrixHexa8(), FemModuleLaplace::_computeElementMatrixHexa8(), FemModulePoisson::_computeElementMatrixHexa8(), FemModuleSoildynamics::_computeElementMatrixHexa8(), computeGradientHexa8(), and ArcaneFemFunctions::BoundaryConditions3D::integrateNodalFieldToRhsHexa8().
computeGradientTetra4()
static Real3 ArcaneFemFunctions::FeOperation3D::computeGradientTetra4 (Cell cell, const VariableNodeReal3 & node_coord, VariableNodeReal u) inline static
Definition at line 922 of file ArcaneFemFunctions.h.
computeGradientXTetra4()
static Real4 ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4 (Cell cell, const VariableNodeReal3 & node_coord) inline static
Computes the X gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
This method calculates gradient operator ∂/∂𝑥 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,4 for the four shape function 𝑁ᵢ hence output is a vector of size 4
    ∂𝐍/∂𝑥 = [ ∂𝑁₁/∂𝑥  ∂𝑁₂/∂𝑥  ∂𝑁₃/∂𝑥  ∂𝑁₄/∂𝑥 ]
    ∂𝐍/∂𝑥 = 1/(6𝑉) [ dx0  dx1  dx2  dx3 ]
where: dx0 = (n1.y * (n3.z - n2.z) + n2.y * (n1.z - n3.z) + n3.y * (n2.z - n1.z)), dx1 = (n0.y * (n2.z - n3.z) + n2.y * (n3.z - n0.z) + n3.y * (n0.z - n2.z)), dx2 = (n0.y * (n3.z - n1.z) + n1.y * (n0.z - n3.z) + n3.y * (n1.z - n0.z)), dx3 = (n0.y * (n1.z - n2.z) + n1.y * (n2.z - n0.z) + n2.y * (n0.z - n1.z)).
Definition at line 807 of file ArcaneFemFunctions.h.
Referenced by FemModuleAerodynamics::_computeElementMatrixTetra4(), FemModuleElastodynamics::_computeElementMatrixTetra4(), FemModuleElectrostatics::_computeElementMatrixTetra4(), FemModuleFourier::_computeElementMatrixTetra4(), FemModuleHeat::_computeElementMatrixTetra4(), FemModuleLaplace::_computeElementMatrixTetra4(), FemModulePoisson::_computeElementMatrixTetra4(), and FemModuleSoildynamics::_computeElementMatrixTetra4().
computeGradientYTetra4()
static Real4 ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4 (Cell cell, const VariableNodeReal3 & node_coord) inline static
Computes the Y gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
This method calculates gradient operator ∂/∂𝑦 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,4 for the four shape functions 𝑁ᵢ, hence the output is a vector of size 4.
    ∂𝐍/∂𝑦 = [ ∂𝑁₁/∂𝑦  ∂𝑁₂/∂𝑦  ∂𝑁₃/∂𝑦  ∂𝑁₄/∂𝑦 ]
    ∂𝐍/∂𝑦 = 1/(6𝑉) [ dy0  dy1  dy2  dy3 ]
where: dy0 = (n1.z * (n3.x - n2.x) + n2.z * (n1.x - n3.x) + n3.z * (n2.x - n1.x)), dy1 = (n0.z * (n2.x - n3.x) + n2.z * (n3.x - n0.x) + n3.z * (n0.x - n2.x)), dy2 = (n0.z * (n3.x - n1.x) + n1.z * (n0.x - n3.x) + n3.z * (n1.x - n0.x)), dy3 = (n0.z * (n1.x - n2.x) + n1.z * (n2.x - n0.x) + n2.z * (n0.x - n1.x)).
Definition at line 852 of file ArcaneFemFunctions.h.
Referenced by FemModuleAerodynamics::_computeElementMatrixTetra4(), FemModuleElastodynamics::_computeElementMatrixTetra4(), FemModuleElectrostatics::_computeElementMatrixTetra4(), FemModuleFourier::_computeElementMatrixTetra4(), FemModuleHeat::_computeElementMatrixTetra4(), FemModuleLaplace::_computeElementMatrixTetra4(), FemModulePoisson::_computeElementMatrixTetra4(), and FemModuleSoildynamics::_computeElementMatrixTetra4().
computeGradientZTetra4()
static Real4 ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4 (Cell cell, const VariableNodeReal3 & node_coord) inline static
Computes the 𝑧 gradients of basis functions 𝐍 for ℙ1 Tetrahedron.
This method calculates gradient operator ∂/∂𝑧 of 𝑁ᵢ for a given ℙ1 cell with i = 1,..,4 for the four shape functions 𝑁ᵢ, hence the output is a vector of size 4.
    ∂𝐍/∂𝑧 = [ ∂𝑁₁/∂𝑧  ∂𝑁₂/∂𝑧  ∂𝑁₃/∂𝑧  ∂𝑁₄/∂𝑧 ]
    ∂𝐍/∂𝑧 = 1/(6𝑉) [ dz0  dz1  dz2  dz3 ]
where: dz0 = (n1.x * (n3.y - n2.y) + n2.x * (n1.y - n3.y) + n3.x * (n2.y - n1.y)), dz1 = (n0.x * (n2.y - n3.y) + n2.x * (n3.y - n0.y) + n3.x * (n0.y - n2.y)), dz2 = (n0.x * (n3.y - n1.y) + n1.x * (n0.y - n3.y) + n3.x * (n1.y - n0.y)), dz3 = (n0.x * (n1.y - n2.y) + n1.x * (n2.y - n0.y) + n2.x * (n0.y - n1.y)).
Definition at line 897 of file ArcaneFemFunctions.h.
Referenced by FemModuleAerodynamics::_computeElementMatrixTetra4(), FemModuleElastodynamics::_computeElementMatrixTetra4(), FemModuleElectrostatics::_computeElementMatrixTetra4(), FemModuleFourier::_computeElementMatrixTetra4(), FemModuleHeat::_computeElementMatrixTetra4(), FemModuleLaplace::_computeElementMatrixTetra4(), FemModulePoisson::_computeElementMatrixTetra4(), and FemModuleSoildynamics::_computeElementMatrixTetra4().
computeShapeFunctionsHexa8()
static RealVector< 8 > ArcaneFemFunctions::FeOperation3D::computeShapeFunctionsHexa8 (Real xi, Real eta, Real zeta) inline static
Computes the shape functions for a Hexa8 element at a given point (ξ,η,ζ).
Parameters
xi The ξ coordinate of the evaluation point (-1 to 1).
eta The η coordinate of the evaluation point (-1 to 1).
zeta The ζ coordinate of the evaluation point (-1 to 1).
Returns
A RealVector<8> containing the shape functions {𝑁₁, 𝑁₂, 𝑁₃, 𝑁₄, 𝑁₅, 𝑁₆, 𝑁₇, 𝑁₈}.
Definition at line 1137 of file ArcaneFemFunctions.h.
Referenced by FemModuleElasticity::_applyBodyForce(), FemModuleAcoustics::_computeElementMatrixHexa8(), FemModuleElastodynamics::_computeElementMatrixHexa8(), FemModuleHeat::_computeElementMatrixHexa8(), and FemModuleSoildynamics::_computeElementMatrixHexa8().
The documentation for this class was generated from the following file:
ArcaneFemFunctions.h