ArcaneFem: FemModuleBilaplacian Class Reference
FemModuleBilaplacian Class Reference
Module Fem.
#include <modules/bilaplacian/FemModule.h>
Public Member Functions
FemModuleBilaplacian (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleBilaplacian at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
Private Member Functions
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _getMaterialParameters ()
Retrieves material parameters for the FEM simulation.
void _assembleBilinearOperator ()
Assembles the bilinear operator for the FEM simulation.
void _updateVariables ()
Updates the variables after solving the linear system.
void _solve ()
Solves the linear system for the FEM simulation.
void _assembleLinearOperator ()
Assembles the linear operator for the FEM simulation.
void _checkResultFile ()
Validates the result file by comparing it with the computed results.
RealMatrix< 6, 6 > _computeElementMatrixTria3 (Cell cell)
Computes the element matrix for a triangular element (ℙ1 FE).
Private Attributes
Real f
DoFLinearSystem m_linear_system
FemDoFsOnNodes m_dofs_on_nodes
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
Detailed Description
Module Fem.
Definition at line 43 of file bilaplacian/FemModule.h.
Constructor & Destructor Documentation
FemModuleBilaplacian()
FemModuleBilaplacian::FemModuleBilaplacian (const ModuleBuildInfo & mbi) inline explicit
Definition at line 48 of file bilaplacian/FemModule.h.
Member Function Documentation
_assembleBilinearOperator()
void FemModuleBilaplacian::_assembleBilinearOperator () private
Assembles the bilinear operator for the FEM simulation.
This method constructs the bilinear operator by iterating over all cells and computing the element matrix for each cell. The values are then added to the global matrix.
Note: The method assumes that the linear system has been initialized before calling this function.
Definition at line 271 of file bilaplacian/FemModule.cc.
References _computeElementMatrixTria3(), Arcane::FemUtils::DoFLinearSystem::matrixAddValue(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_assembleLinearOperator()
void FemModuleBilaplacian::_assembleLinearOperator () private
Assembles the linear operator for the FEM simulation.
This method constructs the linear system by assembling the LHS matrix and RHS vector, applying various boundary conditions and source terms.
Steps involved:
The RHS vector is initialized to zero before applying any conditions.
If Neumann BC are specified applied to the RHS.
If Dirichlet BC/Point are specified apply to the LHS & RHS.
Definition at line 146 of file bilaplacian/FemModule.cc.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::MeshOperation::computeLengthEdge2(), Arcane::FemUtils::RealMatrix< N, M >::fill(), Arcane::FemUtils::DoFLinearSystem::matrixSetValue(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _doStationarySolve().
_checkResultFile()
void FemModuleBilaplacian::_checkResultFile () private
Validates the result file by comparing it with the computed results.
This method checks the result file specified in the options and compares the computed results with the values in the file. It is used for regression testing and validation of the FEM module.
Note: The method assumes that the results have been computed before calling this function.
Definition at line 380 of file bilaplacian/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_computeElementMatrixTria3()
RealMatrix< 6, 6 > FemModuleBilaplacian::_computeElementMatrixTria3 (Cell cell) private
Computes the element matrix for a triangular element (ℙ1 FE).
This function calculates the integral of the expression: a(𝐮,𝐯) = ∫∫ (∂𝑢𝑥/∂𝑥 ∂𝑣𝑦/∂𝑥 + ∂𝑢𝑦/∂𝑥 ∂𝑣𝑦/∂𝑦)dΩ
∫∫ (∂𝑢𝑦/∂𝑥 ∂𝑣𝑥/∂𝑥 + ∂𝑣𝑦/∂𝑦 ∂𝑣𝑥/∂𝑦)dΩ
∫∫ (𝑢𝑦 𝑣𝑦)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 30 of file bilaplacian/ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
Referenced by _assembleBilinearOperator().
_doStationarySolve()
void FemModuleBilaplacian::_doStationarySolve () private
Performs a stationary solve for the FEM system.
This method follows a sequence of steps to solve FEM system:
_assembleBilinearOperator() Assembles the FEM matrix 𝑨
_assembleLinearOperator() Assembles the FEM RHS vector 𝒃
_solve() Solves for solution vector 𝒖 = 𝑨⁻¹𝒃
_updateVariables() Updates FEM variables 𝒖 = 𝒙
_validateResults() Regression test
Definition at line 94 of file bilaplacian/FemModule.cc.
References _assembleBilinearOperator(), _assembleLinearOperator(), _checkResultFile(), _getMaterialParameters(), _solve(), and _updateVariables().
Referenced by compute().
_getMaterialParameters()
void FemModuleBilaplacian::_getMaterialParameters () private
Retrieves material parameters for the FEM simulation.
This method fetches the value of the source term 'f' from the options. It is called at the beginning of the simulation to set up necessary parameters.
Definition at line 120 of file bilaplacian/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_solve()
void FemModuleBilaplacian::_solve () private
Solves the linear system for the FEM simulation.
This method calls the solve function of the linear system object to compute the solution vector.
Note: The method assumes that the linear system has been assembled before calling this function.
Definition at line 326 of file bilaplacian/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updateVariables()
void FemModuleBilaplacian::_updateVariables () private
Updates the variables after solving the linear system.
This method retrieves the solution from the linear system and updates the internal variable m_U with the computed values.
Note: The method assumes that the linear system has been solved before calling this function.
Definition at line 350 of file bilaplacian/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
compute()
void FemModuleBilaplacian::compute () override
Method called at the beginning of the simulation.
Performs the main computation for the FemModuleBilaplacian.
This method:
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Applies PETSc commandline flags to the solver (if PETSc is used).
Executes the stationary solve and extracts psi.
Definition at line 56 of file bilaplacian/FemModule.cc.
References _doStationarySolve(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleBilaplacian::startInit () override
Initializes the FemModuleBilaplacian at the start of the simulation.
This method initializes degrees of freedom (DoFs) on nodes.
It also gets values of some solver parameters.
Definition at line 26 of file bilaplacian/FemModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleBilaplacian::versionInfo () const inline override
Method called at each iteration.
Definition at line 61 of file bilaplacian/FemModule.h.
Member Data Documentation
f
Real FemModuleBilaplacian::f private
Definition at line 65 of file bilaplacian/FemModule.h.
m_assemble_linear_system
bool FemModuleBilaplacian::m_assemble_linear_system = true private
Definition at line 73 of file bilaplacian/FemModule.h.
m_cross_validation
bool FemModuleBilaplacian::m_cross_validation = false private
Definition at line 75 of file bilaplacian/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleBilaplacian::m_dofs_on_nodes private
Definition at line 68 of file bilaplacian/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleBilaplacian::m_linear_system private
Definition at line 67 of file bilaplacian/FemModule.h.
m_matrix_format
String FemModuleBilaplacian::m_matrix_format = "DOK" private
Definition at line 71 of file bilaplacian/FemModule.h.
m_petsc_flags
String FemModuleBilaplacian::m_petsc_flags private
Definition at line 70 of file bilaplacian/FemModule.h.
m_solve_linear_system
bool FemModuleBilaplacian::m_solve_linear_system = true private
Definition at line 74 of file bilaplacian/FemModule.h.
The documentation for this class was generated from the following files:
bilaplacian/FemModule.h
bilaplacian/ElementMatrix.h
bilaplacian/FemModule.cc