ArcaneFem: Arcane::FemUtils::RealMatrix< N, M > Class Template Reference
Arcane::FemUtils::RealMatrix< N, M > Class Template Reference
Matrix of size NxM.
#include <femutils/FemUtils.h>
Public Member Functions
__host__ __device__ RealMatrix (std::initializer_list< Real > init_list)
__host__ __device__ RealMatrix (std::initializer_list< std::initializer_list< Real > > init_list)
__host__ __device__ void fill (Arcane::Real value)
Fill all elements with a given value.
__host__ __device__ Arcane::Real & operator() (Arcane::Int32 i, Arcane::Int32 j)
__host__ __device__ Arcane::Real operator() (Arcane::Int32 i, Arcane::Int32 j) const
__host__ __device__ void multInPlace (Arcane::Real v)
Multiply all the components by v.
void dump (std::ostream &o) const
Dump matrix values.
__host__ __device__ RealMatrix< N, M > operator+ (const RealMatrix< N, M > &other) const
Define the addition operator.
__host__ __device__ RealMatrix< N, M > & operator+= (const RealMatrix< N, M > &other)
Define the addition-assignment operator.
RealMatrix< N, M > operator- (const RealMatrix< N, M > &other) const
Define the subtraction operator.
RealMatrix< N, M > operator- () const
Define the unary negation operator.
__host__ __device__ RealMatrix< N, M > operator* (Real scalar) const
Scalar multiplication: RealMatrix * scalar.
__host__ __device__ RealMatrix< N, M > operator/ (Real scalar) const
Scalar division: RealMatrix / scalar.
Static Public Member Functions
static constexpr Arcane::Int32 totalNbElement ()
Private Types
using ThatClass = RealMatrix< N, M >
Private Attributes
std::array< Arcane::Real, totalNbElement()> m_values = {}
Friends
__host__ __device__ friend RealMatrix< N, M > operator* (Real scalar, const RealMatrix< N, M > &matrix)
Friend function for scalar multiplication: scalar * RealMatrix.
Detailed Description
template<int N, int M>
class Arcane::FemUtils::RealMatrix< N, M >
Matrix of size NxM.
Definition at line 90 of file FemUtils.h.
Member Typedef Documentation
ThatClass
template<int N, int M> using Arcane::FemUtils::RealMatrix< N, M >::ThatClass = RealMatrix<N, M> private
Definition at line 92 of file FemUtils.h.
Constructor & Destructor Documentation
RealMatrix() [1/3]
template<int N, int M> __host__ __device__ Arcane::FemUtils::RealMatrix< N, M >::RealMatrix () inline
Definition at line 97 of file FemUtils.h.
RealMatrix() [2/3]
template<int N, int M> __host__ __device__ Arcane::FemUtils::RealMatrix< N, M >::RealMatrix (std::initializer_list< Real > init_list) inline
Definition at line 98 of file FemUtils.h.
RealMatrix() [3/3]
template<int N, int M> __host__ __device__ Arcane::FemUtils::RealMatrix< N, M >::RealMatrix (std::initializer_list< std::initializer_list< Real > > init_list) inline
Definition at line 107 of file FemUtils.h.
Member Function Documentation
dump()
template<int N, int M> void Arcane::FemUtils::RealMatrix< N, M >::dump (std::ostream & o) const inline
Dump matrix values.
Definition at line 153 of file FemUtils.h.
Referenced by Arcane::FemUtils::Tensor2::dump().
fill()
template<int N, int M> __host__ __device__ void Arcane::FemUtils::RealMatrix< N, M >::fill (Arcane::Real value) inline
Fill all elements with a given value.
Definition at line 121 of file FemUtils.h.
Referenced by FemModuleAcoustics::_assembleLinearOperator(), FemModuleBilaplacian::_assembleLinearOperator(), FemModuleElasticity::_assembleLinearOperator(), FemModuleAerodynamics::_assembleLinearOperatorCpu(), FemModuleElectrostatics::_assembleLinearOperatorCpu(), FemModuleFourier::_assembleLinearOperatorCpu(), FemModuleLaplace::_assembleLinearOperatorCpu(), FemModulePoisson::_assembleLinearOperatorCpu(), FemModuleAerodynamics::_assembleLinearOperatorGpu(), FemModuleElectrostatics::_assembleLinearOperatorGpu(), FemModuleFourier::_assembleLinearOperatorGpu(), FemModuleLaplace::_assembleLinearOperatorGpu(), FemModulePoisson::_assembleLinearOperatorGpu(), FemModuleAcoustics::_computeElementMatrixHexa8(), FemModuleAerodynamics::_computeElementMatrixHexa8(), FemModuleElastodynamics::_computeElementMatrixHexa8(), FemModuleElectrostatics::_computeElementMatrixHexa8(), FemModuleFourier::_computeElementMatrixHexa8(), FemModuleHeat::_computeElementMatrixHexa8(), FemModuleLaplace::_computeElementMatrixHexa8(), FemModulePoisson::_computeElementMatrixHexa8(), FemModuleSoildynamics::_computeElementMatrixHexa8(), FemModuleAcoustics::_computeElementMatrixQuad4(), FemModuleAerodynamics::_computeElementMatrixQuad4(), FemModuleElastodynamics::_computeElementMatrixQuad4(), FemModuleElectrostatics::_computeElementMatrixQuad4(), FemModuleFourier::_computeElementMatrixQuad4(), FemModuleHeat::_computeElementMatrixQuad4(), FemModuleLaplace::_computeElementMatrixQuad4(), FemModulePoisson::_computeElementMatrixQuad4(), FemModuleSoildynamics::_computeElementMatrixQuad4(), and FemModuleFourier::_getMaterialParameters().
multInPlace()
template<int N, int M> __host__ __device__ void Arcane::FemUtils::RealMatrix< N, M >::multInPlace (Arcane::Real v) inline
Multiply all the components by v.
Definition at line 146 of file FemUtils.h.
Referenced by Arcane::FemUtils::Tensor2::multInPlace().
operator()() [1/2]
template<int N, int M> __host__ __device__ Arcane::Real & Arcane::FemUtils::RealMatrix< N, M >::operator() (Arcane::Int32 i, Arcane::Int32 j) inline
Definition at line 129 of file FemUtils.h.
operator()() [2/2]
template<int N, int M> __host__ __device__ Arcane::Real Arcane::FemUtils::RealMatrix< N, M >::operator() (Arcane::Int32 i, Arcane::Int32 j) const inline
Definition at line 136 of file FemUtils.h.
operator*()
template<int N, int M> __host__ __device__ RealMatrix< N, M > Arcane::FemUtils::RealMatrix< N, M >::operator* (Real scalar) const inline
Scalar multiplication: RealMatrix * scalar.
Definition at line 215 of file FemUtils.h.
operator+()
template<int N, int M> __host__ __device__ RealMatrix< N, M > Arcane::FemUtils::RealMatrix< N, M >::operator+ (const RealMatrix< N, M > & other) const inline
Define the addition operator.
Definition at line 168 of file FemUtils.h.
operator+=()
template<int N, int M> __host__ __device__ RealMatrix< N, M > & Arcane::FemUtils::RealMatrix< N, M >::operator+= (const RealMatrix< N, M > & other) inline
Define the addition-assignment operator.
Definition at line 180 of file FemUtils.h.
operator-() [1/2]
template<int N, int M> RealMatrix< N, M > Arcane::FemUtils::RealMatrix< N, M >::operator- () const inline
Define the unary negation operator.
Definition at line 203 of file FemUtils.h.
operator-() [2/2]
template<int N, int M> RealMatrix< N, M > Arcane::FemUtils::RealMatrix< N, M >::operator- (const RealMatrix< N, M > & other) const inline
Define the subtraction operator.
Definition at line 191 of file FemUtils.h.
operator/()
template<int N, int M> __host__ __device__ RealMatrix< N, M > Arcane::FemUtils::RealMatrix< N, M >::operator/ (Real scalar) const inline
Scalar division: RealMatrix / scalar.
Definition at line 227 of file FemUtils.h.
totalNbElement()
template<int N, int M> static constexpr Arcane::Int32 Arcane::FemUtils::RealMatrix< N, M >::totalNbElement () inline static constexpr
Definition at line 96 of file FemUtils.h.
Friends And Related Symbol Documentation
operator*
template<int N, int M> __host__ __device__ friend RealMatrix< N, M > operator* (Real scalar, const RealMatrix< N, M > & matrix) friend
Friend function for scalar multiplication: scalar * RealMatrix.
Definition at line 239 of file FemUtils.h.
Member Data Documentation
m_values
template<int N, int M> std::array<Arcane::Real, totalNbElement()> Arcane::FemUtils::RealMatrix< N, M >::m_values = {} private
Definition at line 252 of file FemUtils.h.
The documentation for this class was generated from the following file:
FemUtils.h