ArcaneFem: FemModuleHeat Class Reference
FemModuleHeat Class Reference
Module Fem.
#include <modules/heat/FemModule.h>
Public Member Functions
FemModuleHeat (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleHeat at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
void _assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
Private Member Functions
void _initTime ()
void _updateTime ()
void _updateVariables ()
void _initTemperature ()
void _doStationarySolve ()
void _getParameters ()
void _solve ()
void _assembleLinearOperator ()
void _validateResults ()
RealMatrix< 3, 3 > _computeElementMatrixTria3 (Cell cell)
Computes the element matrix for a triangular element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixTetra4 (Cell cell)
Computes the element matrix for a tetrahedral element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixQuad4 (Cell cell)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
RealMatrix< 8, 8 > _computeElementMatrixHexa8 (Cell cell)
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
template<int N>
void _assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the bilinear operator matrix for the FEM linear system.
Private Attributes
Real t
Real dt
Real tmax
Real Tinit
Time variables.
Real Text
Real lambda
Temperature.
Real h
Real qdot
DoFLinearSystem m_linear_system
Material parameters.
IItemFamily * m_dof_family = nullptr
FemDoFsOnNodes m_dofs_on_nodes
BSRFormat m_bsr_format
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_hex_quad_mesh = false
Detailed Description
Module Fem.
Definition at line 50 of file heat/FemModule.h.
Constructor & Destructor Documentation
FemModuleHeat()
FemModuleHeat::FemModuleHeat (const ModuleBuildInfo & mbi) inline explicit
Definition at line 55 of file heat/FemModule.h.
Member Function Documentation
_assembleBilinear()
template<int N> void FemModuleHeat::_assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the bilinear operator matrix for the FEM linear system.
The method performs the following steps:
For each cell, retrieves the cell-specific constant lambda.
Computes element matrix using provided compute_element_matrix function.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 499 of file heat/FemModule.cc.
References m_linear_system, and Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleBilinearOperator()
void FemModuleHeat::_assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
Definition at line 439 of file heat/FemModule.cc.
References _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), _computeElementMatrixTria3(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
_assembleLinearOperator()
void FemModuleHeat::_assembleLinearOperator () private
Definition at line 278 of file heat/FemModule.cc.
_computeElementMatrixHexa8()
RealMatrix< 8, 8 > FemModuleHeat::_computeElementMatrixHexa8 (Cell cell) private
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫∫ λ(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ + ∫∫∫ (𝑢𝑣/δ𝑡)dΩ
Steps involved:
Define Gauss points (2x2x2) and weights.
Loop over Gauss points to compute the gradients in physical space (𝑥,𝑦,𝑧) and the determinant of the Jacobian via computeGradientsAndJacobianHexa8.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 91 of file heat/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), ArcaneFemFunctions::FeOperation3D::computeShapeFunctionsHexa8(), Arcane::FemUtils::RealMatrix< N, M >::fill(), and lambda.
Referenced by _assembleBilinearOperator().
_computeElementMatrixQuad4()
RealMatrix< 4, 4 > FemModuleHeat::_computeElementMatrixQuad4 (Cell cell) private
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫ λ(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ + ∫∫ (𝑢𝑣/δ𝑡)dΩ
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 33 of file heat/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), ArcaneFemFunctions::FeOperation2D::computeShapeFunctionsQuad4(), Arcane::FemUtils::RealMatrix< N, M >::fill(), and lambda.
Referenced by _assembleBilinearOperator().
_computeElementMatrixTetra4()
RealMatrix< 4, 4 > FemModuleHeat::_computeElementMatrixTetra4 (Cell cell) private
Computes the element matrix for a tetrahedral element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫∫ λ(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ + ∫∫∫ (𝑢𝑣/δ𝑡)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 89 of file heat/ElementMatrix.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientXTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientYTetra4(), ArcaneFemFunctions::FeOperation3D::computeGradientZTetra4(), ArcaneFemFunctions::MeshOperation::computeVolumeTetra4(), and lambda.
Referenced by _assembleBilinearOperator().
_computeElementMatrixTria3()
RealMatrix< 3, 3 > FemModuleHeat::_computeElementMatrixTria3 (Cell cell) private
Computes the element matrix for a triangular element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫ λ(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ + ∫∫ (𝑢𝑣/δ𝑡)dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 28 of file heat/ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientYTria3(), and lambda.
Referenced by _assembleBilinearOperator().
_doStationarySolve()
void FemModuleHeat::_doStationarySolve () private
Definition at line 219 of file heat/FemModule.cc.
_getParameters()
void FemModuleHeat::_getParameters () private
Definition at line 238 of file heat/FemModule.cc.
_initTemperature()
void FemModuleHeat::_initTemperature () private
Definition at line 196 of file heat/FemModule.cc.
_initTime()
void FemModuleHeat::_initTime () private
Definition at line 102 of file heat/FemModule.cc.
_solve()
void FemModuleHeat::_solve () private
Definition at line 525 of file heat/FemModule.cc.
_updateTime()
void FemModuleHeat::_updateTime () private
Definition at line 116 of file heat/FemModule.cc.
_updateVariables()
void FemModuleHeat::_updateVariables () private
Definition at line 128 of file heat/FemModule.cc.
_validateResults()
void FemModuleHeat::_validateResults () private
Definition at line 540 of file heat/FemModule.cc.
compute()
void FemModuleHeat::compute () override
Method called at the beginning of the simulation.
Definition at line 65 of file heat/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::clearValues(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), Arcane::FemUtils::DoFLinearSystem::isInitialized(), m_linear_system, ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleHeat::startInit () override
Initializes the FemModuleHeat at the start of the simulation.
This method initializes degrees of freedom (DoFs) on nodes.
Definition at line 26 of file heat/FemModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleHeat::versionInfo () const inline override
Method called at each iteration.
Definition at line 69 of file heat/FemModule.h.
Member Data Documentation
dt
Real FemModuleHeat::dt private
Definition at line 75 of file heat/FemModule.h.
h
Real FemModuleHeat::h private
Definition at line 77 of file heat/FemModule.h.
lambda
Real FemModuleHeat::lambda private
Temperature.
Definition at line 77 of file heat/FemModule.h.
Referenced by _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTetra4(), and _computeElementMatrixTria3().
m_assemble_linear_system
bool FemModuleHeat::m_assemble_linear_system = true private
Definition at line 87 of file heat/FemModule.h.
m_bsr_format
BSRFormat FemModuleHeat::m_bsr_format private
Definition at line 82 of file heat/FemModule.h.
m_cross_validation
bool FemModuleHeat::m_cross_validation = false private
Definition at line 89 of file heat/FemModule.h.
m_dof_family
IItemFamily* FemModuleHeat::m_dof_family = nullptr private
Definition at line 80 of file heat/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleHeat::m_dofs_on_nodes private
Definition at line 81 of file heat/FemModule.h.
m_hex_quad_mesh
bool FemModuleHeat::m_hex_quad_mesh = false private
Definition at line 90 of file heat/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleHeat::m_linear_system private
Material parameters.
Definition at line 79 of file heat/FemModule.h.
Referenced by _assembleBilinear(), and compute().
m_matrix_format
String FemModuleHeat::m_matrix_format = "DOK" private
Definition at line 85 of file heat/FemModule.h.
m_petsc_flags
String FemModuleHeat::m_petsc_flags private
Definition at line 84 of file heat/FemModule.h.
m_solve_linear_system
bool FemModuleHeat::m_solve_linear_system = true private
Definition at line 88 of file heat/FemModule.h.
qdot
Real FemModuleHeat::qdot private
Definition at line 77 of file heat/FemModule.h.
t
Real FemModuleHeat::t private
Definition at line 75 of file heat/FemModule.h.
Text
Real FemModuleHeat::Text private
Definition at line 76 of file heat/FemModule.h.
Tinit
Real FemModuleHeat::Tinit private
Time variables.
Definition at line 76 of file heat/FemModule.h.
tmax
Real FemModuleHeat::tmax private
Definition at line 75 of file heat/FemModule.h.
The documentation for this class was generated from the following files:
heat/FemModule.h
heat/ElementMatrix.h
heat/ElementMatrixHexQuad.h
heat/FemModule.cc