ArcaneFem: ElastodynamicModule Class Reference
ElastodynamicModule Class Reference
Class to define the seismic inputmotion features.
#include <modules/passmo/ElastodynamicModule.h>
Classes
struct CaseTableInfo
Public Member Functions
ElastodynamicModule (const ModuleBuildInfo &mbi)
void startInit () override
Method called at the beginning of the simulation.
void compute () override
Method called at each step.
VersionInfo versionInfo () const override
Private Member Functions
void _initDofs ()
void _startInitGauss ()
void _initGaussStep ()
void _initCells ()
void _applyInitialNodeConditions ()
void _applyInitialCellConditions ()
void _assembleLinearLHS ()
void _assembleLinearRHS ()
void _doSolve ()
void _initBoundaryConditions ()
void _initDCConditions ()
void _applyDirichletBoundaryConditions ()
void _applyParaxialBoundaryConditions ()
void _applyNeumannBoundaryConditions ()
void _getParaxialContribution (VariableDoFReal &rhs_values)
void _assembleLHSParaxialContribution ()
void _getTractionContribution (Arcane::VariableDoFReal &rhs_values)
Real3x3 _computeJacobian (const ItemWithNodes &cell, const Int32 &ig, const RealUniqueArray &vec, Real &jac)
void _updateNewmark ()
void _checkResultFile ()
void _computeK (const Real &lambda, const Real &mu, const DoFLocalId &igauss, const Int32 &nb_nodes, RealUniqueArray2 &Ke)
void _computeElemMass (const Real &rho, const DoFLocalId &igauss, const Int32 &nb_nodes, RealUniqueArray2 &Me)
void _computeKParax (const Face &face, const Int32 &ig, const RealUniqueArray &vec, const Real &jacobian, RealUniqueArray2 &Ke, const Real3 &RhoC)
Private Attributes
DoFLinearSystem m_linear_system
FemDoFsOnNodes m_dofs_on_nodes
GaussDoFsOnCells m_gauss_on_cells
UniqueArray< CaseTableInfo > m_traction_case_table_list
UniqueArray< CaseTableInfo > m_sacc_case_table_list
UniqueArray< CaseTableInfo > m_sdispl_case_table_list
UniqueArray< CaseTableInfo > m_svel_case_table_list
UniqueArray< CaseTableInfo > m_sforce_case_table_list
UniqueArray< CaseTableInfo > m_acc_case_table_list
UniqueArray< CaseTableInfo > m_displ_case_table_list
UniqueArray< CaseTableInfo > m_vel_case_table_list
UniqueArray< CaseTableInfo > m_force_case_table_list
UniqueArray< CaseTableInfo > m_ain_case_table_list
UniqueArray< CaseTableInfo > m_vin_case_table_list
UniqueArray< CaseTableInfo > m_uin_case_table_list
UniqueArray< CaseTableInfo > m_dc_case_table_list
Integer ninteg {2}
Int32 NDIM {2}
ArcaneFemFunctions::CellFEMDispatcher cell_fem {}
Real3 gravity {0.,0.,0.}
Real penalty {1.e64}
Real gamma {0.5}
Real beta {0.25}
Real alfam {0.}
Real alfaf {0.}
bool is_alfa_method {false}
bool keep_constop {false}
Real dt2 {0.}
Int32 linop_nstep {1000}
Int32 linop_nstep_counter {0}
TypesElastodynamic::eElastType elast_type {TypesElastodynamic::NoElastPropType}
TypesElastodynamic::eAnalysisType analysis_type {TypesElastodynamic::PlaneStrain}
AnalyticFunc m_inputfunc {}
Detailed Description
Class to define the seismic inputmotion features.
Module Elastodynamic.
Definition at line 61 of file ElastodynamicModule.h.
Constructor & Destructor Documentation
ElastodynamicModule()
ElastodynamicModule::ElastodynamicModule (const ModuleBuildInfo & mbi) explicit
Definition at line 34 of file ElastodynamicModule.cc.
~ElastodynamicModule()
ElastodynamicModule::~ElastodynamicModule ()
Definition at line 48 of file ElastodynamicModule.cc.
Member Function Documentation
_applyDirichletBoundaryConditions()
void ElastodynamicModule::_applyDirichletBoundaryConditions () private
Definition at line 905 of file ElastodynamicModule.cc.
_applyInitialCellConditions()
void ElastodynamicModule::_applyInitialCellConditions () private
Definition at line 331 of file ElastodynamicModule.cc.
_applyInitialNodeConditions()
void ElastodynamicModule::_applyInitialNodeConditions () private
Definition at line 302 of file ElastodynamicModule.cc.
_applyNeumannBoundaryConditions()
void ElastodynamicModule::_applyNeumannBoundaryConditions () private
Definition at line 1199 of file ElastodynamicModule.cc.
_applyParaxialBoundaryConditions()
void ElastodynamicModule::_applyParaxialBoundaryConditions () private
Definition at line 1239 of file ElastodynamicModule.cc.
_assembleLHSParaxialContribution()
void ElastodynamicModule::_assembleLHSParaxialContribution () private
Definition at line 2234 of file ElastodynamicModule.cc.
_assembleLinearLHS()
void ElastodynamicModule::_assembleLinearLHS () private
Definition at line 1714 of file ElastodynamicModule.cc.
_assembleLinearRHS()
void ElastodynamicModule::_assembleLinearRHS () private
Definition at line 1804 of file ElastodynamicModule.cc.
_checkResultFile()
void ElastodynamicModule::_checkResultFile () private
Definition at line 545 of file ElastodynamicModule.cc.
_computeElemMass()
void ElastodynamicModule::_computeElemMass (const Real & rho, const DoFLocalId & igauss, const Int32 & nb_nodes, RealUniqueArray2 & Me) private
Definition at line 1395 of file ElastodynamicModule.cc.
_computeJacobian()
Real3x3 ElastodynamicModule::_computeJacobian (const ItemWithNodes & cell, const Int32 & ig, const RealUniqueArray & vec, Real & jac) private
Definition at line 1352 of file ElastodynamicModule.cc.
_computeK()
void ElastodynamicModule::_computeK (const Real & lambda, const Real & mu, const DoFLocalId & igauss, const Int32 & nb_nodes, RealUniqueArray2 & Ke) private
Definition at line 1432 of file ElastodynamicModule.cc.
_computeKParax()
void ElastodynamicModule::_computeKParax (const Face & face, const Int32 & ig, const RealUniqueArray & vec, const Real & jacobian, RealUniqueArray2 & Ke, const Real3 & RhoC) private
Definition at line 1645 of file ElastodynamicModule.cc.
_doSolve()
void ElastodynamicModule::_doSolve () private
Definition at line 2350 of file ElastodynamicModule.cc.
_getParaxialContribution()
void ElastodynamicModule::_getParaxialContribution (VariableDoFReal & rhs_values) private
Definition at line 2115 of file ElastodynamicModule.cc.
_getTractionContribution()
void ElastodynamicModule::_getTractionContribution (Arcane::VariableDoFReal & rhs_values) private
Definition at line 2316 of file ElastodynamicModule.cc.
_initBoundaryConditions()
void ElastodynamicModule::_initBoundaryConditions () private
Definition at line 600 of file ElastodynamicModule.cc.
_initCells()
void ElastodynamicModule::_initCells () private
Definition at line 255 of file ElastodynamicModule.cc.
_initDCConditions()
void ElastodynamicModule::_initDCConditions () private
Definition at line 868 of file ElastodynamicModule.cc.
_initDofs()
void ElastodynamicModule::_initDofs () private
Definition at line 180 of file ElastodynamicModule.cc.
_initGaussStep()
void ElastodynamicModule::_initGaussStep () private
Definition at line 413 of file ElastodynamicModule.cc.
_startInitGauss()
void ElastodynamicModule::_startInitGauss () private
Definition at line 187 of file ElastodynamicModule.cc.
_updateNewmark()
void ElastodynamicModule::_updateNewmark () private
Definition at line 559 of file ElastodynamicModule.cc.
compute()
void ElastodynamicModule::compute () override
Method called at each step.
Definition at line 471 of file ElastodynamicModule.cc.
References Arcane::FemUtils::DoFLinearSystem::clearValues(), Arcane::FemUtils::DoFLinearSystem::isInitialized(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void ElastodynamicModule::startInit () override
Method called at the beginning of the simulation.
Definition at line 80 of file ElastodynamicModule.cc.
References TypesElastodynamic::Lame, Arcane::FemUtils::DoFLinearSystem::reset(), Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory(), TypesElastodynamic::ThreeD, TypesElastodynamic::Veloc, and TypesElastodynamic::YoungNu.
versionInfo()
VersionInfo ElastodynamicModule::versionInfo () const override
Definition at line 44 of file ElastodynamicModule.cc.
Member Data Documentation
alfaf
Real ElastodynamicModule::alfaf {0.} private
Definition at line 121 of file ElastodynamicModule.h.
alfam
Real ElastodynamicModule::alfam {0.} private
Definition at line 120 of file ElastodynamicModule.h.
analysis_type
TypesElastodynamic::eAnalysisType ElastodynamicModule::analysis_type {TypesElastodynamic::PlaneStrain} private
Definition at line 127 of file ElastodynamicModule.h.
beta
Real ElastodynamicModule::beta {0.25} private
Definition at line 119 of file ElastodynamicModule.h.
cell_fem
ArcaneFemFunctions::CellFEMDispatcher ElastodynamicModule::cell_fem {} private
Definition at line 115 of file ElastodynamicModule.h.
dt2
Real ElastodynamicModule::dt2 {0.} private
Definition at line 124 of file ElastodynamicModule.h.
elast_type
TypesElastodynamic::eElastType ElastodynamicModule::elast_type {TypesElastodynamic::NoElastPropType} private
Definition at line 126 of file ElastodynamicModule.h.
gamma
Real ElastodynamicModule::gamma {0.5} private
Definition at line 118 of file ElastodynamicModule.h.
gravity
Real3 ElastodynamicModule::gravity {0.,0.,0.} private
Definition at line 116 of file ElastodynamicModule.h.
is_alfa_method
bool ElastodynamicModule::is_alfa_method {false} private
Definition at line 122 of file ElastodynamicModule.h.
keep_constop
bool ElastodynamicModule::keep_constop {false} private
Definition at line 122 of file ElastodynamicModule.h.
linop_nstep
Int32 ElastodynamicModule::linop_nstep {1000} private
Definition at line 125 of file ElastodynamicModule.h.
linop_nstep_counter
Int32 ElastodynamicModule::linop_nstep_counter {0} private
Definition at line 125 of file ElastodynamicModule.h.
m_acc_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_acc_case_table_list private
Definition at line 100 of file ElastodynamicModule.h.
m_ain_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_ain_case_table_list private
Definition at line 106 of file ElastodynamicModule.h.
m_dc_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_dc_case_table_list private
Definition at line 111 of file ElastodynamicModule.h.
m_displ_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_displ_case_table_list private
Definition at line 101 of file ElastodynamicModule.h.
m_dofs_on_nodes
FemDoFsOnNodes ElastodynamicModule::m_dofs_on_nodes private
Definition at line 80 of file ElastodynamicModule.h.
m_force_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_force_case_table_list private
Definition at line 103 of file ElastodynamicModule.h.
m_gauss_on_cells
GaussDoFsOnCells ElastodynamicModule::m_gauss_on_cells private
Definition at line 81 of file ElastodynamicModule.h.
m_inputfunc
AnalyticFunc ElastodynamicModule::m_inputfunc {} private
Definition at line 128 of file ElastodynamicModule.h.
m_linear_system
DoFLinearSystem ElastodynamicModule::m_linear_system private
Definition at line 79 of file ElastodynamicModule.h.
m_sacc_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_sacc_case_table_list private
Definition at line 94 of file ElastodynamicModule.h.
m_sdispl_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_sdispl_case_table_list private
Definition at line 95 of file ElastodynamicModule.h.
m_sforce_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_sforce_case_table_list private
Definition at line 97 of file ElastodynamicModule.h.
m_svel_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_svel_case_table_list private
Definition at line 96 of file ElastodynamicModule.h.
m_traction_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_traction_case_table_list private
Definition at line 91 of file ElastodynamicModule.h.
m_uin_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_uin_case_table_list private
Definition at line 108 of file ElastodynamicModule.h.
m_vel_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_vel_case_table_list private
Definition at line 102 of file ElastodynamicModule.h.
m_vin_case_table_list
UniqueArray<CaseTableInfo> ElastodynamicModule::m_vin_case_table_list private
Definition at line 107 of file ElastodynamicModule.h.
NDIM
Int32 ElastodynamicModule::NDIM {2} private
Definition at line 114 of file ElastodynamicModule.h.
ninteg
Integer ElastodynamicModule::ninteg {2} private
Definition at line 113 of file ElastodynamicModule.h.
penalty
Real ElastodynamicModule::penalty {1.e64} private
Definition at line 117 of file ElastodynamicModule.h.
The documentation for this class was generated from the following files:
ElastodynamicModule.h
ElastodynamicModule.cc