ArcaneFem: FemModuleTestlab Class Reference
FemModuleTestlab Class Reference
Module Fem.
#include <modules/testlab/FemModule.h>
Public Member Functions
FemModuleTestlab (const ModuleBuildInfo &mbi)
void compute () override
Method called at each iteration.
void startInit () override
Method called at the beginning of the simulation.
void endModule () override
Method called at the end of the simulation.
VersionInfo versionInfo () const override
void _doStationarySolve ()
void _applyDirichletBoundaryConditionsGpu ()
void _assembleCsrGpuLinearOperator ()
void _computeSortedEdges (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > &sorted_edges_ss)
void _computeNeighbors (Int8 edges_per_element, Int64 nb_edge_total, NumArray< Int32, MDDim1 > &neighbors, SmallSpan< UInt64 > &sorted_edges_ss)
void _computeRowIndex (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > &sorted_edges_ss)
void _computeColumns (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< uint64_t > &sorted_edges_ss)
void _computeSparsity ()
void _fillDiagonal (Int64 nb_edge, NodeGroup nodes)
void _assembleCsrGPUBilinearOperatorTRIA3 ()
Assembles the bilinear operator matrix for the FEM linear system with the CSR sparse matrix format for TRIA3 elements.
void _assembleCsrGPUBilinearOperatorTETRA4 ()
Assembles the bilinear operator matrix for the FEM linear system with the CSR sparse matrix format for TETRA4 elements.
void _buildMatrixCooGPU ()
void _assembleCooGPUBilinearOperatorTRIA3 ()
void _assembleCooGPUBilinearOperatorTETRA4 ()
void _buildMatrixCooSortGPU ()
void _assembleCooSortGPUBilinearOperatorTRIA3 ()
void _assembleCooSortGPUBilinearOperatorTETRA4 ()
void _buildMatrixNodeWiseCsr ()
void _buildOffsetsNodeWiseCsr (const SmallSpan< UInt32 > &offsets_smallspan)
Builds the node-wise CSR matrix for the finite element method.
void _assembleNodeWiseCsrBilinearOperatorTria3 ()
void _assembleNodeWiseCsrBilinearOperatorTetra4 ()
Assembles the node-wise CSR bilinear operator for TETRA4 mesh type.
void _buildMatrixBuildLessCsr ()
void _buildMatrixGpuBuildLessCsr ()
void _assembleBuildLessCsrBilinearOperatorTria3 ()
void _assembleBuildLessCsrBilinearOperatorTetra4 ()
Static Public Member Functions
static __host__ __device__ Int32 _getValIndexCsrGpu (Int32 begin, Int32 end, DoFLocalId col, ax::NumArrayView< DataViewGetter< Int32 >, MDDim1, DefaultLayout > csr_col)
static __host__ __device__ Real _computeAreaTetra4Gpu (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord)
static __host__ __device__ Real _computeAreaTriangle3Gpu (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord)
static __host__ __device__ Real _computeEdgeLength2Gpu (FaceLocalId iface, IndexedFaceNodeConnectivityView fnc, ax::VariableNodeReal3InView in_node_coord)
static __host__ __device__ Real2 _computeEdgeNormal2Gpu (FaceLocalId iface, IndexedFaceNodeConnectivityView fnc, ax::VariableNodeReal3InView in_node_coord, FaceInfoListView faces_infos)
static __host__ __device__ void _computeElementMatrixTRIA3GPU (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord, Real K_e[9])
static __host__ __device__ void _computeElementMatrixTETRA4GPU (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord, Real K_e[16])
static __host__ __device__ Real _computeCellMatrixGpuTETRA4 (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord, Real b_matrix[12])
static __host__ __device__ Real _computeCellMatrixGpuTRIA3 (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord, Real b_matrix[6])
static __host__ __device__ void _addValueToGlobalMatrixGpu (Int32 begin, Int32 end, Int32 col, ax::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > in_out_col_csr, ax::NumArrayView< DataViewGetterSetter< Real >, MDDim1, DefaultLayout > in_out_val_csr, Real x)
Private Member Functions
void _handleFlags ()
void _getMaterialParameters ()
void _checkCellType ()
void _assembleBilinearOperatorTRIA3 ()
void _assembleBilinearOperatorTETRA4 ()
void _solve ()
void _initBoundaryconditions ()
void _assembleLinearOperator (BSRMatrix *bsr_matrix=nullptr)
void _applyDirichletBoundaryConditions ()
void _checkResultFile ()
void _dumpTimeStats ()
void _setPetscFlagsFromCommandline ()
Function to set Petsc flags from commandline.
RealMatrix< 3, 3 > _computeElementMatrixTRIA3 (Cell cell)
RealMatrix< 4, 4 > _computeElementMatrixTETRA4 (Cell cell)
Real _computeAreaTriangle3 (Cell cell)
Real _computeAreaTetra4 (Cell cell)
Real _computeEdgeLength2 (Face face)
Real2 _computeEdgeNormal2 (Face face)
void _buildMatrixCoo ()
Builds the coordinate (COO) matrix for the finite element method (FEM) module.
void _assembleCooBilinearOperatorTRIA3 ()
Assembles the bilinear operator matrix for the FEM linear system with the COO sparse matrix format for TRIA3 elements.
void _assembleCooBilinearOperatorTETRA4 ()
Assembles the bilinear operator matrix for the FEM linear system with the COO sparse matrix format.
void _buildMatrixCooSort ()
Builds the COO Sort matrix by first filling the diagonal and then the off-diagonal entries.
void _assembleCooSortBilinearOperatorTRIA3 ()
Assembles the bilinear operator matrix for the FEM linear system with the COO Sorted sparse matrix format for TRIA3 elements.
void _assembleCooSortBilinearOperatorTETRA4 ()
Assembles the bilinear operator matrix for the FEM linear system with the COO Sorted sparse matrix format for TETRA4 elements.
void _assembleCsrBilinearOperatorTRIA3 ()
void _assembleCsrBilinearOperatorTETRA4 ()
void _buildMatrixCsr ()
Initialization of the csr matrix. It only works for p=1 since there is one node per Edge.
void _build ()
void _assembleCsrLinearOperator ()
void _translateRhs ()
bool _isMasterRank () const
void _printArcaneFemTime (const String label, const Real value)
Function to prints the execution time value of phase label
Private Attributes
Real f
Real ElementNodes
DoFLinearSystem m_linear_system
IItemFamily * m_dof_family = nullptr
FemDoFsOnNodes m_dofs_on_nodes
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_register_time = false
bool m_arcane_timer = false
Integer m_cache_warming = 1
bool m_use_coo = false
bool m_use_coo_sort = false
bool m_use_coo_gpu = false
bool m_use_coo_sort_gpu = false
bool m_use_csr = false
bool m_use_csr_gpu = false
bool m_use_nodewise_csr = false
bool m_use_buildless_csr = false
bool m_use_legacy = true
bool m_use_bsr = false
bool m_use_bsr_atomic_free = false
bool m_running_on_gpu = false
bool m_solve_linear_system = true
bool m_cross_validation = true
ITimeStats * m_time_stats
CooFormat m_coo_matrix
CsrFormat m_csr_matrix
BSRFormat m_bsr_format
NumArray< Real, MDDim1 > m_rhs_vect
Integer cache_index
Ref< IIndexedIncrementalItemConnectivity > m_node_node_via_edge_connectivity
List of nodes connected to an another node via a edge of the a cell.
Int64 m_nb_edge = -1
Number of edges (only for 3D meshes)
RunQueue m_queue
Default queue used for computation.
Detailed Description
Module Fem.
Definition at line 116 of file testlab/FemModule.h.
Constructor & Destructor Documentation
FemModuleTestlab()
FemModuleTestlab::FemModuleTestlab (const ModuleBuildInfo & mbi) inline explicit
Definition at line 121 of file testlab/FemModule.h.
Member Function Documentation
_addValueToGlobalMatrixGpu()
__host__ __device__ void FemModuleTestlab::_addValueToGlobalMatrixGpu (Int32 begin, Int32 end, Int32 col, ax::NumArrayView< DataViewGetterSetter< Int32 >, MDDim1, DefaultLayout > in_out_col_csr, ax::NumArrayView< DataViewGetterSetter< Real >, MDDim1, DefaultLayout > in_out_val_csr, Real x) static
Definition at line 106 of file BlCsrBiliAssembly.cc.
_applyDirichletBoundaryConditions()
void FemModuleTestlab::_applyDirichletBoundaryConditions () private
Definition at line 647 of file testlab/FemModule.cc.
_applyDirichletBoundaryConditionsGpu()
void FemModuleTestlab::_applyDirichletBoundaryConditionsGpu ()
Definition at line 594 of file testlab/FemModule.cc.
_assembleBilinearOperatorTETRA4()
void FemModuleTestlab::_assembleBilinearOperatorTETRA4 () private
Definition at line 52 of file LegacyBiliAssembly.cc.
_assembleBilinearOperatorTRIA3()
void FemModuleTestlab::_assembleBilinearOperatorTRIA3 () private
Definition at line 16 of file LegacyBiliAssembly.cc.
_assembleBuildLessCsrBilinearOperatorTetra4()
void FemModuleTestlab::_assembleBuildLessCsrBilinearOperatorTetra4 ()
Definition at line 189 of file BlCsrBiliAssembly.cc.
_assembleBuildLessCsrBilinearOperatorTria3()
void FemModuleTestlab::_assembleBuildLessCsrBilinearOperatorTria3 ()
Definition at line 124 of file BlCsrBiliAssembly.cc.
_assembleCooBilinearOperatorTETRA4()
void FemModuleTestlab::_assembleCooBilinearOperatorTETRA4 () private
Assembles the bilinear operator matrix for the FEM linear system with the COO sparse matrix format.
The method performs the following steps:
Builds the COO matrix using _buildMatrixCoo.
For each cell, computes element matrix using _computeElementMatrixTETRA4.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 129 of file CooBiliAssembly.cc.
References _buildMatrixCoo(), and Arcane::FemUtils::CooFormat::matrixAddValue().
_assembleCooBilinearOperatorTRIA3()
void FemModuleTestlab::_assembleCooBilinearOperatorTRIA3 () private
Assembles the bilinear operator matrix for the FEM linear system with the COO sparse matrix format for TRIA3 elements.
The method performs the following steps:
Builds the COO matrix using _buildMatrixCoo.
For each cell, computes element matrix using _computeElementMatrixTRIA3.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 78 of file CooBiliAssembly.cc.
References _buildMatrixCoo(), and Arcane::FemUtils::CooFormat::matrixAddValue().
_assembleCooGPUBilinearOperatorTETRA4()
void FemModuleTestlab::_assembleCooGPUBilinearOperatorTETRA4 ()
Definition at line 297 of file CooGpuBiliAssembly.cc.
_assembleCooGPUBilinearOperatorTRIA3()
void FemModuleTestlab::_assembleCooGPUBilinearOperatorTRIA3 ()
Definition at line 237 of file CooGpuBiliAssembly.cc.
_assembleCooSortBilinearOperatorTETRA4()
void FemModuleTestlab::_assembleCooSortBilinearOperatorTETRA4 () private
Assembles the bilinear operator matrix for the FEM linear system with the COO Sorted sparse matrix format for TETRA4 elements.
The method performs the following steps:
Builds the COO Sorted matrix using _buildMatrixCooSort.
For each cell, computes element matrix using _computeElementMatrixTETRA4.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Note
This implementation is the same as the one in CooBiliAssembly.cc, but uses the sorted COO matrix.
Definition at line 143 of file CooSortBiliAssembly.cc.
References _buildMatrixCooSort(), and Arcane::FemUtils::CooFormat::matrixAddValue().
_assembleCooSortBilinearOperatorTRIA3()
void FemModuleTestlab::_assembleCooSortBilinearOperatorTRIA3 () private
Assembles the bilinear operator matrix for the FEM linear system with the COO Sorted sparse matrix format for TRIA3 elements.
The method performs the following steps:
Builds the COO Sorted matrix using _buildMatrixCooSort.
For each cell, computes element matrix using _computeElementMatrixTRIA3.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Note
This implementation is the same as the one in CooBiliAssembly.cc, but uses the sorted COO matrix.
Definition at line 87 of file CooSortBiliAssembly.cc.
References _buildMatrixCooSort(), and Arcane::FemUtils::CooFormat::matrixAddValue().
_assembleCooSortGPUBilinearOperatorTETRA4()
void FemModuleTestlab::_assembleCooSortGPUBilinearOperatorTETRA4 ()
Definition at line 229 of file CooSortGpuBiliAssembly.cc.
_assembleCooSortGPUBilinearOperatorTRIA3()
void FemModuleTestlab::_assembleCooSortGPUBilinearOperatorTRIA3 ()
Definition at line 169 of file CooSortGpuBiliAssembly.cc.
_assembleCsrBilinearOperatorTETRA4()
void FemModuleTestlab::_assembleCsrBilinearOperatorTETRA4 () private
Definition at line 148 of file CsrBiliAssembly.cc.
_assembleCsrBilinearOperatorTRIA3()
void FemModuleTestlab::_assembleCsrBilinearOperatorTRIA3 () private
Definition at line 97 of file CsrBiliAssembly.cc.
_assembleCsrGPUBilinearOperatorTETRA4()
void FemModuleTestlab::_assembleCsrGPUBilinearOperatorTETRA4 ()
Assembles the bilinear operator matrix for the FEM linear system with the CSR sparse matrix format for TETRA4 elements.
The method performs the following steps:
Builds the CSR matrix using _buildMatrixCsrGPU.
For each cell, computes element matrix using _computeElementMatrixTETRA4GPU.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 310 of file CsrGpuBiliAssembly.cc.
References m_queue.
_assembleCsrGPUBilinearOperatorTRIA3()
void FemModuleTestlab::_assembleCsrGPUBilinearOperatorTRIA3 ()
Assembles the bilinear operator matrix for the FEM linear system with the CSR sparse matrix format for TRIA3 elements.
The method performs the following steps:
Builds the CSR matrix using _buildMatrixCsrGPU.
For each cell, computes element matrix using _computeElementMatrixTRIA3GPU.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 222 of file CsrGpuBiliAssembly.cc.
_assembleCsrGpuLinearOperator()
void FemModuleTestlab::_assembleCsrGpuLinearOperator ()
Definition at line 1190 of file testlab/FemModule.cc.
_assembleCsrLinearOperator()
void FemModuleTestlab::_assembleCsrLinearOperator () private
Definition at line 953 of file testlab/FemModule.cc.
_assembleLinearOperator()
void FemModuleTestlab::_assembleLinearOperator (BSRMatrix * bsr_matrix = nullptr) private
Definition at line 713 of file testlab/FemModule.cc.
_assembleNodeWiseCsrBilinearOperatorTetra4()
void FemModuleTestlab::_assembleNodeWiseCsrBilinearOperatorTetra4 ()
Assembles the node-wise CSR bilinear operator for TETRA4 mesh type.
This function builds the CSR matrix and computes the bilinear operator for a TETRA4 mesh type. It initializes the CSR matrix, sets up the necessary views, and performs the computation on the accelerator.
Definition at line 232 of file NodeWiseCsrBiliAssembly.cc.
_assembleNodeWiseCsrBilinearOperatorTria3()
void FemModuleTestlab::_assembleNodeWiseCsrBilinearOperatorTria3 ()
Definition at line 157 of file NodeWiseCsrBiliAssembly.cc.
_build()
void FemModuleTestlab::_build () private
Definition at line 2061 of file testlab/FemModule.cc.
_buildMatrixBuildLessCsr()
void FemModuleTestlab::_buildMatrixBuildLessCsr ()
Definition at line 18 of file BlCsrBiliAssembly.cc.
_buildMatrixCoo()
void FemModuleTestlab::_buildMatrixCoo () private
Builds the coordinate (COO) matrix for the finite element method (FEM) module.
This function initializes and populates the COO matrix based on the mesh's nodes and their connectivity. It assumes a polynomial degree (p) of 1. The matrix is constructed by iterating over all nodes in the mesh and setting the coordinates for the degrees of freedom (DOFs) associated with each node and its connected edges or faces, depending on the mesh dimension.
Note
This implementation is specific to 2D and 3D meshes.
Definition at line 29 of file CooBiliAssembly.cc.
References m_nb_edge, m_node_node_via_edge_connectivity, and m_queue.
Referenced by _assembleCooBilinearOperatorTETRA4(), and _assembleCooBilinearOperatorTRIA3().
_buildMatrixCooGPU()
void FemModuleTestlab::_buildMatrixCooGPU ()
The _fillMatrix and _fillDiagonal functions can be used in association with the dead-code present in _buildMatrixCooGPU to build the sparsity of the matrix.
They are commented as the arrays their produced are not sorted, making the index search of the assembly phase very slow.
This dead-code can be used to build the sparsity by iterating of the edges (see Pull Request #174 of arcaneFEM project on GitHub)
It is commented as the arrays it produces is not sorted, making the index search of the assembly phase very slow.
Definition at line 76 of file CooGpuBiliAssembly.cc.
References m_nb_edge, m_node_node_via_edge_connectivity, and m_queue.
_buildMatrixCooSort()
void FemModuleTestlab::_buildMatrixCooSort () private
Builds the COO Sort matrix by first filling the diagonal and then the off-diagonal entries.
This method initializes the diagonal elements of the matrix and then proceeds to fill the remaining entries based on the connectivity of the mesh entities (nodes, edges, faces). After filling the matrix, a sorting step is performed to optimize further operations.
Note
This implementation is specific to 2D and 3D meshes.
Definition at line 30 of file CooSortBiliAssembly.cc.
References m_nb_edge, m_node_node_via_edge_connectivity, and m_queue.
Referenced by _assembleCooSortBilinearOperatorTETRA4(), and _assembleCooSortBilinearOperatorTRIA3().
_buildMatrixCooSortGPU()
void FemModuleTestlab::_buildMatrixCooSortGPU ()
Definition at line 30 of file CooSortGpuBiliAssembly.cc.
_buildMatrixCsr()
void FemModuleTestlab::_buildMatrixCsr () private
Initialization of the csr matrix. It only works for p=1 since there is one node per Edge.
Definition at line 23 of file CsrBiliAssembly.cc.
References m_nb_edge, m_node_node_via_edge_connectivity, and m_queue.
_buildMatrixGpuBuildLessCsr()
void FemModuleTestlab::_buildMatrixGpuBuildLessCsr ()
Definition at line 62 of file BlCsrBiliAssembly.cc.
_buildMatrixNodeWiseCsr()
void FemModuleTestlab::_buildMatrixNodeWiseCsr ()
Definition at line 115 of file NodeWiseCsrBiliAssembly.cc.
_buildOffsetsNodeWiseCsr()
void FemModuleTestlab::_buildOffsetsNodeWiseCsr (const SmallSpan< UInt32 > & offsets_smallspan)
Builds the node-wise CSR matrix for the finite element method.
This function initializes and fills the CSR (Compressed Sparse Row) matrix based on the node-wise connectivity of the mesh. It supports different mesh types, specifically "TRIA3" and "TETRA4".
For "TRIA3" mesh type, the function iterates over all nodes and sets the coordinates in the CSR matrix based on the node's faces.
For "TETRA4" mesh type, the function iterates over all nodes and sets the coordinates in the CSR matrix based on the node's edges.
The function also initializes the memory space required for the CSR matrix based on the number of nodes and edges/faces in the mesh.
Definition at line 90 of file NodeWiseCsrBiliAssembly.cc.
References m_node_node_via_edge_connectivity.
_checkCellType()
void FemModuleTestlab::_checkCellType () private
Definition at line 682 of file testlab/FemModule.cc.
_checkResultFile()
void FemModuleTestlab::_checkResultFile () private
Definition at line 2069 of file testlab/FemModule.cc.
_computeAreaTetra4()
Real FemModuleTestlab::_computeAreaTetra4 (Cell cell) private
Definition at line 1803 of file testlab/FemModule.cc.
_computeAreaTetra4Gpu()
__host__ __device__ Real FemModuleTestlab::_computeAreaTetra4Gpu (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord) static
Definition at line 1734 of file testlab/FemModule.cc.
_computeAreaTriangle3()
Real FemModuleTestlab::_computeAreaTriangle3 (Cell cell) private
Definition at line 1768 of file testlab/FemModule.cc.
_computeAreaTriangle3Gpu()
__host__ __device__ Real FemModuleTestlab::_computeAreaTriangle3Gpu (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord) static
Definition at line 1755 of file testlab/FemModule.cc.
_computeCellMatrixGpuTETRA4()
__host__ __device__ Real FemModuleTestlab::_computeCellMatrixGpuTETRA4 (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord, Real b_matrix[12]) inline static
Definition at line 498 of file testlab/FemModule.h.
_computeCellMatrixGpuTRIA3()
__host__ __device__ Real FemModuleTestlab::_computeCellMatrixGpuTRIA3 (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord, Real b_matrix[6]) inline static
Definition at line 469 of file testlab/FemModule.h.
_computeColumns()
void FemModuleTestlab::_computeColumns (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< uint64_t > & sorted_edges_ss)
Definition at line 142 of file CsrGpuBiliAssembly.cc.
_computeEdgeLength2()
Real FemModuleTestlab::_computeEdgeLength2 (Face face) private
Definition at line 1792 of file testlab/FemModule.cc.
_computeEdgeLength2Gpu()
__host__ __device__ Real FemModuleTestlab::_computeEdgeLength2Gpu (FaceLocalId iface, IndexedFaceNodeConnectivityView fnc, ax::VariableNodeReal3InView in_node_coord) static
Definition at line 1781 of file testlab/FemModule.cc.
_computeEdgeNormal2()
Real2 FemModuleTestlab::_computeEdgeNormal2 (Face face) private
Definition at line 1846 of file testlab/FemModule.cc.
_computeEdgeNormal2Gpu()
__host__ __device__ Real2 FemModuleTestlab::_computeEdgeNormal2Gpu (FaceLocalId iface, IndexedFaceNodeConnectivityView fnc, ax::VariableNodeReal3InView in_node_coord, FaceInfoListView faces_infos) static
Definition at line 1824 of file testlab/FemModule.cc.
_computeElementMatrixTETRA4()
RealMatrix< 4, 4 > FemModuleTestlab::_computeElementMatrixTETRA4 (Cell cell) private
Definition at line 1909 of file testlab/FemModule.cc.
_computeElementMatrixTETRA4GPU()
__host__ __device__ void FemModuleTestlab::_computeElementMatrixTETRA4GPU (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord, Real K_e[16]) inline static
Definition at line 398 of file testlab/FemModule.h.
_computeElementMatrixTRIA3()
RealMatrix< 3, 3 > FemModuleTestlab::_computeElementMatrixTRIA3 (Cell cell) private
Definition at line 1863 of file testlab/FemModule.cc.
_computeElementMatrixTRIA3GPU()
__host__ __device__ void FemModuleTestlab::_computeElementMatrixTRIA3GPU (CellLocalId icell, IndexedCellNodeConnectivityView cnc, ax::VariableNodeReal3InView in_node_coord, Real K_e[9]) inline static
Definition at line 342 of file testlab/FemModule.h.
_computeNeighbors()
void FemModuleTestlab::_computeNeighbors (Int8 edges_per_element, Int64 nb_edge_total, NumArray< Int32, MDDim1 > & neighbors, SmallSpan< UInt64 > & sorted_edges_ss)
Definition at line 96 of file CsrGpuBiliAssembly.cc.
_computeRowIndex()
void FemModuleTestlab::_computeRowIndex (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > & sorted_edges_ss)
Definition at line 117 of file CsrGpuBiliAssembly.cc.
_computeSortedEdges()
void FemModuleTestlab::_computeSortedEdges (Int8 edges_per_element, Int64 nb_edge_total, SmallSpan< UInt64 > & sorted_edges_ss)
Definition at line 42 of file CsrGpuBiliAssembly.cc.
_computeSparsity()
void FemModuleTestlab::_computeSparsity ()
Definition at line 187 of file CsrGpuBiliAssembly.cc.
_doStationarySolve()
void FemModuleTestlab::_doStationarySolve ()
Definition at line 320 of file testlab/FemModule.cc.
_dumpTimeStats()
void FemModuleTestlab::_dumpTimeStats () private
Definition at line 19 of file testlab/FemModule.cc.
_getMaterialParameters()
void FemModuleTestlab::_getMaterialParameters () private
Definition at line 564 of file testlab/FemModule.cc.
_getValIndexCsrGpu()
__host__ __device__ Int32 FemModuleTestlab::_getValIndexCsrGpu (Int32 begin, Int32 end, DoFLocalId col, ax::NumArrayView< DataViewGetter< Int32 >, MDDim1, DefaultLayout > csr_col) static
Definition at line 1173 of file testlab/FemModule.cc.
_handleFlags()
void FemModuleTestlab::_handleFlags () private
Definition at line 168 of file testlab/FemModule.cc.
_initBoundaryconditions()
void FemModuleTestlab::_initBoundaryconditions () private
Definition at line 583 of file testlab/FemModule.cc.
_isMasterRank()
bool FemModuleTestlab::_isMasterRank () const private
Definition at line 2090 of file testlab/FemModule.cc.
_printArcaneFemTime()
void FemModuleTestlab::_printArcaneFemTime (const String label, const Real value) private
Function to prints the execution time value of phase label
Definition at line 2102 of file testlab/FemModule.cc.
Referenced by compute(), and startInit().
_setPetscFlagsFromCommandline()
void FemModuleTestlab::_setPetscFlagsFromCommandline () private
Function to set Petsc flags from commandline.
Definition at line 2114 of file testlab/FemModule.cc.
Referenced by compute().
_solve()
void FemModuleTestlab::_solve () private
Definition at line 1975 of file testlab/FemModule.cc.
_translateRhs()
void FemModuleTestlab::_translateRhs () private
Definition at line 1714 of file testlab/FemModule.cc.
compute()
void FemModuleTestlab::compute () override
Method called at each iteration.
Definition at line 67 of file testlab/FemModule.cc.
References _printArcaneFemTime(), _setPetscFlagsFromCommandline(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
endModule()
void FemModuleTestlab::endModule () override
Method called at the end of the simulation.
Definition at line 61 of file testlab/FemModule.cc.
startInit()
void FemModuleTestlab::startInit () override
Method called at the beginning of the simulation.
Definition at line 107 of file testlab/FemModule.cc.
References _printArcaneFemTime(), Arcane::FemUtils::FemDoFsOnNodes::initialize(), m_nb_edge, m_node_node_via_edge_connectivity, and m_queue.
versionInfo()
VersionInfo FemModuleTestlab::versionInfo () const inline override
Definition at line 150 of file testlab/FemModule.h.
Member Data Documentation
cache_index
Integer FemModuleTestlab::cache_index private
Definition at line 195 of file testlab/FemModule.h.
ElementNodes
Real FemModuleTestlab::ElementNodes private
Definition at line 158 of file testlab/FemModule.h.
f
Real FemModuleTestlab::f private
Definition at line 157 of file testlab/FemModule.h.
m_arcane_timer
bool FemModuleTestlab::m_arcane_timer = false private
Definition at line 168 of file testlab/FemModule.h.
m_bsr_format
BSRFormat FemModuleTestlab::m_bsr_format private
Definition at line 191 of file testlab/FemModule.h.
m_cache_warming
Integer FemModuleTestlab::m_cache_warming = 1 private
Definition at line 169 of file testlab/FemModule.h.
m_coo_matrix
CooFormat FemModuleTestlab::m_coo_matrix private
Definition at line 187 of file testlab/FemModule.h.
m_cross_validation
bool FemModuleTestlab::m_cross_validation = true private
Definition at line 183 of file testlab/FemModule.h.
m_csr_matrix
CsrFormat FemModuleTestlab::m_csr_matrix private
Definition at line 189 of file testlab/FemModule.h.
m_dof_family
IItemFamily* FemModuleTestlab::m_dof_family = nullptr private
Definition at line 161 of file testlab/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleTestlab::m_dofs_on_nodes private
Definition at line 162 of file testlab/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleTestlab::m_linear_system private
Definition at line 160 of file testlab/FemModule.h.
m_matrix_format
String FemModuleTestlab::m_matrix_format = "DOK" private
Definition at line 165 of file testlab/FemModule.h.
m_nb_edge
Int64 FemModuleTestlab::m_nb_edge = -1 private
Number of edges (only for 3D meshes)
Definition at line 203 of file testlab/FemModule.h.
Referenced by _buildMatrixCoo(), _buildMatrixCooGPU(), _buildMatrixCooSort(), _buildMatrixCsr(), and startInit().
m_node_node_via_edge_connectivity
Ref<IIndexedIncrementalItemConnectivity> FemModuleTestlab::m_node_node_via_edge_connectivity private
List of nodes connected to an another node via a edge of the a cell.
Definition at line 200 of file testlab/FemModule.h.
Referenced by _buildMatrixCoo(), _buildMatrixCooGPU(), _buildMatrixCooSort(), _buildMatrixCsr(), _buildOffsetsNodeWiseCsr(), and startInit().
m_petsc_flags
String FemModuleTestlab::m_petsc_flags private
Definition at line 164 of file testlab/FemModule.h.
m_queue
RunQueue FemModuleTestlab::m_queue private
Default queue used for computation.
Definition at line 206 of file testlab/FemModule.h.
Referenced by _assembleCsrGPUBilinearOperatorTETRA4(), _buildMatrixCoo(), _buildMatrixCooGPU(), _buildMatrixCooSort(), _buildMatrixCsr(), and startInit().
m_register_time
bool FemModuleTestlab::m_register_time = false private
Definition at line 167 of file testlab/FemModule.h.
m_rhs_vect
NumArray<Real, MDDim1> FemModuleTestlab::m_rhs_vect private
Definition at line 193 of file testlab/FemModule.h.
m_running_on_gpu
bool FemModuleTestlab::m_running_on_gpu = false private
Definition at line 181 of file testlab/FemModule.h.
m_solve_linear_system
bool FemModuleTestlab::m_solve_linear_system = true private
Definition at line 182 of file testlab/FemModule.h.
m_time_stats
ITimeStats* FemModuleTestlab::m_time_stats private
Definition at line 185 of file testlab/FemModule.h.
m_use_bsr
bool FemModuleTestlab::m_use_bsr = false private
Definition at line 179 of file testlab/FemModule.h.
m_use_bsr_atomic_free
bool FemModuleTestlab::m_use_bsr_atomic_free = false private
Definition at line 180 of file testlab/FemModule.h.
m_use_buildless_csr
bool FemModuleTestlab::m_use_buildless_csr = false private
Definition at line 177 of file testlab/FemModule.h.
m_use_coo
bool FemModuleTestlab::m_use_coo = false private
Definition at line 170 of file testlab/FemModule.h.
m_use_coo_gpu
bool FemModuleTestlab::m_use_coo_gpu = false private
Definition at line 172 of file testlab/FemModule.h.
m_use_coo_sort
bool FemModuleTestlab::m_use_coo_sort = false private
Definition at line 171 of file testlab/FemModule.h.
m_use_coo_sort_gpu
bool FemModuleTestlab::m_use_coo_sort_gpu = false private
Definition at line 173 of file testlab/FemModule.h.
m_use_csr
bool FemModuleTestlab::m_use_csr = false private
Definition at line 174 of file testlab/FemModule.h.
m_use_csr_gpu
bool FemModuleTestlab::m_use_csr_gpu = false private
Definition at line 175 of file testlab/FemModule.h.
m_use_legacy
bool FemModuleTestlab::m_use_legacy = true private
Definition at line 178 of file testlab/FemModule.h.
m_use_nodewise_csr
bool FemModuleTestlab::m_use_nodewise_csr = false private
Definition at line 176 of file testlab/FemModule.h.
The documentation for this class was generated from the following files:
testlab/FemModule.h
BlCsrBiliAssembly.cc
CooBiliAssembly.cc
CooGpuBiliAssembly.cc
CooSortBiliAssembly.cc
CooSortGpuBiliAssembly.cc
CsrBiliAssembly.cc
CsrGpuBiliAssembly.cc
testlab/FemModule.cc
LegacyBiliAssembly.cc
NodeWiseCsrBiliAssembly.cc