ArcaneFem: ArcaneFemFunctions::GeneralFunctions Class Reference
ArcaneFemFunctions::GeneralFunctions Class Reference
Provides general purpose fuctions.
#include <femutils/ArcaneFemFunctions.h>
Static Public Member Functions
static void printArcaneFemTime (ITraceMng *tm, const String &label, const Real &value)
Logs the execution time with ArcaneFem-Timer.
static CommandLineArguments getPetscFlagsFromCommandline (const String &petsc_flags)
Parses Petsc command-line flags into a CommandLineArguments object.
Detailed Description
Provides general purpose fuctions.
Definition at line 52 of file ArcaneFemFunctions.h.
Member Function Documentation
getPetscFlagsFromCommandline()
static CommandLineArguments ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline (const String & petsc_flags) inline static
Parses Petsc command-line flags into a CommandLineArguments object.
This method processes a space-separated string of Petsc flags and converts it into a list of individual arguments. We do the following:
Convert the input String to a standard C++ string.
Use a string stream to tokenize the input based on spaces.
Store the tokens in a StringList.
Return a CommandLineArguments object constructed from the StringList.
Parameters
`petsc_flags` space-separated string containing Petsc CLI flags.
Returns
A CommandLineArguments object containing the parsed flags.
Definition at line 87 of file ArcaneFemFunctions.h.
Referenced by FemModuleAcoustics::compute(), FemModuleAerodynamics::compute(), FemModuleBilaplacian::compute(), FemModuleElasticity::compute(), FemModuleElastodynamics::compute(), FemModuleElectrostatics::compute(), FemModuleFourier::compute(), FemModuleFourierNL::compute(), FemModuleHeat::compute(), FemModuleLaplace::compute(), FemModulePoisson::compute(), and FemModuleSoildynamics::compute().
printArcaneFemTime()
static void ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime (ITraceMng * tm, const String & label, const Real & value) inline static
Logs the execution time with ArcaneFem-Timer.
Parameters
tm The Arcane trace manager for logging.
label A short description of the event being timed.
value The elapsed time associated with the event.
Definition at line 65 of file ArcaneFemFunctions.h.
Referenced by FemModuleAcoustics::_assembleBilinearOperator(), FemModuleAerodynamics::_assembleBilinearOperator(), FemModuleBilaplacian::_assembleBilinearOperator(), FemModuleElasticity::_assembleBilinearOperator(), FemModuleElectrostatics::_assembleBilinearOperator(), FemModuleFourier::_assembleBilinearOperator(), FemModuleFourierNL::_assembleBilinearOperator(), FemModuleHeat::_assembleBilinearOperator(), FemModuleLaplace::_assembleBilinearOperator(), FemModulePoisson::_assembleBilinearOperator(), FemModuleAcoustics::_assembleLinearOperator(), FemModuleBilaplacian::_assembleLinearOperator(), FemModuleElasticity::_assembleLinearOperator(), FemModuleAerodynamics::_assembleLinearOperatorCpu(), FemModuleElectrostatics::_assembleLinearOperatorCpu(), FemModuleFourier::_assembleLinearOperatorCpu(), FemModuleFourierNL::_assembleLinearOperatorCpu(), FemModuleLaplace::_assembleLinearOperatorCpu(), FemModulePoisson::_assembleLinearOperatorCpu(), FemModuleAerodynamics::_assembleLinearOperatorGpu(), FemModuleElectrostatics::_assembleLinearOperatorGpu(), FemModuleFourier::_assembleLinearOperatorGpu(), FemModuleFourierNL::_assembleLinearOperatorGpu(), FemModuleLaplace::_assembleLinearOperatorGpu(), FemModulePoisson::_assembleLinearOperatorGpu(), FemModulePoisson::_assembleLinearSystem(), FemModuleFourierNL::_checkConvergence(), FemModuleBilaplacian::_checkResultFile(), FemModuleFourierNL::_checkSolution(), FemModuleBilaplacian::_getMaterialParameters(), FemModuleElasticity::_getMaterialParameters(), FemModuleElectrostatics::_getMaterialParameters(), FemModuleFourier::_getMaterialParameters(), FemModulePoisson::_getMaterialParameters(), FemModuleElasticity::_initBsr(), FemModuleAcoustics::_solve(), FemModuleBilaplacian::_solve(), FemModuleElasticity::_solve(), FemModuleElectrostatics::_solve(), FemModuleFourier::_solve(), FemModuleFourierNL::_solve(), FemModuleLaplace::_solve(), FemModulePoisson::_solve(), FemModuleFourierNL::_updateExactSolution(), FemModuleFourierNL::_updatePreviousIterationVariables(), FemModuleFourierNL::_updateSolutionFromVariables(), FemModuleAcoustics::_updateVariables(), FemModuleAerodynamics::_updateVariables(), FemModuleElasticity::_updateVariables(), FemModuleElectrostatics::_updateVariables(), FemModuleFourier::_updateVariables(), FemModuleLaplace::_updateVariables(), FemModulePoisson::_updateVariables(), FemModuleFourierNL::_updateVariables(), FemModuleAcoustics::_validateResults(), FemModuleAerodynamics::_validateResults(), FemModuleElectrostatics::_validateResults(), FemModuleFourier::_validateResults(), FemModuleFourierNL::_validateResults(), FemModuleLaplace::_validateResults(), FemModulePoisson::_validateResults(), FemModuleAcoustics::compute(), FemModuleAerodynamics::compute(), FemModuleBilaplacian::compute(), FemModuleElasticity::compute(), FemModuleElastodynamics::compute(), FemModuleElectrostatics::compute(), FemModuleFourier::compute(), FemModuleFourierNL::compute(), FemModuleHeat::compute(), FemModuleLaplace::compute(), FemModulePoisson::compute(), FemModuleSoildynamics::compute(), FemModuleAcoustics::startInit(), FemModuleAerodynamics::startInit(), FemModuleBilaplacian::startInit(), FemModuleElasticity::startInit(), FemModuleElastodynamics::startInit(), FemModuleElectrostatics::startInit(), FemModuleFourier::startInit(), FemModuleFourierNL::startInit(), FemModuleHeat::startInit(), FemModuleLaplace::startInit(), and FemModulePoisson::startInit().
The documentation for this class was generated from the following file:
ArcaneFemFunctions.h