ArcaneFem: Arcane::FemUtils::DoFLinearSystem Class Reference
Arcane::FemUtils::DoFLinearSystem Class Reference
Linear system Matrix A + Vector x + Vector b for Ax=b.
#include <femutils/DoFLinearSystem.h>
Public Member Functions
DoFLinearSystem (const DoFLinearSystem &)=delete
DoFLinearSystem (DoFLinearSystem &&)=delete
DoFLinearSystem & operator= (DoFLinearSystem &&)=delete
DoFLinearSystem & operator= (const DoFLinearSystem &)=delete
void initialize (ISubDomain *sd, IItemFamily *dof_family, const String &solver_name)
void initialize (ISubDomain *sd, Runner *runner, IItemFamily *dof_family, const String &solver_name)
Initialize the instance with a specific runner.
bool isInitialized () const
Indicate if method initialize() has been called.
void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value)
Add the value value to the (row,column) element of the matrix.
void matrixSetValue (DoFLocalId row, DoFLocalId column, Real value)
Set the value value to the (row,column) element of the matrix.
DoFLinearSystemRowEliminationHelper rowEliminationHelper ()
DoFLinearSystemRowColumnEliminationHelper rowColumnEliminationHelper ()
void applyLinearSystemTransformationAndSolve ()
Apply the underlying transformation and Solve the current linear system.
void applyMatrixTransformation ()
Apply Matrix Transformation.
void applyRHSTransformation ()
Apply RHS Transformation.
void solve ()
Solve the current linear system.
void reset ()
Reset the current instance.
void clearValues ()
Clear values.
VariableDoFReal & solutionVariable ()
Variable containing the solution vector.
VariableDoFReal & rhsVariable ()
Variable containing the right hand side vector.
void setLinearSystemFactory (IDoFLinearSystemFactory *factory)
Set the factory used to create the underlying linear system solver.
void setSolverCommandLineArguments (const CommandLineArguments &args)
void setCSRValues (const CSRFormatView &csr_view)
Positionne directement les valeurs de la matrice.
bool hasSetCSRValues () const
Indique si l'implémentation supporte d'utiliser setCSRValue()
CSRFormatView & getCSRValues ()
VariableDoFReal & getForcedValue ()
VariableDoFBool & getForcedInfo ()
IDoFLinearSystemFactory * linearSystemFactory () const
Private Member Functions
void _checkInit () const
void _eliminateRow (DoFLocalId row, Real value)
void _eliminateRowColumn (DoFLocalId row, Real value)
VariableDoFByte & _getEliminationInfo ()
VariableDoFReal & _getEliminationValue ()
Private Attributes
friend DoFLinearSystemRowEliminationHelper
friend DoFLinearSystemRowColumnEliminationHelper
IDoFLinearSystemImpl * m_p = nullptr
IItemFamily * m_item_family = nullptr
IDoFLinearSystemFactory * m_linear_system_factory = nullptr
IDoFLinearSystemFactory * m_default_linear_system_factory = nullptr
Detailed Description
Linear system Matrix A + Vector x + Vector b for Ax=b.
Before using an instance of this class you need to call method initialize(). If you want to reuse the same instance for several solving you need to call reset() to destroy the underlying linear system and then you need to call initialize() again.
The solve() method solves the current linear system. After this variable returned by the method solutionVariable() will be filled with the values of the solution vector.
Definition at line 154 of file DoFLinearSystem.h.
Constructor & Destructor Documentation
DoFLinearSystem()
Arcane::FemUtils::DoFLinearSystem::DoFLinearSystem ()
Definition at line 319 of file DoFLinearSystem.cc.
~DoFLinearSystem()
Arcane::FemUtils::DoFLinearSystem::~DoFLinearSystem ()
Definition at line 327 of file DoFLinearSystem.cc.
Member Function Documentation
_checkInit()
void Arcane::FemUtils::DoFLinearSystem::_checkInit () const private
Definition at line 337 of file DoFLinearSystem.cc.
_eliminateRow()
void Arcane::FemUtils::DoFLinearSystem::_eliminateRow (DoFLocalId row, Real value) private
Definition at line 399 of file DoFLinearSystem.cc.
_eliminateRowColumn()
void Arcane::FemUtils::DoFLinearSystem::_eliminateRowColumn (DoFLocalId row, Real value) private
Definition at line 408 of file DoFLinearSystem.cc.
_getEliminationInfo()
VariableDoFByte & Arcane::FemUtils::DoFLinearSystem::_getEliminationInfo () private
Definition at line 545 of file DoFLinearSystem.cc.
_getEliminationValue()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystem::_getEliminationValue () private
Definition at line 555 of file DoFLinearSystem.cc.
applyLinearSystemTransformationAndSolve()
void Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve ()
Apply the underlying transformation and Solve the current linear system.
This is equivalent to calling the following methods in order:
applyMatrixTransformation()
applyRHSTransformation()
solve()
Definition at line 467 of file DoFLinearSystem.cc.
References applyMatrixTransformation(), applyRHSTransformation(), and solve().
Referenced by FemModuleAcoustics::_solve(), FemModuleBilaplacian::_solve(), FemModuleElasticity::_solve(), FemModuleElectrostatics::_solve(), FemModuleFourier::_solve(), FemModuleLaplace::_solve(), and FemModulePoisson::_solve().
applyMatrixTransformation()
void Arcane::FemUtils::DoFLinearSystem::applyMatrixTransformation ()
Apply Matrix Transformation.
Apply operation like Row or RowColumn elimination on the matrix. This has to be done one and only time before calling solve(). If the values of the matrix are cleared, this method has to be called again.
Definition at line 447 of file DoFLinearSystem.cc.
Referenced by applyLinearSystemTransformationAndSolve().
applyRHSTransformation()
void Arcane::FemUtils::DoFLinearSystem::applyRHSTransformation ()
Apply RHS Transformation.
Apply operation like Row or RowColumn elimination on the RHS. This method has to be called at least one time calling solve(). You may call this method several time if you have manually changed the values of the RHS.
Definition at line 457 of file DoFLinearSystem.cc.
Referenced by applyLinearSystemTransformationAndSolve().
clearValues()
void Arcane::FemUtils::DoFLinearSystem::clearValues ()
Clear values.
After this call, the matrix and the RHS vector will have their values cleared.
Definition at line 586 of file DoFLinearSystem.cc.
Referenced by FemModuleElasticity::compute(), FemModuleElastodynamics::compute(), FemModuleHeat::compute(), ElastodynamicModule::compute(), NLDynamicModule::compute(), and FemModuleSoildynamics::compute().
getCSRValues()
CSRFormatView & Arcane::FemUtils::DoFLinearSystem::getCSRValues ()
Definition at line 518 of file DoFLinearSystem.cc.
getForcedInfo()
VariableDoFBool & Arcane::FemUtils::DoFLinearSystem::getForcedInfo ()
Definition at line 536 of file DoFLinearSystem.cc.
getForcedValue()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystem::getForcedValue ()
Definition at line 527 of file DoFLinearSystem.cc.
hasSetCSRValues()
bool Arcane::FemUtils::DoFLinearSystem::hasSetCSRValues () const
Indique si l'implémentation supporte d'utiliser setCSRValue()
Definition at line 565 of file DoFLinearSystem.cc.
Referenced by Arcane::FemUtils::CsrFormat::translateToLinearSystem().
initialize() [1/2]
void Arcane::FemUtils::DoFLinearSystem::initialize (ISubDomain * sd, IItemFamily * dof_family, const String & solver_name)
Definition at line 370 of file DoFLinearSystem.cc.
initialize() [2/2]
void Arcane::FemUtils::DoFLinearSystem::initialize (ISubDomain * sd, Runner * runner, IItemFamily * dof_family, const String & solver_name)
Initialize the instance with a specific runner.
runner may be null.
Definition at line 347 of file DoFLinearSystem.cc.
isInitialized()
bool Arcane::FemUtils::DoFLinearSystem::isInitialized () const
Indicate if method initialize() has been called.
Definition at line 596 of file DoFLinearSystem.cc.
Referenced by FemModuleElastodynamics::compute(), FemModuleHeat::compute(), ElastodynamicModule::compute(), NLDynamicModule::compute(), and FemModuleSoildynamics::compute().
linearSystemFactory()
IDoFLinearSystemFactory * Arcane::FemUtils::DoFLinearSystem::linearSystemFactory () const inline
Definition at line 336 of file DoFLinearSystem.h.
matrixAddValue()
void Arcane::FemUtils::DoFLinearSystem::matrixAddValue (DoFLocalId row, DoFLocalId column, Real value)
Add the value value to the (row,column) element of the matrix.
Definition at line 379 of file DoFLinearSystem.cc.
Referenced by FemModuleSoildynamics::_applyParaxial(), FemModuleAcoustics::_assembleBilinear(), FemModuleAerodynamics::_assembleBilinear(), FemModuleElectrostatics::_assembleBilinear(), FemModuleFourier::_assembleBilinear(), FemModuleHeat::_assembleBilinear(), FemModuleLaplace::_assembleBilinear(), FemModulePoisson::_assembleBilinear(), FemModuleBilaplacian::_assembleBilinearOperator(), FemModuleElasticity::_assembleBilinearOperatorCpu(), FemModuleElastodynamics::_assembleBilinearOperatorCpu(), FemModuleSoildynamics::_assembleBilinearOperatorCpu(), Arcane::FemUtils::CooFormat::translateToLinearSystem(), and Arcane::FemUtils::CsrFormat::translateToLinearSystem().
matrixSetValue()
void Arcane::FemUtils::DoFLinearSystem::matrixSetValue (DoFLocalId row, DoFLocalId column, Real value)
Set the value value to the (row,column) element of the matrix.
The value is only changed when solve() is called. Any call to matrixAddValue(row,column) done before or after the call to matrixSetValue(row,column) are discarded.
Definition at line 389 of file DoFLinearSystem.cc.
Referenced by FemModuleBilaplacian::_assembleLinearOperator(), FemModuleAerodynamics::_assembleLinearOperatorCpu(), ArcaneFemFunctions::BoundaryConditions3D::applyManufacturedDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions2D::applyManufacturedDirichletToLhsAndRhs().
reset()
void Arcane::FemUtils::DoFLinearSystem::reset ()
Reset the current instance.
You have to call initialize() again to re-use the same instance.
Definition at line 575 of file DoFLinearSystem.cc.
Referenced by FemModuleAcoustics::compute(), FemModuleAerodynamics::compute(), FemModuleBilaplacian::compute(), FemModuleElasticity::compute(), FemModuleElastodynamics::compute(), FemModuleElectrostatics::compute(), FemModuleFourier::compute(), FemModuleHeat::compute(), FemModuleLaplace::compute(), ElastodynamicModule::compute(), NLDynamicModule::compute(), FemModulePoisson::compute(), FemModuleSoildynamics::compute(), FemModuleTestlab::compute(), ElastodynamicModule::startInit(), and NLDynamicModule::startInit().
rhsVariable()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystem::rhsVariable ()
Variable containing the right hand side vector.
The values of this variable will be used during the solve() call to fill the right hand side vector.
Definition at line 488 of file DoFLinearSystem.cc.
Referenced by FemModuleAcoustics::_assembleLinearOperator(), FemModuleBilaplacian::_assembleLinearOperator(), FemModuleElasticity::_assembleLinearOperator(), FemModuleAerodynamics::_assembleLinearOperatorCpu(), FemModuleElectrostatics::_assembleLinearOperatorCpu(), FemModuleFourier::_assembleLinearOperatorCpu(), FemModuleLaplace::_assembleLinearOperatorCpu(), FemModulePoisson::_assembleLinearOperatorCpu(), FemModuleAerodynamics::_assembleLinearOperatorGpu(), FemModuleElectrostatics::_assembleLinearOperatorGpu(), FemModuleFourier::_assembleLinearOperatorGpu(), FemModuleLaplace::_assembleLinearOperatorGpu(), and FemModulePoisson::_assembleLinearOperatorGpu().
rowColumnEliminationHelper()
DoFLinearSystemRowColumnEliminationHelper Arcane::FemUtils::DoFLinearSystem::rowColumnEliminationHelper ()
Definition at line 427 of file DoFLinearSystem.cc.
rowEliminationHelper()
DoFLinearSystemRowEliminationHelper Arcane::FemUtils::DoFLinearSystem::rowEliminationHelper ()
Definition at line 417 of file DoFLinearSystem.cc.
setCSRValues()
void Arcane::FemUtils::DoFLinearSystem::setCSRValues (const CSRFormatView & csr_view)
Positionne directement les valeurs de la matrice.
Positionne les valeurs de la matrice en considérant le format comme étant au format CSR. Les vues doivent rester valides jusqu'à la résolution du système linéaire (appel à solve()).
Definition at line 508 of file DoFLinearSystem.cc.
Referenced by Arcane::FemUtils::CsrFormat::translateToLinearSystem().
setLinearSystemFactory()
void Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory (IDoFLinearSystemFactory * factory) inline
Set the factory used to create the underlying linear system solver.
Definition at line 298 of file DoFLinearSystem.h.
Referenced by FemModuleAcoustics::compute(), FemModuleAerodynamics::compute(), FemModuleBilaplacian::compute(), FemModuleElasticity::compute(), FemModuleElastodynamics::compute(), FemModuleElectrostatics::compute(), FemModuleFourier::compute(), FemModuleHeat::compute(), FemModuleLaplace::compute(), ElastodynamicModule::compute(), NLDynamicModule::compute(), FemModulePoisson::compute(), FemModuleSoildynamics::compute(), FemModuleTestlab::compute(), ElastodynamicModule::startInit(), and NLDynamicModule::startInit().
setSolverCommandLineArguments()
void Arcane::FemUtils::DoFLinearSystem::setSolverCommandLineArguments (const CommandLineArguments & args)
Definition at line 498 of file DoFLinearSystem.cc.
solutionVariable()
VariableDoFReal & Arcane::FemUtils::DoFLinearSystem::solutionVariable ()
Variable containing the solution vector.
The values of this variable are only relevant after a call to solve().
Definition at line 478 of file DoFLinearSystem.cc.
Referenced by FemModuleAcoustics::_updateVariables(), FemModuleAerodynamics::_updateVariables(), FemModuleBilaplacian::_updateVariables(), FemModuleElasticity::_updateVariables(), FemModuleElectrostatics::_updateVariables(), FemModuleFourier::_updateVariables(), FemModuleLaplace::_updateVariables(), and FemModulePoisson::_updateVariables().
solve()
void Arcane::FemUtils::DoFLinearSystem::solve ()
Solve the current linear system.
You have to call applyMatrixTransformation() and applyRHSTransformation() before calling this method().
Definition at line 437 of file DoFLinearSystem.cc.
Referenced by applyLinearSystemTransformationAndSolve().
Member Data Documentation
DoFLinearSystemRowColumnEliminationHelper
friend Arcane::FemUtils::DoFLinearSystem::DoFLinearSystemRowColumnEliminationHelper private
Definition at line 157 of file DoFLinearSystem.h.
DoFLinearSystemRowEliminationHelper
friend Arcane::FemUtils::DoFLinearSystem::DoFLinearSystemRowEliminationHelper private
Definition at line 156 of file DoFLinearSystem.h.
m_default_linear_system_factory
IDoFLinearSystemFactory* Arcane::FemUtils::DoFLinearSystem::m_default_linear_system_factory = nullptr private
Definition at line 346 of file DoFLinearSystem.h.
m_item_family
IItemFamily* Arcane::FemUtils::DoFLinearSystem::m_item_family = nullptr private
Definition at line 344 of file DoFLinearSystem.h.
m_linear_system_factory
IDoFLinearSystemFactory* Arcane::FemUtils::DoFLinearSystem::m_linear_system_factory = nullptr private
Definition at line 345 of file DoFLinearSystem.h.
m_p
IDoFLinearSystemImpl* Arcane::FemUtils::DoFLinearSystem::m_p = nullptr private
Definition at line 343 of file DoFLinearSystem.h.
The documentation for this class was generated from the following files:
DoFLinearSystem.h
DoFLinearSystem.cc