ArcaneFem: FemModuleElasticity Class Reference
FemModuleElasticity Class Reference
A module for finite element method.
#include <modules/elasticity/FemModule.h>
Public Member Functions
FemModuleElasticity (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleElasticity at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
void _assembleDirichletsGpu ()
Applies dirichlet to LHS matrix and RHS vector of the linear system on Gpu.
Private Member Functions
void _getMaterialParameters ()
Retrieves and sets the material parameters for the simulation.
void _solve ()
Solves the linear system.
void _assembleLinearOperator ()
Assemble the FEM linear operator.
void _validateResults ()
void _updateVariables ()
Update the FEM variables.
void _initBsr ()
Initializes BSR matrix.
void _applyBodyForce (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies body force to the RHS vector of the linear system.
void _applyTraction (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies traction to the RHS vector of the linear system.
void _applyDirichlet (VariableDoFReal &rhs_values, const IndexedNodeDoFConnectivityView &node_dof)
Applies dirichlet to LHS matrix and RHS vector of the linear system.
RealMatrix< 6, 6 > _computeElementMatrixTria3 (Cell cell)
RealMatrix< 12, 12 > _computeElementMatrixTetra4 (Cell cell)
RealMatrix< 8, 8 > _computeElementMatrixQuad4 (Cell cell)
RealMatrix< 24, 24 > _computeElementMatrixHexa8 (Cell cell)
template<int N>
void _assembleBilinearOperatorCpu (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the FEM bilinear operator on CPU.
Private Attributes
DoFLinearSystem m_linear_system
FemDoFsOnNodes m_dofs_on_nodes
BSRFormat m_bsr_format
Real E
Real nu
Real mu
Real lambda
Real3 f
Real3 t
Int8 m_dof_per_node
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_hex_quad_mesh = false
Detailed Description
A module for finite element method.
This class handles the initialization and computation for finite element method (FEM) simulations, providing methods to set up and solve linear systems, assemble FEM operators, and perform result checks.
Definition at line 60 of file elasticity/FemModule.h.
Constructor & Destructor Documentation
FemModuleElasticity()
FemModuleElasticity::FemModuleElasticity (const ModuleBuildInfo & mbi) inline explicit
Definition at line 65 of file elasticity/FemModule.h.
Member Function Documentation
_applyBodyForce()
void FemModuleElasticity::_applyBodyForce (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Applies body force to the RHS vector of the linear system.
This function computes the contribution of body forces to the RHS vector of the linear system. It iterates over all cells in the mesh, calculates the appropriate force contributions based on the element type and mesh dimension, and updates the RHS vector accordingly.
body force ∫∫∫ (𝐟.𝐯) with 𝐟 = (𝑓𝑥, 𝑓𝑦, 𝑓𝑧) = (f[0], f[1], f[2])
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding degrees of freedom (DoFs).
/*------------------------------------------------------------------------—
Definition at line 31 of file BodyForce.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), ArcaneFemFunctions::FeOperation3D::computeShapeFunctionsHexa8(), ArcaneFemFunctions::FeOperation2D::computeShapeFunctionsQuad4(), and ArcaneFemFunctions::MeshOperation::computeVolumeTetra4().
Referenced by _assembleLinearOperator().
_applyDirichlet()
void FemModuleElasticity::_applyDirichlet (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Applies dirichlet to LHS matrix and RHS vector of the linear system.
This function applies Dirichlet boundary conditions to both the LHS matrix and RHS vector of the linear system.
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 26 of file elasticity/Dirichlet.h.
References _assembleDirichletsGpu(), ArcaneFemFunctions::BoundaryConditions::applyDirichletToLhsAndRhs(), and ArcaneFemFunctions::BoundaryConditions::applyPointDirichletToLhsAndRhs().
Referenced by _assembleLinearOperator().
_applyTraction()
void FemModuleElasticity::_applyTraction (VariableDoFReal & rhs_values, const IndexedNodeDoFConnectivityView & node_dof) inline private
Applies traction to the RHS vector of the linear system.
This function computes the contribution of traction to the RHS vector of the linear system. It iterates over all cells in the mesh, calculates the appropriate force contributions based on the element type and mesh dimension, and updates the RHS vector accordingly.
traction term ∫∫ (𝐭.𝐯) with 𝐭 = (𝑡𝑥, 𝑡𝑦, 𝑡𝑧) = (t[0], t[1], t[2])
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding degrees of freedom (DoFs).
/*------------------------------------------------------------------------—
Definition at line 31 of file elasticity/Traction.h.
References ArcaneFemFunctions::BoundaryConditions3D::applyTractionToRhsTetra4(), and ArcaneFemFunctions::BoundaryConditions2D::applyTractionToRhsTria3().
Referenced by _assembleLinearOperator().
_assembleBilinearOperator()
void FemModuleElasticity::_assembleBilinearOperator ()
Calls the right function for LHS assembly given as mesh type.
Definition at line 228 of file elasticity/FemModule.cc.
References Arcane::FemUtils::BSRFormat::assembleBilinearAtomic(), Arcane::FemUtils::BSRFormat::assembleBilinearAtomicFree(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_assembleBilinearOperatorCpu()
template<int N> void FemModuleElasticity::_assembleBilinearOperatorCpu (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the FEM bilinear operator on CPU.
This method assembles the FEM stiffness matrix by iterating over each cell, computing the element stiffness matrix using the provided function, and populating the global stiffness matrix accordingly.
Template Parameters
N Total DOF size (nodes_per_element × dimensions).
Parameters
compute_element_matrix function computing cell's element stiffness matrix.
Definition at line 304 of file elasticity/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleDirichletsGpu()
void FemModuleElasticity::_assembleDirichletsGpu ()
Applies dirichlet to LHS matrix and RHS vector of the linear system on Gpu.
This function applies Dirichlet boundary conditions to both the LHS matrix and RHS vector of the linear system using GPU acceleration.
Parameters
rhs_values The variable representing the RHS vector to be updated.
node_dof The connectivity view mapping nodes to their corresponding
Definition at line 61 of file elasticity/Dirichlet.h.
Referenced by _applyDirichlet().
_assembleLinearOperator()
void FemModuleElasticity::_assembleLinearOperator () private
Assemble the FEM linear operator.
This method follows a sequence of steps to assemble RHS of FEM linear system:
assembles the bodyforce contribution (source term) ∫∫∫ (𝐟.𝐯) on Ω
assembles the traction contribution (Neumann term) ∫∫ (𝐭.𝐯) on ∂Ω
apply Dirichlet contributions to LHS and RHS
Definition at line 203 of file elasticity/FemModule.cc.
References _applyBodyForce(), _applyDirichlet(), _applyTraction(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _doStationarySolve().
_computeElementMatrixHexa8()
RealMatrix< 24, 24 > FemModuleElasticity::_computeElementMatrixHexa8 (Cell cell) private
Definition at line 189 of file elasticity/ElementMatrixHexQuad.h.
_computeElementMatrixQuad4()
RealMatrix< 8, 8 > FemModuleElasticity::_computeElementMatrixQuad4 (Cell cell) private
Definition at line 73 of file elasticity/ElementMatrixHexQuad.h.
_computeElementMatrixTetra4()
RealMatrix< 12, 12 > FemModuleElasticity::_computeElementMatrixTetra4 (Cell cell) private
Definition at line 188 of file elasticity/ElementMatrix.h.
_computeElementMatrixTria3()
RealMatrix< 6, 6 > FemModuleElasticity::_computeElementMatrixTria3 (Cell cell) private
Definition at line 75 of file elasticity/ElementMatrix.h.
_doStationarySolve()
void FemModuleElasticity::_doStationarySolve ()
Performs a stationary solve for the FEM system.
This method follows a sequence of steps to solve FEM system:
_getMaterialParameters() Retrieves material parameters via
_assembleBilinearOperator() Assembles the FEM matrix 𝐀
_assembleLinearOperator() Assembles the FEM RHS vector 𝐛
_solve() Solves for solution vector 𝐮 = 𝐀⁻¹𝐛
_updateVariables() Updates FEM variables 𝐮 = 𝐱
_validateResults() Regression test
Definition at line 140 of file elasticity/FemModule.cc.
References _assembleBilinearOperator(), _assembleLinearOperator(), _solve(), and _updateVariables().
Referenced by compute().
_getMaterialParameters()
void FemModuleElasticity::_getMaterialParameters () private
Retrieves and sets the material parameters for the simulation.
Definition at line 162 of file elasticity/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by startInit().
_initBsr()
void FemModuleElasticity::_initBsr () private
Initializes BSR matrix.
Definition at line 106 of file elasticity/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by compute().
_solve()
void FemModuleElasticity::_solve () private
Solves the linear system.
Definition at line 341 of file elasticity/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updateVariables()
void FemModuleElasticity::_updateVariables () private
Update the FEM variables.
This method performs the following actions:
Fetches values of solution from solved linear system to FEM variables, i.e., it copies RHS DOF to u.
Performs synchronize of FEM variables across subdomains.
Definition at line 395 of file elasticity/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_validateResults()
void FemModuleElasticity::_validateResults () private
Definition at line 356 of file elasticity/FemModule.cc.
compute()
void FemModuleElasticity::compute () override
Method called at the beginning of the simulation.
Performs the main computation for the FemModuleElasticity.
This method:
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Sets Petsc flags if user has provided them.
Executes the stationary solve.
Definition at line 57 of file elasticity/FemModule.cc.
References _doStationarySolve(), _initBsr(), Arcane::FemUtils::DoFLinearSystem::clearValues(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleElasticity::startInit () override
Initializes the FemModuleElasticity at the start of the simulation.
This method initializes degrees of freedom (DoFs) on nodes.
Definition at line 31 of file elasticity/FemModule.cc.
References _getMaterialParameters(), Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleElasticity::versionInfo () const inline override
Method called at each iteration.
Definition at line 77 of file elasticity/FemModule.h.
Member Data Documentation
E
Real FemModuleElasticity::E private
Definition at line 89 of file elasticity/FemModule.h.
f
Real3 FemModuleElasticity::f private
Definition at line 94 of file elasticity/FemModule.h.
lambda
Real FemModuleElasticity::lambda private
Definition at line 92 of file elasticity/FemModule.h.
m_assemble_linear_system
bool FemModuleElasticity::m_assemble_linear_system = true private
Definition at line 102 of file elasticity/FemModule.h.
m_bsr_format
BSRFormat FemModuleElasticity::m_bsr_format private
Definition at line 87 of file elasticity/FemModule.h.
m_cross_validation
bool FemModuleElasticity::m_cross_validation = false private
Definition at line 104 of file elasticity/FemModule.h.
m_dof_per_node
Int8 FemModuleElasticity::m_dof_per_node private
Definition at line 97 of file elasticity/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleElasticity::m_dofs_on_nodes private
Definition at line 86 of file elasticity/FemModule.h.
m_hex_quad_mesh
bool FemModuleElasticity::m_hex_quad_mesh = false private
Definition at line 105 of file elasticity/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleElasticity::m_linear_system private
Definition at line 85 of file elasticity/FemModule.h.
m_matrix_format
String FemModuleElasticity::m_matrix_format = "DOK" private
Definition at line 100 of file elasticity/FemModule.h.
m_petsc_flags
String FemModuleElasticity::m_petsc_flags private
Definition at line 99 of file elasticity/FemModule.h.
m_solve_linear_system
bool FemModuleElasticity::m_solve_linear_system = true private
Definition at line 103 of file elasticity/FemModule.h.
mu
Real FemModuleElasticity::mu private
Definition at line 91 of file elasticity/FemModule.h.
nu
Real FemModuleElasticity::nu private
Definition at line 90 of file elasticity/FemModule.h.
t
Real3 FemModuleElasticity::t private
Definition at line 95 of file elasticity/FemModule.h.
The documentation for this class was generated from the following files:
elasticity/FemModule.h
BodyForce.h
elasticity/Dirichlet.h
elasticity/ElementMatrix.h
elasticity/ElementMatrixHexQuad.h
elasticity/FemModule.cc
elasticity/Traction.h