ArcaneFem: Arcane::FemUtils::FemDoFsOnNodes Class Reference
Arcane::FemUtils::FemDoFsOnNodes Class Reference
Manage one or more DoFs on Nodes.
#include <femutils/FemDoFsOnNodes.h>
Classes
class Impl
Public Member Functions
FemDoFsOnNodes (Arcane::ITraceMng *tm)
FemDoFsOnNodes (const FemDoFsOnNodes &)=delete
FemDoFsOnNodes (FemDoFsOnNodes &&)=delete
FemDoFsOnNodes & operator= (FemDoFsOnNodes &&)=delete
FemDoFsOnNodes & operator= (const FemDoFsOnNodes &)=delete
void initialize (Arcane::IMesh *mesh, Arcane::Int32 nb_dof_per_node)
Initialize the instance.
Arcane::IndexedNodeDoFConnectivityView nodeDoFConnectivityView () const
Arcane::IItemFamily * dofFamily () const
Private Attributes
Impl * m_p = nullptr
Detailed Description
Manage one or more DoFs on Nodes.
Before using an instance of this class you need to call method initialize().
After initialization, you can access DoFs like that:
FemDoFsOnNodes dofs_on_nodes = ...;
auto node_dof(m_dofs_on_nodes.nodeDoFConnectivityView());
Node node = ...
DoFLocalId dof0 = node_dof.dofId(node, 0); //< First DoF of the node
DoFLocalId dof1 = node_dof.dofId(node, 1); //< Second DoF of the node
Definition at line 45 of file FemDoFsOnNodes.h.
Constructor & Destructor Documentation
~FemDoFsOnNodes()
Arcane::FemUtils::FemDoFsOnNodes::~FemDoFsOnNodes ()
Definition at line 62 of file FemDoFsOnNodes.cc.
Member Function Documentation
dofFamily()
IItemFamily * Arcane::FemUtils::FemDoFsOnNodes::dofFamily () const
Definition at line 154 of file FemDoFsOnNodes.cc.
initialize()
void Arcane::FemUtils::FemDoFsOnNodes::initialize (Arcane::IMesh * mesh, Arcane::Int32 nb_dof_per_node)
Initialize the instance.
Definition at line 136 of file FemDoFsOnNodes.cc.
Referenced by FemModuleAcoustics::startInit(), FemModuleAerodynamics::startInit(), FemModuleBilaplacian::startInit(), FemModuleElasticity::startInit(), FemModuleElastodynamics::startInit(), FemModuleElectrostatics::startInit(), FemModuleFourier::startInit(), FemModuleFourierNL::startInit(), FemModuleHeat::startInit(), FemModuleLaplace::startInit(), FemModulePoisson::startInit(), and FemModuleTestlab::startInit().
nodeDoFConnectivityView()
IndexedNodeDoFConnectivityView Arcane::FemUtils::FemDoFsOnNodes::nodeDoFConnectivityView () const
Definition at line 145 of file FemDoFsOnNodes.cc.
Member Data Documentation
m_p
Impl* Arcane::FemUtils::FemDoFsOnNodes::m_p = nullptr private
Definition at line 75 of file FemDoFsOnNodes.h.
The documentation for this class was generated from the following files:
FemDoFsOnNodes.h
FemDoFsOnNodes.cc