ArcaneFem: Arcane::FemUtils::CooFormat Class Reference
Arcane::FemUtils::CooFormat Class Reference
Public Member Functions
CooFormat (ITraceMng *tm)
void initialize (IItemFamily *dof_family, Int32 nnz, RunQueue &queue)
void matrixAddValue (DoFLocalId row, DoFLocalId column, Real value)
void translateToLinearSystem (DoFLinearSystem &linear_system)
Translate to Arcane linear system.
void printMatrix (std::string fileName, bool nonzero)
function to print the current content of the csr matrix
void setCoordinates (DoFLocalId row, DoFLocalId column)
void sort ()
Int32 getValue (DoFLocalId row, DoFLocalId column)
Int32 binSearchRow (Int32 row)
binSearchRow is a binary search through the row to get the leftmost corresponding index.
Int32 indexValue (Int32 row, Int32 column)
indexValue is a Binsearch through the row and then the column to get the index of the corresponding value.
void sortMatrix (bool is_row, Int32 start, Int32 end)
Quicksort algorithm for the CSR Matrix.
Int32 partition (bool is_row, Int32 start, Int32 end)
Partition helper for the quickSort.
void swap (bool is_row, Int32 i, Int32 j)
Swap helper for the quickSort.
Public Attributes
Int32 m_nnz
Int32 m_last_value
NumArray< Int32, MDDim1 > m_matrix_row
NumArray< Int32, MDDim1 > m_matrix_column
NumArray< Real, MDDim1 > m_matrix_value
IItemFamily * m_dof_family = nullptr
Detailed Description
Definition at line 38 of file CooFormatMatrix.h.
Constructor & Destructor Documentation
CooFormat()
Arcane::FemUtils::CooFormat::CooFormat (ITraceMng * tm) inline explicit
Definition at line 42 of file CooFormatMatrix.h.
Member Function Documentation
binSearchRow()
Int32 Arcane::FemUtils::CooFormat::binSearchRow (Int32 row) inline
binSearchRow is a binary search through the row to get the leftmost corresponding index.
Parameters
row
Returns
Int32
Definition at line 175 of file CooFormatMatrix.h.
Referenced by indexValue().
getValue()
Int32 Arcane::FemUtils::CooFormat::getValue (DoFLocalId row, DoFLocalId column) inline
Definition at line 163 of file CooFormatMatrix.h.
indexValue()
Int32 Arcane::FemUtils::CooFormat::indexValue (Int32 row, Int32 column) inline
indexValue is a Binsearch through the row and then the column to get the index of the corresponding value.
Parameters
row
column
Returns
Int32
Definition at line 205 of file CooFormatMatrix.h.
References binSearchRow().
Referenced by matrixAddValue().
initialize()
void Arcane::FemUtils::CooFormat::initialize (IItemFamily * dof_family, Int32 nnz, RunQueue & queue) inline
Definition at line 48 of file CooFormatMatrix.h.
matrixAddValue()
void Arcane::FemUtils::CooFormat::matrixAddValue (DoFLocalId row, DoFLocalId column, Real value) inline
Parameters
row
column
value
Definition at line 75 of file CooFormatMatrix.h.
References indexValue().
Referenced by FemModuleTestlab::_assembleCooBilinearOperatorTETRA4(), FemModuleTestlab::_assembleCooBilinearOperatorTRIA3(), FemModuleTestlab::_assembleCooSortBilinearOperatorTETRA4(), and FemModuleTestlab::_assembleCooSortBilinearOperatorTRIA3().
partition()
Int32 Arcane::FemUtils::CooFormat::partition (bool is_row, Int32 start, Int32 end) inline
Partition helper for the quickSort.
Parameters
is_row
start
end
Returns
Int32
Definition at line 262 of file CooFormatMatrix.h.
References swap().
Referenced by sortMatrix().
printMatrix()
void Arcane::FemUtils::CooFormat::printMatrix (std::string fileName, bool nonzero) inline
function to print the current content of the csr matrix
Parameters
fileName
nonzero if set to true, print only the non zero values
Definition at line 105 of file CooFormatMatrix.h.
setCoordinates()
void Arcane::FemUtils::CooFormat::setCoordinates (DoFLocalId row, DoFLocalId column) inline
Definition at line 129 of file CooFormatMatrix.h.
sort()
void Arcane::FemUtils::CooFormat::sort () inline
Definition at line 136 of file CooFormatMatrix.h.
sortMatrix()
void Arcane::FemUtils::CooFormat::sortMatrix (bool is_row, Int32 start, Int32 end) inline
Quicksort algorithm for the CSR Matrix.
Parameters
is_row
start
end
Definition at line 241 of file CooFormatMatrix.h.
References partition(), and sortMatrix().
Referenced by sortMatrix().
swap()
void Arcane::FemUtils::CooFormat::swap (bool is_row, Int32 i, Int32 j) inline
Swap helper for the quickSort.
Parameters
is_row
i
j
Definition at line 292 of file CooFormatMatrix.h.
Referenced by partition().
translateToLinearSystem()
void Arcane::FemUtils::CooFormat::translateToLinearSystem (DoFLinearSystem & linear_system) inline
Translate to Arcane linear system.
Parameters
linear_system
Definition at line 91 of file CooFormatMatrix.h.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
Member Data Documentation
m_dof_family
IItemFamily* Arcane::FemUtils::CooFormat::m_dof_family = nullptr
Definition at line 158 of file CooFormatMatrix.h.
m_last_value
Int32 Arcane::FemUtils::CooFormat::m_last_value
Definition at line 154 of file CooFormatMatrix.h.
m_matrix_column
NumArray<Int32, MDDim1> Arcane::FemUtils::CooFormat::m_matrix_column
Definition at line 156 of file CooFormatMatrix.h.
m_matrix_row
NumArray<Int32, MDDim1> Arcane::FemUtils::CooFormat::m_matrix_row
Definition at line 155 of file CooFormatMatrix.h.
m_matrix_value
NumArray<Real, MDDim1> Arcane::FemUtils::CooFormat::m_matrix_value
Definition at line 157 of file CooFormatMatrix.h.
m_nnz
Int32 Arcane::FemUtils::CooFormat::m_nnz
Definition at line 150 of file CooFormatMatrix.h.
The documentation for this class was generated from the following file:
CooFormatMatrix.h