ArcaneFem: FemModuleAcoustics Class Reference
FemModuleAcoustics Class Reference
A module for finite element method.
#include <modules/acoustics/FemModule.h>
Public Member Functions
FemModuleAcoustics (const ModuleBuildInfo &mbi)
void startInit () override
Initializes the FemModuleAcoustics at the start of the simulation.
void compute () override
Method called at the beginning of the simulation.
VersionInfo versionInfo () const override
Method called at each iteration.
Private Member Functions
void _doStationarySolve ()
Performs a stationary solve for the FEM system.
void _getMaterialParameters ()
void _assembleBilinearOperator ()
Calls the right function for LHS assembly.
void _solve ()
Solves the linear system and updates the solution vector.
void _assembleLinearOperator ()
Assembles the FEM linear operator.
void _updateVariables ()
Update the FEM variables.
void _validateResults ()
Validates and prints the results of the FEM computation.
RealMatrix< 3, 3 > _computeElementMatrixTria3 (Cell cell)
Computes the element matrix for a triangular element (ℙ1 FE).
RealMatrix< 4, 4 > _computeElementMatrixTetra4 (Cell cell)
RealMatrix< 4, 4 > _computeElementMatrixQuad4 (Cell cell)
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
RealMatrix< 8, 8 > _computeElementMatrixHexa8 (Cell cell)
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
template<int N>
void _assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> &compute_element_matrix)
Assembles the bilinear operator matrix for the FEM linear system.
Private Attributes
Real m_kc2
DoFLinearSystem m_linear_system
IItemFamily * m_dof_family = nullptr
FemDoFsOnNodes m_dofs_on_nodes
String m_petsc_flags
String m_matrix_format = "DOK"
bool m_assemble_linear_system = true
bool m_solve_linear_system = true
bool m_cross_validation = false
bool m_hex_quad_mesh = false
Detailed Description
A module for finite element method.
This class handles the initialization and computation for finite element method (FEM) simulations, providing methods to set up and solve linear systems, assemble FEM operators, and perform result checks.
Definition at line 53 of file acoustics/FemModule.h.
Constructor & Destructor Documentation
FemModuleAcoustics()
FemModuleAcoustics::FemModuleAcoustics (const ModuleBuildInfo & mbi) inline explicit
Definition at line 58 of file acoustics/FemModule.h.
Member Function Documentation
_assembleBilinear()
template<int N> void FemModuleAcoustics::_assembleBilinear (const std::function< RealMatrix< N, N >(const Cell &)> & compute_element_matrix) private
Assembles the bilinear operator matrix for the FEM linear system.
The method performs the following steps:
Computes element matrix using provided compute_element_matrix function.
Assembles global matrix by adding contributions from each cell's element matrix to the corresponding entries in the global matrix.
Definition at line 210 of file acoustics/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::matrixAddValue().
_assembleBilinearOperator()
void FemModuleAcoustics::_assembleBilinearOperator () private
Calls the right function for LHS assembly.
Definition at line 177 of file acoustics/FemModule.cc.
References _computeElementMatrixHexa8(), _computeElementMatrixQuad4(), _computeElementMatrixTria3(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_assembleLinearOperator()
void FemModuleAcoustics::_assembleLinearOperator () private
Assembles the FEM linear operator.
This method assembles the RHS 'b' of the linear system by:
Initializing the RHS values to zero.
Iterating over Neumann boundary conditions to apply it to RHS.
Definition at line 138 of file acoustics/FemModule.cc.
References ArcaneFemFunctions::BoundaryConditions3D::applyNeumannToRhs(), ArcaneFemFunctions::BoundaryConditions2D::applyNeumannToRhs(), Arcane::FemUtils::RealMatrix< N, M >::fill(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::rhsVariable().
Referenced by _doStationarySolve().
_computeElementMatrixHexa8()
RealMatrix< 8, 8 > FemModuleAcoustics::_computeElementMatrixHexa8 (Cell cell) private
Computes the element matrix for a hexahedral element (HEXA8, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦 + ∂𝑢/∂𝑧 ∂𝑣/∂𝑧)dΩ + ∫∫∫ 𝑘²𝑢𝑣 dΩ
Steps involved:
Define Gauss points (2x2x2) and weights.
Loop over Gauss points to compute the gradients in physical space (𝑥,𝑦,𝑧) and the determinant of the Jacobian via computeGradientsAndJacobianHexa8.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 89 of file acoustics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation3D::computeGradientsAndJacobianHexa8(), ArcaneFemFunctions::FeOperation3D::computeShapeFunctionsHexa8(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixQuad4()
RealMatrix< 4, 4 > FemModuleAcoustics::_computeElementMatrixQuad4 (Cell cell) private
Computes the element matrix for a quadrilateral element (QUAD4, ℙ1 FE).
This function calculates the integral of: 𝑎(𝑢,𝑣) = ∫∫ (∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ + ∫∫ 𝑘²𝑢𝑣 dΩ
Steps involved:
Define Gauss points (2x2) and weights.
Loop over Gauss points to compute the gradients in physical space and the determinant of the Jacobian, via computeGradientsAndJacobianQuad4.
Compute the integration weight.
Assemble the element matrix using the computed gradients.
Parameters
cell The cell for which the element matrix is computed.
Returns
The computed element matrix.
Definition at line 33 of file acoustics/ElementMatrixHexQuad.h.
References ArcaneFemFunctions::FeOperation2D::computeGradientsAndJacobianQuad4(), ArcaneFemFunctions::FeOperation2D::computeShapeFunctionsQuad4(), and Arcane::FemUtils::RealMatrix< N, M >::fill().
Referenced by _assembleBilinearOperator().
_computeElementMatrixTetra4()
RealMatrix< 4, 4 > FemModuleAcoustics::_computeElementMatrixTetra4 (Cell cell) private
Definition at line 55 of file acoustics/ElementMatrix.h.
_computeElementMatrixTria3()
RealMatrix< 3, 3 > FemModuleAcoustics::_computeElementMatrixTria3 (Cell cell) private
Computes the element matrix for a triangular element (ℙ1 FE).
This function calculates the integral of the expression: a(𝑢,𝑣) = ∫∫ -(∂𝑢/∂𝑥 ∂𝑣/∂𝑥 + ∂𝑢/∂𝑦 ∂𝑣/∂𝑦)dΩ + ∫∫ 𝑘²𝑢𝑣 dΩ
Steps involved:
Calculate the area of the triangle.
Compute the gradients of the shape functions.
Return a(𝑢,𝑣);
Definition at line 28 of file acoustics/ElementMatrix.h.
References ArcaneFemFunctions::MeshOperation::computeAreaTria3(), ArcaneFemFunctions::FeOperation2D::computeGradientXTria3(), and ArcaneFemFunctions::FeOperation2D::computeGradientYTria3().
Referenced by _assembleBilinearOperator().
_doStationarySolve()
void FemModuleAcoustics::_doStationarySolve () private
Performs a stationary solve for the FEM system.
This method follows a sequence of steps to solve FEM system:
_getMaterialParameters() Retrieves material parameters via
_assembleBilinearOperator() Assembles the FEM matrix 𝑨
_assembleLinearOperator() Assembles the FEM RHS vector 𝒃
_solve() Solves for solution vector 𝒖 = 𝑨⁻¹𝒃
_updateVariables() Updates FEM variables 𝒖 = 𝒙
_validateResults() Regression test
Definition at line 95 of file acoustics/FemModule.cc.
References _assembleBilinearOperator(), _assembleLinearOperator(), _solve(), _updateVariables(), and _validateResults().
Referenced by compute().
_getMaterialParameters()
void FemModuleAcoustics::_getMaterialParameters () private
Definition at line 116 of file acoustics/FemModule.cc.
_solve()
void FemModuleAcoustics::_solve () private
Solves the linear system and updates the solution vector.
This method performs the following actions:
Solves the linear system to compute the solution.
Copies the computed solution from the DoF to the node values.
Synchronizes the updated node values.
Definition at line 244 of file acoustics/FemModule.cc.
References Arcane::FemUtils::DoFLinearSystem::applyLinearSystemTransformationAndSolve(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
_updateVariables()
void FemModuleAcoustics::_updateVariables () private
Update the FEM variables.
This method performs the following actions:
Fetches values of solution from solved linear system to FEM variables, i.e., it copies RHS DOF to u.
Performs synchronize of FEM variables across subdomains.
Definition at line 267 of file acoustics/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), and Arcane::FemUtils::DoFLinearSystem::solutionVariable().
Referenced by _doStationarySolve().
_validateResults()
void FemModuleAcoustics::_validateResults () private
Validates and prints the results of the FEM computation.
This method performs the following actions:
If number of nodes < 200, prints the computed values for each node.
Retrieves the filename for the solution-comparison-file from options.
Checks the computed results against solution-comparison-file.
Note
The result comparison uses a tolerance of 1.0e-4.
Definition at line 301 of file acoustics/FemModule.cc.
References ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
Referenced by _doStationarySolve().
compute()
void FemModuleAcoustics::compute () override
Method called at the beginning of the simulation.
Performs the main computation for the FemModuleAcoustics.
This method:
Stops the time loop after 1 iteration since the equation is steady state.
Resets, configures, and initializes the linear system.
Executes the stationary solve.
Definition at line 57 of file acoustics/FemModule.cc.
References _doStationarySolve(), ArcaneFemFunctions::GeneralFunctions::getPetscFlagsFromCommandline(), ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime(), Arcane::FemUtils::DoFLinearSystem::reset(), and Arcane::FemUtils::DoFLinearSystem::setLinearSystemFactory().
startInit()
void FemModuleAcoustics::startInit () override
Initializes the FemModuleAcoustics at the start of the simulation.
This method initializes degrees of freedom (DoFs) on nodes.
Definition at line 26 of file acoustics/FemModule.cc.
References Arcane::FemUtils::FemDoFsOnNodes::initialize(), and ArcaneFemFunctions::GeneralFunctions::printArcaneFemTime().
versionInfo()
VersionInfo FemModuleAcoustics::versionInfo () const inline override
Method called at each iteration.
Definition at line 69 of file acoustics/FemModule.h.
Member Data Documentation
m_assemble_linear_system
bool FemModuleAcoustics::m_assemble_linear_system = true private
Definition at line 82 of file acoustics/FemModule.h.
m_cross_validation
bool FemModuleAcoustics::m_cross_validation = false private
Definition at line 84 of file acoustics/FemModule.h.
m_dof_family
IItemFamily* FemModuleAcoustics::m_dof_family = nullptr private
Definition at line 76 of file acoustics/FemModule.h.
m_dofs_on_nodes
FemDoFsOnNodes FemModuleAcoustics::m_dofs_on_nodes private
Definition at line 77 of file acoustics/FemModule.h.
m_hex_quad_mesh
bool FemModuleAcoustics::m_hex_quad_mesh = false private
Definition at line 85 of file acoustics/FemModule.h.
m_kc2
Real FemModuleAcoustics::m_kc2 private
Definition at line 73 of file acoustics/FemModule.h.
m_linear_system
DoFLinearSystem FemModuleAcoustics::m_linear_system private
Definition at line 75 of file acoustics/FemModule.h.
m_matrix_format
String FemModuleAcoustics::m_matrix_format = "DOK" private
Definition at line 80 of file acoustics/FemModule.h.
m_petsc_flags
String FemModuleAcoustics::m_petsc_flags private
Definition at line 79 of file acoustics/FemModule.h.
m_solve_linear_system
bool FemModuleAcoustics::m_solve_linear_system = true private
Definition at line 83 of file acoustics/FemModule.h.
The documentation for this class was generated from the following files:
acoustics/FemModule.h
acoustics/ElementMatrix.h
acoustics/ElementMatrixHexQuad.h
acoustics/FemModule.cc